### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#135] opened 2015-07-17 15:58 UTC
There are no language change link in V4

**Comment by Data66PF** [comment] 2015-07-20 17:01
closing as it is a duplicate of #137 but that one has more details.

**Comment by Ylmzef** [comment] 2015-07-23 00:30
I mean on frontpage.

**Comment by Data66PF** [comment] 2015-07-23 11:56
Use phrase manager. Please post normal questions in the community as this is not a bug if you want to change phrases. Please note that we already posted how to change the front page photos, just feature a photo in your photo section. Other questions need to be in the community forum as this is not a bug

**Comment by Ylmzef** [comment] 2015-07-23 18:16
I mean not phrase, its about language of the site.
Please read good. "There are no language change link in V4"

**Comment by Data66PF** [comment] 2015-07-23 18:50
You said on front page after that. Do you mean in the footer of the site? Since there is no way to install a language yet, I'm not sure the change language would show up.

**Comment by Ylmzef** [comment] 2015-07-24 02:00
I have upgraded from v3 therefor i have 5 languages in admincp.
But no links in the footer for changing the language.

**Comment by Data66PF** [comment] 2015-07-24 13:55
Ok I've reopened this for him to look at.

**Comment by RaymondBenc** [comment] 2015-07-27 19:19
We won't be adding this by default in our product. Since its menu based, a link can be added from the AdminCP and have it point to **/user/setting/**. Just place the link in the footer.

**Closed by RaymondBenc** 2015-07-27 19:19 UTC
Labels: bug

**Comment by Ylmzef** [comment] 2015-07-28 22:53
Remove this settings than please.
![download 1](https://cloud.githubusercontent.com/assets/8562514/8945916/2a96524e-358c-11e5-8967-902cb7027dfb.png)

**Comment by Jarkko82** [comment] 2015-08-28 08:27
Hi. Where can I find that page "Language Package Helper"
