### ISSUE TITLE
Languege export.

### ISSUE THREAD

**Issue by kaligula7** [moxi9/phpfox#1686] opened 2016-10-04 13:12 UTC
I can not export the languages.
The ZIP file is o bytes large. (See the picture)
![lang export](https://cloud.githubusercontent.com/assets/21354832/19075388/0231d828-8a45-11e6-9bbc-e06f0636886e.JPG)

Wersion 4.4.3.
Update from 3.9 to 4.4.2 and 4.4.3. 

Does anyone else have the problem?

**Comment by neil96** [comment] 2016-10-05 01:57
It's the same with #1496 that is marked as fixed from 4.4.0.
I can't reproduce on 4.4.3 now. Are you follow all steps of upgrade to new version?

**Comment by kaligula7** [comment] 2016-10-05 12:42
Yes, I did - all steps in sequence.

**Comment by neil96** [comment] 2016-10-06 01:52
What is php version on your server?
Are you enable debug?...
Please tell me some special of your server. Thanks!

**Comment by kaligula7** [comment] 2016-10-06 12:51
I have PHP version 5.6.26, run as FastCGI application served by Apache.

When I turn debug to on, and try the language export, then comes error site with the message: The file http://www.mysite.de/admincp/language/?export=en could not be found.

**Comment by kaligula7** [comment] 2016-10-06 13:22
Oups!!!

Thank you Neil96!
Here is a larger problem with debug.
I opened a support ticket.

**Closed** 2016-10-10 13:09 UTC
Labels: Cannot reproduce

**Comment by neil96** [comment] 2016-10-11 01:58
The issue is resolved. If someone get this issue, please check again this php configuration: ** allow_url_fopen**
