### ISSUE TITLE
Change user name

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#640] opened 2015-10-19 06:38 UTC
When a member changes their user name in My Account front end it does not check if name already in use.

**Comment by Data66PF** [comment] 2015-10-19 10:42
I cannot reproduce this for Username. Displayname can always be the same as it is just what is displayed. Username, however, gives me an error any time I try to put it at one that exists. Tested with 4.0.9 with a registered user account group.

**Comment by one44** [comment] 2015-10-19 11:11
Ok I see For some reason the Online members app shows user name whereas site uses display name.

**Comment by Data66PF** [comment] 2015-10-19 11:12
ok I'll close this and you would want to contact that developer for a fix.

**Closed by Data66PF** 2015-10-19 11:12 UTC
Labels: cannot reproduce
