### ISSUE TITLE
New users avatar and profile cover photo uploads and photogallery.

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#755] opened 2015-11-27 22:59 UTC
v4.1.0b2
New users avatar and profile cover photo gets uploaded by default into the photo gallery and have to be deleted from that users gallery photo edit tool. 

When deleted, the avatar is persistent (remained afterward), but the user loses the cover photo in profile.  If you wanted it in your profile as a cover, you have to settle for it being in the photo gallery to.

Neither avatar nor cover photo should appear in the photo gallery when uploaded within profile.

**Comment by Data66PF** [comment] 2015-11-28 12:36
This was already posted in the pre-release bugs I found but was not addressed yet. will confirm since you've posted it here. 

We need to bring back the setting that we had a huge amount of clients asking for in our old feature request system as it was a top voted item. The setting to Keep User Profile Photos from the photo section.It was working fine prior to this release. 

Please remove cover photos from showing in the main photo section as they didn't do that before.

 Please bring the setting back to allow us to choose if profile photos appear or not. Many sites want them in there, many sites don't. We need that setting back so that webmasters choose if profile photos show in the main photo section.

**Comment by Gatsby-PF** [comment] 2015-12-16 21:56
It would be nice if this issue was taken care of prior to the next release. Use of the photo gallery is understandable if a generic set of avatars is to be offered to users in and avatar album, but to publish the mug they upload to their users area but unintentionally to in the public photo-gallery borders on, but is not quite a privacy issue. They should not have to search for it, go there and delete.

**Comment by Data66PF** [comment] 2015-12-16 22:41
Agreed. I hope so too. This is very important to many sites. We (clients) fought to have the setting to remove profile photos from the gallery. We do want it back please. @RaymondBenc @phpfoxdev @Vivian-phpFox @neil96 I figure one of these will see it now. :)

**Comment by Data66PF** [comment] 2015-12-23 12:18
I can still reproduce this in 4.1.2. Need a fix please. :)

**Comment by neil96** [comment] 2015-12-25 10:58
Fixed on V4.2.0

**Closed** 2016-01-14 04:40 UTC
Labels: Bug, Fixed
