### ISSUE TITLE
profile pic in user popup

### ISSUE THREAD

**Issue by lordofnos** [moxi9/phpfox#74] opened 2015-07-12 13:40 UTC
i do not see any user profile pics in the popup

**Comment by RaymondBenc** [comment] 2015-07-13 13:06
Are these the popups we see when we hover over a users name?

I tested this locally and couldn't reproduce it so it might have been fixed in an earlier build.

**Comment by lordofnos** [comment] 2015-07-13 14:00
yes when hovering over usernames. also an issue on phpfox community. i can see only white space with latest firefox

**Comment by GloriousKoch** [comment] 2015-07-14 10:56
Can confirm I'm having the same issue as @lordofnos on both my site and the PHPfox community site. However, it only seems to be randomly. It works on some and others it doesn't. Been playing around a bit with it and can't seem to find a common ground quite yet for the ones it doesn't work on, other than the ones it DOESN'T show up on, are user uploaded images. Anyone without a default image where PHPfox puts the two letters in, seems to show up fine in the boxes.

**Comment by Data66PF** [comment] 2015-07-20 17:33
I think this is related to #146

**Comment by Data66PF** [comment] 2015-07-24 13:41
This is still an issue on the PF community.

**Comment by RaymondBenc** [comment] 2015-07-25 16:07
Issue has been resolved for next version, 4.0.4.

**Closed by RaymondBenc** 2015-07-25 16:07 UTC
Labels: bug
