### ISSUE TITLE
custom fields

### ISSUE THREAD

**Issue by alexsilva8** [moxi9/phpfox#170] opened 2015-07-21 20:19 UTC
does not give option to add options
![error1](https://cloud.githubusercontent.com/assets/12040099/8811484/e8837ccc-2fbb-11e5-990e-8a896695a2fb.jpg)

**Comment by Data66PF** [comment] 2015-07-21 21:19
Please check the open issues before posting. This is a duplicate of #108

**Closed by Data66PF** 2015-07-21 21:19 UTC
