### ISSUE TITLE
Friends Not In Phrase

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#1243] opened 2016-03-23 11:13 UTC
when someone is not our freind and we try to send a message then pop up comes.in this pop up friends is not in phrase
and when someone closed his friend in privacy setting and we click on friends in his timeline then in msg friends not in phrase value is hard code in both cases
i check in latest v4.0.3 build 5
![friend phrase](https://cloud.githubusercontent.com/assets/13433124/13983537/4fd1fd60-f116-11e5-81ec-00f9c9fd66b2.png)
![friennd phrase2](https://cloud.githubusercontent.com/assets/13433124/13983538/4fd922f2-f116-11e5-9e00-b0083626cb8b.png)

**Comment by Data66PF** [comment] 2016-03-23 17:07
Did you check in v4.3.0 build 5? You say 4.0.3

**Comment by SalmanKhan86** [comment] 2016-03-23 17:45
Yes..check it

**Comment by Data66PF** [comment] 2016-03-23 18:43
Please start putting v4.3.0 for your bugs as you have been putting 4.0.3 which makes us ask the question about what version you are using.

**Comment by Data66PF** [comment] 2016-03-24 13:51
Using a Spanish language pack to test, I cannot reproduce the issue.

![friends](https://cloud.githubusercontent.com/assets/6908282/14018807/f60bc82a-f1a5-11e5-87c8-150dee0df41e.png)

**Comment by Data66PF** [comment] 2016-03-24 14:03
Please post only one issue per bug report from now on for our testing. It makes it easier to mark bugs. We will not be able to accept any more with multiple issues posted.

The second issue can be reproduced for this phrase:
friend.user_link_has_closed_their_friends_section

**Comment by neil96** [comment] 2016-03-25 02:09
Fixed on V4.3.1

**Closed** 2016-04-04 14:36 UTC
Labels: Bug, Fixed
