### ISSUE TITLE
Parsing links: When a website is missing the character encode phpfox display weird anomally

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1179] opened 2016-03-02 04:24 UTC
Parsing links (to post on status): When a website is missing the character encode phpfox display weird anomaly. In my case it showed the name of my corporate name even though it is someone else website. It should never do this.

**Comment by Data66PF** [comment] 2016-03-04 12:32
screen shot please.

**Comment by lueung** [comment] 2016-03-04 13:49
Hmmm... I didn't take a screenshot @ the time, but I had the site owner fix his site by adding character encode and it picked up the title, where before when the the site was missing the character encode it wouldn't pick anything up and instead displays the sites' url and the name of my server.

**Comment by robert9592** [comment] 2016-03-11 03:00
I cannot reproduce in v4.3.0.

**Comment by lueung** [comment] 2016-03-18 04:28
It's still doing the same thing under v4.3 This is what I mean: http://prntscr.com/agopjh

The link is this: http://www.exchangewar.info/coinprice?ORB_BTC

**Comment by neil96** [comment] 2016-03-22 04:59
Fixed on 4.3.1

**Closed** 2016-04-04 14:59 UTC
Labels: Bug, Fixed
