### ISSUE TITLE
Search is not correctly aligned in "Pages"

### ISSUE THREAD

**Issue by cleger80** [moxi9/phpfox#626] opened 2015-10-15 22:43 UTC
The Search is not correctly aligned with the elements of the page and the banner.
Moreover, the "edit" button is not correctly aligned too.
Tested on Chrome Version 46.0.2490.71
![events_ _social_networking_community](https://cloud.githubusercontent.com/assets/15106126/10529520/d7b3d258-739e-11e5-880c-ad8360579bb1.jpg)

**Comment by Data66PF** [comment] 2015-10-16 10:37
Cannot reproduce at the community using Chrome latest version on win 10 and screen resolution of 1920 x 1080. Please state your screen resolution and please don't use the browser resize to try to test the responsive layout.

**Comment by t2nttn** [comment] 2015-10-16 10:44
Please try event on pages, example: http://community.phpfox.com/pages/691/event/

**Comment by cleger80** [comment] 2015-10-16 10:51
If the window is less than 1430px, we have the problem.

**Comment by Data66PF** [comment] 2015-10-16 11:11
I did try event. Please state the screen size you have and please be sure you are not just resizing the browser window.

**Comment by cleger80** [comment] 2015-10-16 14:15
I am resizing the window. It is not possible to do it ? I can not give this answer to clients...
When you have a big screen you can reduce your window to 1200px for example. Then you can see the issue.

**Comment by Data66PF** [comment] 2015-10-16 14:24
That is not how to test responsive design. A responsive design shows based on the screen size of the device, not the resizing browser. You need to test on a mobile device to see the view from that as the design will adjust accordingly. Are you adjusting your actual screen resolution or are you only adjusting via the browser resize? If just on the browser then that is not the proper way to test.

**Comment by cleger80** [comment] 2015-10-16 14:26
Well, I do not want to test responsive design. I just want to test PHPfox. You can not tell to a user not to resize his window...

**Comment by Data66PF** [comment] 2015-10-16 14:27
For testing the responsiveness of the design, you need to test an actual environment. I can test other screen resolutions if I know what resolution you tested to get a bad result.

**Comment by Data66PF** [comment] 2015-10-16 14:34
I tested all of my display settings going down until I got to 1400 x 1050. At that point the search extends beyond the cover page and center column and is not aligned as it is for the higher resolution. Perhaps a core developer can check on this issue. tested at the community with chrome on win 10.

**Comment by neil96** [comment] 2016-01-05 16:07
Fixed on V4.2.0

**Closed** 2016-01-19 13:50 UTC
Labels: Bug, Fixed, Minor
