### ISSUE TITLE
Not Able to play video

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#1159] opened 2016-02-24 05:41 UTC
i have set up video plugin in v 4.2.2 and video uploaded successfully but i am not able to play it.

in Mozilla Firefox its gives following error.
no video with supported format and no mime type found.  
![video upload bug](https://cloud.githubusercontent.com/assets/13433124/13276616/3eea1400-dae7-11e5-9eb0-b3c6883f5246.png)

in chrome play button is not clickable.
![video problem](https://cloud.githubusercontent.com/assets/13433124/13276619/42a51f22-dae7-11e5-9561-fcd3847d1788.png)

**Comment by Data66PF** [comment] 2016-02-24 10:45
Cannot reproduce at our demo https://v4.phpfox.com on a macbook pro, El Capitan, using firefox latest and chrome https://v4.phpfox.com/v/play/115873

**Comment by SalmanKhan86** [comment] 2016-02-24 10:46
what is the solution of this problem..
i am able reproduce it at my live website..

**Comment by Lidercan** [comment] 2016-02-28 23:10
I have some problem. I can't Play video. Tried with IE, Firefox etc.

**Comment by neil96** [comment] 2016-03-04 04:41
Please read this page: https://docs.phpfox.com/display/FOX4MAN/Setting+Up+the+Video+App and try again.

**Comment by SalmanKhan86** [comment] 2016-03-04 10:26
I Followed All the Required Steps gives in Above link.
but nothing Working.
but upload complete
in Mozilla Firefox i got error Message No Video With Supported format and Mime type found. and In chrome its Not Working
 i Also Followed Complete guide by https://foliovision.com/player/fix-amazon-mime-type
but not works

**Comment by SalmanKhan86** [comment] 2016-03-04 11:29
i am getting following error in Mozilla Firebug console
![video error](https://cloud.githubusercontent.com/assets/13433124/13525922/743e1bca-e22a-11e5-8d80-ab79b403605b.png)

**Comment by neil96** [comment] 2016-03-04 11:44
Hi @SalmanKhan86 , I tested on your site and I found 500 error when upload new video (Failed to load resource: the server responded with a status of 500 (Internal Server Error)). Please sure you config your site properly.

**Comment by SalmanKhan86** [comment] 2016-03-04 11:53
i followed all the steps correctly.
video is Successfully upload to my Amazon s3 account and processed by Zencoder but its not showing in my website.how can i solve it.

**Comment by neil96** [comment] 2016-03-07 04:20
Could you test again this step:

> Bucket Policy
> With your bucket created you know need to give Zencoder access to your bucket so they can upload files that have been encoded. To do this click on your new bucket and then click Properties. Then click on Permissions. 
> 
> We are looking for the Edit bucket policy link. Click on that to get a popup where you can enter your policy. Here is a sample policy 
> {  "Version": "2008-10-17",
>   "Id": "ZencoderBucketPolicy",
>   "Statement": [
>     {
>       "Sid": "Stmt1295042087538",
>       "Effect": "Allow",
>       "Principal": {
>         "AWS": "arn:aws:iam::395540211253:root"
>       },
>       "Action": [
>         "s3:GetObjectAcl",
>         "s3:GetObject",
>         "s3:PutObjectAcl",
>         "s3:PutObject",
>         "s3:ListMultipartUploadParts"
>       ],
>       "Resource": "arn:aws:s3:::MY-BUCKET/*"
>     },
>     {
>       "Sid": "Stmt1295042087538",
>       "Effect": "Allow",
>       "Principal": {
>         "AWS": "arn:aws:iam::395540211253:root"
>       },
>       "Action": [
>         "s3:ListBucketMultipartUploads",
>         "s3:GetBucketLocation"
>       ],
>       "Resource": "arn:aws:s3:::MY-BUCKET"
>     }
>   ]
> }
> Before Pasting: You need to change the words MY-BUCKET with the name of the bucket you just created. Once you have done that paste it into the bucket policy editor and hit Save.

Is it correct?

**Comment by SalmanKhan86** [comment] 2016-03-07 05:06
I Already Apply it.but same result.

**Comment by neil96** [comment] 2016-03-10 08:52
Could you submit a ticket with your site info. I will check your configuration.

**Comment by SalmanKhan86** [comment] 2016-03-10 10:20
Although everything is working fine now.
but when i open video link in new tab. following error found.
some permission issue is there.i have to manually give each video (everyone
permission).so that its in working mode. but is the solution of this
problem.i Already set my bucket with everyone(open/download)permission. so
why i have to set it manually for each video.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>BDBFCAE4F113F549</RequestId>
<HostId>
qcCs479RikRbPYJ1CRf7yAmqCvXF42AdVt0EaI6wbeCoooZqojjaWU0kaGRKIpGe1EAW8fwnWD0=
</HostId>
</Error>

On Thu, Mar 10, 2016 at 2:22 PM, Neil <notifications@github.com> wrote:

> Could you submit a ticket with your site info. I will check your
> configuration.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moxi9/phpfox/issues/1159#issuecomment-194739965>.
>



-- 
Thanks & Regards
Pankaj Garg
M.+91-9728598858

**Comment by SalmanKhan86** [comment] 2016-03-10 10:38
why all the files uploaded on Amazon s3 uploaded same also uploaded on my server
All video files goes to PF.Base/file/static folder
Its eats up my lots of server space.Big problem is there.

**Comment by Lidercan** [comment] 2016-03-10 16:58
Please write the solution here. I also have same problem.

**Comment by SalmanKhan86** [comment] 2016-03-11 04:41
follow this guide https://foliovision.com/player/fix-amazon-mime-type
if u are facing mime type error and also set bucket policy by following official tutorials  https://docs.phpfox.com/display/FOX4MAN/Setting+Up+the+Video+App

**Comment by Lidercan** [comment] 2016-03-11 15:09
I followed all the steps correctly. But some results...

**Comment by neil96** [comment] 2016-03-12 01:02
Please submit a ticket with your site info, I will check it for you.

**Comment by Lidercan** [comment] 2016-03-13 00:47
Hello neil96,
i can't find your Helpdesk Ticketsystem Page. Can You put here?

**Comment by neil96** [comment] 2016-03-14 09:56
@Lidercan I fixed on your site.

**Closed by neil96** 2016-03-14 09:56 UTC
Labels: Cannot reproduce
