### ISSUE TITLE
Alizarin theme - Register & forgot your password out of Alignment 

### ISSUE THREAD

**Issue by Lukey199223** [moxi9/phpfox#864] opened 2015-12-21 15:25 UTC
I've noticed the "Register and "Forgot your password button text on the log in screen is out of alignment, I tested it on the phpfox demo too

**Comment by Data66PF** [comment] 2015-12-21 16:04
I can't reproduce this in v4.1.2. Please provide a screen shot.

**Comment by Lukey199223** [comment] 2015-12-21 16:06
I zoomed in as much as I could without it getting blurry :) , 
![image](https://cloud.githubusercontent.com/assets/16384395/11934914/be2cc32a-a7fc-11e5-8a6f-0e68f505e76f.png)

**Comment by Lukey199223** [comment] 2015-12-21 16:07
![image](https://cloud.githubusercontent.com/assets/16384395/11934959/f8d6cade-a7fc-11e5-8288-df062ce8981e.png)
this is the phpfox demo one :)

**Comment by Data66PF** [comment] 2015-12-21 16:21
Ok that is the community. The demo is at http://v4.phpfox.com :) The community is using a special theme so we do need to fix it but that would not be for the core script, it is for the community special theme. 

for your site, what theme is that?

**Comment by Lukey199223** [comment] 2015-12-21 16:29
The Alizarin theme :)

**Comment by Data66PF** [comment] 2015-12-21 17:16
ok I'll edit the title for a tech to test that theme.

**Comment by Lukey199223** [comment] 2015-12-21 21:34
Ah awesome, thanks Donna :) , Sorry it took hours for me to get back to you, been down my sister's spending time with my nephews and sister :)

**Comment by Lukey199223** [comment] 2015-12-21 21:36
I'm still on 1.1, I'm waiting for the update 1.2 to come out, so Hopefully that'll fix it :)

**Comment by neil96** [comment] 2016-01-05 06:47
Fixed on V4.2.0

**Closed** 2016-01-13 09:23 UTC
Labels: Bug, Fixed
