### ISSUE TITLE
Liking an item such as photo, feed post doesn't show until refreshing the page

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#971] opened 2016-01-19 12:59 UTC
tested on your demo 4.2 site  (stage.phpfox.com) using windows 10 and chrome
whenever we like an item it is not instantly updating and  after doing a page refresh it says " you like it"

**Comment by Data66PF** [comment] 2016-01-19 13:43
confirmed on mac with chrome.

**Comment by neil96** [comment] 2016-01-19 14:20
This is not a bug, it's working as designed. Because after we like a page, we have more permission on this page. Example, admin set permission only member can post new comment, after you like that page, you can comment on it, if we don't refresh page, it can make user confuse.

**Comment by Data66PF** [comment] 2016-01-19 14:28
Please look again. This is not for liking a page. This is for liking an item such as a photo or anything in the feed.. Please test again.

**Comment by neil96** [comment] 2016-01-20 10:23
This bug only occur if debug mode turn on. Fixed on 4.2.1.

**Closed** 2016-02-02 09:01 UTC
Labels: Bug, Fixed
