### ISSUE TITLE
photo battles

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#1032] opened 2016-01-29 18:59 UTC
latest phpfox
I was previously told by data66 that photo battles is not a part of v4. but we can still see a link of photo battles under  www.ursite . com / photo

**Comment by aakash83** [comment] 2016-01-29 19:00
also  in photo sort options we can see  " Top Battle"

**Comment by Data66PF** [comment] 2016-01-30 10:39
I cannot reproduce this at the staging site or at the demo. When you upgraded, did you run the Find Missing Settings and clear cache?

**Comment by aakash83** [comment] 2016-01-30 16:34
i  did all those (rebuild theme , find missing theme) and cleared cache  but i can still see photo battles. 
![image](https://cloud.githubusercontent.com/assets/406030/12696959/9f1b9a2a-c777-11e5-8565-9e4b406a6731.png)

**Comment by Data66PF** [comment] 2016-02-03 15:50
More clients can reproduce this at the community forum. Marked a bug.

**Comment by SpeakLife** [comment] 2016-02-03 16:53
Upgraded to 4.2.1 and now the photo category list on the left hand side appeared. However there is still a link on the left hand side of the first section of categories that says "photo battles" When I click on it, it loads me back to the photos module page. Since the photo battles were a part of V3 and are not currently a part of V4, maybe there's a way I can manually remove this link or folder path so it doesn't auto appear on the next upgrade.

https://speaklife.com/photo/

**Comment by robert9592** [comment] 2016-02-04 06:47
Fixed in v4.3.0

**Closed** 2016-03-02 10:47 UTC
Labels: Bug, Fixed
