### ISSUE TITLE
favicon.ico not changing....

### ISSUE THREAD

**Issue by haisay** [moxi9/phpfox#388] opened 2015-08-21 11:55 UTC
Favicon not able to change. please check it.

i hosted my icon favicon.ico file in root directory. but still show the 'PF' icon.

**Comment by Jinkers** [comment] 2015-08-21 12:05
Cleared site cache and local cache? What version are you currently using?

**Comment by Data66PF** [comment] 2015-08-21 12:07
I cannot reproduce this with v4.0.7 on my live development site. As @Jinkers mentioned, please fully clear site cache and browser cache.

**Comment by haisay** [comment] 2015-08-22 08:00
v4.0.7
i tried all the way.
as well as new pc also.
root directory .ico file also right.

**Comment by mobicomfi** [comment] 2015-08-23 15:44
Enable short url, i was same problem and if i activate short url, then it works fine

**Comment by ESA55** [comment] 2015-09-24 02:46
Rename the file favicon.ico deleting the extension .jpg or .png

**Comment by Data66PF** [comment] 2015-10-30 16:01
This seems a bug when short urls are not enabled as I can confirm at a client's site.

**Comment by Data66PF** [comment] 2015-11-13 11:55
Fixed in v4.0.10 *staff note YPFOXNEUTRON-132 *

**Closed by Data66PF** 2015-11-13 11:55 UTC
Labels: Bug, Minor
