### ISSUE TITLE
Multiple Comment Boxes/Double Profile Name

### ISSUE THREAD

**Issue by orgazilla** [moxi9/phpfox#138] opened 2015-07-18 02:20 UTC
When you click on a users main profile picture, then you click their picture, you will be able to comment their picture. But everything multiplies...

![double1](https://cloud.githubusercontent.com/assets/13330878/8759938/bd127990-2cd1-11e5-95ef-9b60867fd157.jpg)

Double Profile Name
![double4](https://cloud.githubusercontent.com/assets/13330878/8760115/c3bc7230-2cd8-11e5-8d36-c15c03566b68.jpg)

**Comment by Jinkers** [comment] 2015-07-18 02:23
Confirmed. Looks like it loops continuously to load the details.

**Comment by Data66PF** [comment] 2015-07-20 16:58
Closing this as it is a duplicate of #98

**Closed by Data66PF** 2015-07-20 16:58 UTC
Labels: duplicate
