### ISSUE TITLE
Users cant login after successful registration

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#279] opened 2015-08-06 12:06 UTC
Im trying login after successful registration but i cant login to phpfox with correctly details.
I need recovery for first login to phpfox site.
After recovered password i can login to site.
I tryed this a few times with different accounts.

**Comment by Ylmzef** [comment] 2015-08-06 13:22
http://community.phpfox.com/forum/thread/52243/password-not-accepted-after-registration/

**Comment by Data66PF** [comment] 2015-08-06 13:52
Do you mean you can't log into the PHPfox community or your website?

**Comment by Ylmzef** [comment] 2015-08-06 14:37
I dont tested it in phpfox community but well in some phpfox clients sites.

**Comment by Data66PF** [comment] 2015-08-06 15:12
can't reproduce this. v4.0.5. Chrome browser. I used the password reset. got a new password. used it to log into my dev site.

**Comment by Ylmzef** [comment] 2015-08-06 15:24
password reset working fine for me too but this about first password durring the registiration.
First password is not working for login.

**Comment by Data66PF** [comment] 2015-08-06 15:48
I'm not having that issue and I've installed several sites. I'll test once more though

**Comment by Data66PF** [comment] 2015-08-06 15:50
tested again and it's working fine for me.

**Comment by qsrs** [comment] 2015-08-07 06:19
The issue appears since the update from V3 to V4. I can see that the encrypted passwords, stored in the database, begins with $2y$10$ since I have updated to V4. That means V4 uses native password hashing which is supported since PHP 5.5. My server is running 5.5.9, hashing is enabled, supported hashing engines are:

md2 md4 md5 sha1 sha224 sha256 sha384 sha512 ripemd128 ripemd160 ripemd256 ripemd320 whirlpool tiger128,3 tiger160,3 tiger192,3 tiger128,4 tiger160,4 tiger192,4 snefru snefru256 gost adler32 crc32 crc32b fnv132 fnv164 joaat haval128,3 haval160,3 haval192,3 haval224,3 haval256,3 haval128,4 haval160,4 haval192,4 haval224,4 haval256,4 haval128,5 haval160,5 haval192,5 haval224,5 haval256,5 

I heard that in V3 there were similair problems with passwords, caused by 3rd party modules or when some modules are not activated. To check this, I have activated debug mode, but all I get is this:

Fatal error: Uncaught exception 'Whoops\Exception\ErrorException' with message 'preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead' in /var/www/vhosts/mydomain.com/httpdocs/PF.Base/include/library/phpfox/parse/bbcode.class.php:220 Stack trace: #0 [internal function]: Whoops\Run->handleError(8192, 'preg_replace():...', '/var/www/vhosts...', 220, Array) #1 /var/www/vhosts/mydomain.com/httpdocs/PF.Base/include/library/phpfox/parse/bbcode.class.php(220): preg_replace('/\[b\]/ise', '''.$this->_repl...', ' Say something ...') #2 /var/www/vhosts/mydomain.com/httpdocs/PF.Base/include/library/phpfox/parse/output.class.php(123): Phpfox_Parse_Bbcode->parse(' Say something ...') #3 /var/www/vhosts/mydomain.com/httpdocs/PF.Base/include/library/phpfox/parse/output.class.php(361): Phpfox_Parse_Output->parse('Say something a...') #4 /var/www/vhosts/mydomain.com/httpdocs/PF.Base/file/cache/template/block_feed.block.content.php(48): Phpfox_Parse_Output->feedStrip('Say something a...') #5 /var/www/vhosts/b in /var/www/vhosts/mydomain.com/httpdocs/PF.Src/Core/View/Functions.php on line 132

This doesn't help me to find the problem.

**Comment by qsrs** [comment] 2015-08-07 08:17
I have tested something. When I sign up, the passwords are stored with $2y$10$ in the database table, which should not be. After I have requested for a new password and changed it to the same password chosen when signing up, the password will be stored without $2y$10$ and the login works.

**Comment by Data66PF** [comment] 2015-08-07 08:43
My passwords are like that and they work fine.

**Comment by qsrs** [comment] 2015-08-07 09:16
That's really strange. I have no idea anymore how to solve this. Is the debug output helpful to you?

**Comment by Data66PF** [comment] 2015-08-07 10:15
Are you sure you are using v4.0.5 and that you followed the steps for upgrading, including the final steps here, http://scripttechs.com/article/354/phpfox-v4-upgrade-final-steps-you-need-to-do/

Yes, I'm sure the debug info will be good for him to see. Make sure debug is disabled for the site to test logging in. Make sure you do not have the old debug method enabled when you do decide to debug. remove the include/setting/dev.sett.php file if you had one on there. Use the new debug method (but not for logging in as I added a bug I found for that) . New debug is here but at your own site yoursite.com/PF.Base/tools/debug.php

**Comment by qsrs** [comment] 2015-08-07 14:00
Yes I am sure about using 4.0.5. and I have followed all the final steps from your link already after updating to 4.0.3. Also I know how to use debug, but I get the result posted above.

**Comment by qsrs** [comment] 2015-08-07 14:10
Now, I have just enabled debug again, and no website will show any debug results - just nothing. PHP display_errors is on. No dev.sett.php there. Using yoursite.com/PF.Base/tools/debug.php - it shows enabled, but on websites are no debug results.

**Comment by Data66PF** [comment] 2015-08-07 14:42
perhaps your server is not up to the requirements?

**Comment by qsrs** [comment] 2015-08-07 15:12
It does, I have checked this before updating.

**Comment by Data66PF** [comment] 2015-08-25 18:27
Is this still an issue? I see it posted in the PF community in another thread

**Comment by Ylmzef** [comment] 2015-08-26 01:52
Yes i tested several times but i can't find cause of the problem.
Default theme
Chrome 44
Windows  10
Admincp -> Settings -> User Settings:
![download 1](https://cloud.githubusercontent.com/assets/8562514/9483901/75b517b8-4ba5-11e5-839d-f0fc0d1c0464.png)

Admincp -> Settings -> User Registration:
![download 2](https://cloud.githubusercontent.com/assets/8562514/9483936/d9d2a21a-4ba5-11e5-83cb-9f90af83bb3e.png)

**Comment by one44** [comment] 2015-08-26 11:41
Same issue on my site have reported it here as well.

**Comment by qsrs** [comment] 2015-08-26 11:48
The same here. My site is dead since updating to V4 due to the registration problem

**Comment by Ylmzef** [comment] 2015-08-26 20:58
if there is another person with this problem, please report here!

**Comment by one44** [comment] 2015-08-27 07:45
Place a link and request in phpfox forum to this page.

**Comment by Data66PF** [comment] 2015-08-27 11:55
It is already in a thread as that's why I was checking this bug. I'll try to reproduce it some more with an upgraded site.

**Comment by Ylmzef** [comment] 2015-08-27 21:05
It's fixed asap and need to relased patch for this.
I lost my all new members..

**Comment by Ylmzef** [comment] 2015-09-07 01:09
I'm still wating for this, im lossing traffic every time for this issue.

**Comment by qsrs** [comment] 2015-09-07 07:55
Same here, it's more than 5 weeks now that no one can sign up to my website anymore. I would appreciate a solution asap.

**Comment by one44** [comment] 2015-09-07 08:31
I too have this issue and it is frustrating on a live site. Members must request a password reset to get in and this causes many new members to just give up in disgust.

**Comment by Data66PF** [comment] 2015-09-07 09:43
Do you all have the verify email on? If you disable it, does it fix the issue? Note that verify email really doesn't work to deter spammers any more. Try the free v4 recaptcha app and see if that works better as I use google's recapcha on my v3 sites (updated version of  recaptcha provided free by a member of my site)

**Comment by Data66PF** [comment] 2015-09-07 09:44
Marked a bug though I can't reproduce it. Waiting to see if all of these clients have verify email on and if they disable it, if that resolves the issue. If so, it must be an issue with upgraded sites and verify email.

**Comment by Ylmzef** [comment] 2015-09-07 09:52
I tryed all things it's not due to settings.
Also we need correct mail's for user notification etc. not only for spammers..

**Comment by qsrs** [comment] 2015-09-07 10:15
I have disabled email verification, to see if it works. It doesn't, it's the same issue. After the registration, the user can't login. No matter if email verification is set to on or off.

**Comment by Ylmzef** [comment] 2015-09-07 10:17
I said. It's due to coding i think.

**Comment by one44** [comment] 2015-09-07 10:28
I too have disabled e mail verification still same issue

**Comment by one44** [comment] 2015-09-07 10:30
I do not have verify e mail This needs an urgent fix as money is being spent promoting sites and new members have a problem from the get go.

**Comment by Data66PF** [comment] 2015-09-07 11:01
I'm going to have to unsubscribe from this as I'm getting too many emails after already confirming it is a bug. Thanks for testing and providing feedback. I'm sure he will fix it once he can reproduce it. He might ask for details so he can some see it on one site but please wait for his response as he might not need a ticket created for that.

**Comment by RaymondBenc** [comment] 2015-09-07 18:59
For those having this issue, please open a sales ticket and reference the ID # here. I will then give it a look on your sites as I cannot reproduce it locally.

Thank you

**Comment by one44** [comment] 2015-09-08 03:29
A sales ticket where or is it a support ticket

**Comment by qsrs** [comment] 2015-09-08 07:25
I have contacted the support on phpfox.com with this issue about 6 weeks ago, and I received the answer, that I had to pay for support, even I think that this is a bug. I could not find any ticket system there either. Where should we open a ticket?

**Comment by one44** [comment] 2015-09-08 08:36
As there area few of us with upgraded live sites I think the solution should be published or a patch issued to fix this.

**Comment by Ylmzef** [comment] 2015-09-08 12:10
Ticket ID: 1955

**Comment by qsrs** [comment] 2015-09-08 12:17
Where did you open the ticket? Can you post a link to the ticket system?

**Comment by Ylmzef** [comment] 2015-09-08 12:23
Mail to hello@phpfox.com

**Comment by qsrs** [comment] 2015-09-08 12:26
Thank you

**Comment by whookka** [comment] 2015-09-09 04:56
I have the same issue with the registration process and it's time for a fix! I was under the impression it was being addressed in 4.06 & 4.07 so I waited to test. My test....On a separate device I created three users, each with a simple 3 character passwords. Each time registration failed (or so I thought)...after checking the admin panel, my three users were in fact created, however the entered passwords showed as invalid.

After requesting password resets for all three users, sign in was established.  So judging by the number of phpfox clients that have this issue, I would request a quick fix, since the goal of most is to monetize the site and new members equal money...the issue now effects the livelihoods of phpfox' customers.

**Comment by one44** [comment] 2015-09-09 11:07
Any movement on this issue it is a critical problem on live sites upgraded

**Comment by qsrs** [comment] 2015-09-09 12:26
I have contacted the sales support to open a ticket as suggested from Raymond, but no answer. I have this issue now since more than 6 weeks and my side is dead now.

**Comment by RaymondBenc** [comment] 2015-09-10 09:55
@Ylmzef Could you update your FTP details? I am personally looking into both those issues and should find a resolve to them today.

**Comment by Ylmzef** [comment] 2015-09-10 09:59
I updated the ticket.

**Comment by one44** [comment] 2015-09-10 09:59
Thanks Raymond for update nice to see movement on this issue.

**Comment by qsrs** [comment] 2015-09-10 12:58
@RaymondBenc: Will there be a fix for the other customers in a release? Or do you need to fix this by hand? Because I have written to the support, and so far I haven't received any ticket number.

**Comment by one44** [comment] 2015-09-11 03:08
Has there been a fix for this have a ticket but still no feedback

**Comment by Ylmzef** [comment] 2015-09-11 12:01
Me too: Ticket ID: 1955

**Comment by one44** [comment] 2015-09-11 12:06
You did update your ticket as requested so customer service says you should be updated om progress.

**Comment by qsrs** [comment] 2015-09-11 13:43
I even did not get ANY reply to my mail - no ticket nothing. Guys, what is this?

**Comment by one44** [comment] 2015-09-11 14:10
Live sites after upgrade are useless with this problem as new members just leave after having hassles to log in.

**Comment by qsrs** [comment] 2015-09-11 14:20
New members leave and existing members are falling like dominos and leaving as well. I have to persist for a quick fix for this. The thing is that we even do not get any feedback here.

**Comment by Ylmzef** [comment] 2015-09-12 10:33
It's weekend..

**Comment by one44** [comment] 2015-09-12 11:10
It may be weekend but this has been a long standing issue and is of such critical importance it should be given priority and clients given at least a daily report so that we know there is activity.

**Comment by Ylmzef** [comment] 2015-09-14 15:58
It's not fixed today too..

**Comment by belleman** [comment] 2015-09-16 01:05
I have the same issue

**Comment by belleman** [comment] 2015-09-16 12:04
I updated to latest version yesterday. I tested registration and when form is completed, members try to login and gives invalid password.. Is this similar to everyone else

**Comment by qsrs** [comment] 2015-09-16 13:24
Yes, it is the same issue

**Comment by Ylmzef** [comment] 2015-09-17 20:20
This week is over too but it's still not fixed..

**Comment by one44** [comment] 2015-09-18 04:07
A patch needs to be released urgently before the next official release.

**Comment by Ylmzef** [comment] 2015-09-18 12:21
https://github.com/moxi9/phpfox updated 8 days ago. Please little bit interest, there lot of people paying for this service.

**Comment by whookka** [comment] 2015-09-18 23:30
If the link on Github was a fix...it didn't work.  Now, it has been over 60 days since the upgrade and still no response to what should be the most important issue of a social network (signing on new members) I think we have all been patient enough, it's time for action. Like many others, my network has stopped growing, I busted my ass to get on page one of google and now that I've accomplished that new members can not sign up!       I ask PHPFOX, if the roles were reversed...how would you react?

**Comment by belleman** [comment] 2015-09-22 12:14
Can we get any kind of update on this. How many people are having this issue?

**Comment by RaymondBenc** [comment] 2015-09-22 16:14
I was able to finally reproduce this issue on a clients site. We are pushing an update later today and we we are working on a fix for this specific issue to be part of that release.

**Comment by RaymondBenc** [comment] 2015-09-22 16:19
We were able to find the issue. The DB column for passwords is set to 32, it should be at 150. Our update routine for RC1 shows that it updates this column. For those having this problem, can you confirm how the upgrade for your site was done?

**Comment by RaymondBenc** [comment] 2015-09-22 16:33
In any case, the next update will make sure the DB column is set to 150 characters. I've ran a final test on a clients site and was able to login after the column was changed.

**Closed** 2015-09-22 16:32 UTC
Labels: bug, cannot reproduce, Critical

**Comment by Ylmzef** [comment] 2015-09-22 16:44
And what about old users? can they login with old password?

**Comment by belleman** [comment] 2015-09-22 17:06
@RaymondBenc http://support.phpfox.com/upgrading-phpfox/manually-upload-files/ I followed the steps here. I will check my db column and see what that is set to. Thanks for the repy

**Comment by one44** [comment] 2015-09-22 17:56
was set to 32 changed to 150 but still seems to have same issue

**Comment by RaymondBenc** [comment] 2015-09-22 17:56
Old users from v3? or just those that signed up after v4 was installed?

**Comment by one44** [comment] 2015-09-22 18:04
I can still log in so old users seem ok But when I try to register an new user have problem.

**Comment by one44** [comment] 2015-09-22 18:06
PS it worked with first upgrade after 3.8 but broke with one of the other upgrades

**Comment by qsrs** [comment] 2015-09-22 18:35
I have changed columns to 150 manually and it works now. Thanks Raymond.

**Comment by one44** [comment] 2015-09-22 18:55
ok fixed changed correct password field

**Comment by Ylmzef** [comment] 2015-09-22 23:47
@RaymondBenc users before this fix..

**Comment by whookka** [comment] 2015-09-25 21:47
(I up graded from V.3 months ago)  just upgraded to 4.0.8 but still have the same problem (could some one point me to the proper password filed I need to change)
Thanks Very Much!!!

**Comment by one44** [comment] 2015-09-25 23:03
Go to DB and under user change password from 32 to 150 characters.

**Comment by SpeakLife** [comment] 2016-02-04 02:21
What is the exact code table name in the database to change the password length from 32 to 150? I'm experiencing this issue and didn't even noticed it. I went from version 4.0.9 to 4.2.1 I can register accounts but when they try to log in they receive the error that their password is invalid.
