### ISSUE TITLE
Commented on the page notification.

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#465] opened 2015-09-02 20:41 UTC
I got a notification from my site about commented on the page notification.
When i click on it i see Wall Comment: #5 and commented user with comment. (
sitename.com/PAGESNAME/wall/comment-id_5/)
But when i surf to commanted page (
sitename.com/PAGESNAME/) I dont see the comment.

**Comment by Data66PF** [comment] 2015-09-04 14:40
How are you getting notifications that someone commented on a page? I know there was a third party plugin for that before but not for default script. Are you using that plugin to have notifications for comments on a page? If so, please disable it and contact that developer to get a new solution.

**Comment by Data66PF** [comment] 2015-09-04 14:45
Ok I see what you mean. It is not the PM notifications I was thinking of. I was thinking it was something else. Will test this further tomorrow after I update this dev site with latest code from here as I am getting errors on pages/groups when I make a status post as confirmed in another bug report.

**Comment by Ylmzef** [comment] 2015-09-04 20:49
I posted self any text on page wall but it's not showing.
It's upgraded site 4.0.7 with default theme.

**Comment by Data66PF** [comment] 2015-09-07 15:09
Ok this bug is related to the bug I linked as there is an error with pages. I'll close this as a duplicate as a fix for that will fix this issue.

**Closed by Data66PF** 2015-09-07 15:09 UTC

**Comment by Ylmzef** [comment] 2015-09-08 12:14
It's not same.
I post on page but it's not showing also it's upgraded site.

**Comment by Data66PF** [comment] 2015-09-08 15:02
The reason is it not showing is due to that bug posted in the comment at the one I linked. Once that is fixed, it will allow the post to show up. I even have the same issue due to that.

**Comment by Ylmzef** [comment] 2015-09-26 02:16
This still issue when i post something to page feed after clicked share button i see nothing on feed.
Upgraded site
v4.0.8
Chrome 45
Windows 10
