### ISSUE TITLE
Not found image issue with buttons on v3 upgraded sites

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#756] opened 2015-11-28 11:10 UTC
![d35a011da50be780978daa749d8bdff5](https://cloud.githubusercontent.com/assets/8562514/11451513/0edea626-95c9-11e5-955d-9de1f24b8a77.png)

**Comment by Data66PF** [comment] 2015-11-28 12:20
Did you sync css and follow the other steps regarding final upgrade steps that I have a tutorial for at ScriptTechs? Do you have the same issue with unedited default Neutron theme?

**Comment by Ylmzef** [comment] 2015-11-28 22:54
I did it also updated counters and cleared cache.
And yes same issue with default theme.

**Comment by Ylmzef** [comment] 2015-11-28 22:55
Also please check community: http://community.phpfox.com/forum/thread/53294/problem-after-update-4-1-0/

**Comment by Data66PF** [comment] 2015-11-28 23:36
I did see that thread and another client also cannot reproduce the issue. The theme shown has different coloring than default. Since the default theme needs to be reverted, sync css, clear cache, etc. the view should show default unedited Neutron theme.

**Comment by Ylmzef** [comment] 2015-11-28 23:45
Maybe other client dont have upgraded site?

**Comment by Data66PF** [comment] 2015-11-29 11:22
The other client does. I also have upgraded test sites. You need to check default theme that has NO edits. You need to always revert theme, sync css, find missing settings, find missing phrases, clear cache when upgrading.

**Comment by wlongdonstudio** [comment] 2015-11-29 21:37
solution?

**Comment by Data66PF** [comment] 2015-11-29 22:13
Our techs will need to test it on our other testing sites and see if they can reproduce it. They will mark it a bug if they can reproduce it and fix it if it's a bug.

**Comment by Data66PF** [comment] 2015-11-30 00:15
Though I am not getting any "not found" showing, I am seeing that the images are missing for Neutron theme but are showing up for Bootstrap.

With neutron we see in developer browser console the path:
NetworkError: 404 Not Found - http://localhost/41b3/PF.Base/theme/frontend/default/style/default/image/layout/privacy_setting_active.png

However, that folder is empty and it is empty in the downloaded files.  Looking back at 4.0.9, that folder has files in it.

**Comment by wlongdonstudio** [comment] 2015-12-03 12:20
good morning..what's the status?

**Comment by Data66PF** [comment] 2015-12-03 15:46
Please wait for techs to test and mark fixed. They do post when that is done. Thanks.

**Comment by Data66PF** [comment] 2015-12-04 12:04
Fixed in v4.1.1 *staff note YPFOXNEUTRON-253 *

**Closed** 2015-12-04 12:15 UTC
Labels: Bug, Fixed
