### ISSUE TITLE
Community | Aphostrophes and more are shown as HTML entities in page title

### ISSUE THREAD

**Issue by optiroot** [moxi9/phpfox#831] opened 2015-12-14 19:13 UTC
In the PHPfox community if you open a forum thread with an ' in the title or letters like "è" and so on, in the page title (Browser tab) shows the HTML entity code.

![image](https://cloud.githubusercontent.com/assets/12573563/11791006/207f391c-a29f-11e5-895e-553db46378d4.png)

As shown, and the link for this discussion is:
http://community.phpfox.com/forum/thread/53535/can-039-t-login-getting-urgent-solved/

The problem is not present in my community, instead; using PHPfox v4.1.1 and Bootstrap theme.

**Comment by Data66PF** [comment] 2015-12-15 09:33
This is how it's always been though. I'll leave this open and assign it to Ray to see but I don't think it's a bug.

**Comment by Data66PF** [comment] 2016-01-05 15:17
@neil96 is this working as designed?

**Comment by neil96** [comment] 2016-01-05 15:43
I can't reproduce this issue, so I can't answer it is a bug or working as designed.
@optiroot Could you give me more detail how to reproduce? Thanks!

**Comment by Data66PF** [comment] 2016-01-06 10:35
https://community.phpfox.com/forum/thread/53717/can-039-t-get-to-edit-all-the-event-address/ please go there and check the browser tab. It will show there and you can see it has code in the link as well.

**Comment by neil96** [comment] 2016-01-06 10:37
![screen shot 2016-01-06 at 17 36 47](https://cloud.githubusercontent.com/assets/15936115/12140634/1f4e8188-b49c-11e5-89e8-f982563430ff.png)

It's working on my side.

**Comment by Data66PF** [comment] 2016-01-06 15:21
Please log in to the community. Then, click a link that is in the list of feeds or in the recent posts that shows a title with an apostrophe as that seems to be the only way to reproduce it is to click the actual title of the thread. https://community.phpfox.com/forum/114/neutron-v4/ and then click the one with "can't" in the title.

**Comment by neil96** [comment] 2016-01-07 10:13
Fixed on V4.2.0

**Closed** 2016-01-14 02:31 UTC
Labels: Bug, Fixed
