### ISSUE TITLE
All items are gone after upgrade to 4.4.3

### ISSUE THREAD

**Issue by lordofnos** [moxi9/phpfox#1681] opened 2016-09-30 13:08 UTC
After the Upgrade my users can not see items like events, photos, pages, quizzes and polls. When changing the setting "Can view private items posted on the site. " to yes all items are back again. I need this fixed asap. never had this issue before and the update on dev site (same server and apps) does work.

**Comment by kaligula7** [comment] 2016-09-30 13:32
See option Friends Only community...

**Comment by lordofnos** [comment] 2016-09-30 13:34
it is not set to friends only

**Comment by lordofnos** [comment] 2016-09-30 13:42
when exchanging the module folder with the one from 4.4.2 it works again but i dont have find out wich single module causes that. maybe a combination of changed files.

**Comment by lordofnos** [comment] 2016-09-30 13:48
its the privacy module. when using the 4.4.2 files of this the items are back. can i use the old version to solve this temporary or does it cause other issues?

**Comment by Data66PF** [comment] 2016-09-30 20:00
The change was to fix it so admin could see all items on the site regardless of privacy so the admin can manage the site. Will you please double check that the registered users are the ones able to see everything for this bug? The admin is supposed to see everything in order to properly manage the site (just like in v3). However, registered and other user groups should not see private stuff, but should see non-private stuff on an open (non friends only) community, unless that setting is at true for them.

**Comment by lordofnos** [comment] 2016-10-01 04:58
i have double checked it before posting on github. i also know how this setting works and how to use it. the value was never changed since installing the first release of my v4 site. the thing is that downgrading this module solves the issue. in the list of modified files on the blog there are no changes from 4.4.2 to 4.4.3 on this module. if there was an error while uploading (but i am pretty sure there was none) nevertheless the files should be the same. what else could i check? btw on my second site (same server and settings) the new version works fine. i have also disabled all third party apps while trying to bring the items back.

**Comment by lordofnos** [comment] 2016-10-01 05:18
i dont know why but now the issue is gone when changing the module to 4.4.3 again. after upgrade cache was cleared and all upgrade steps were done. i have compared alle files of the module and they all match with 4.4.2 so it would be strange if this causes the issue. can not reproduce it for now... i am using phpfox since 2011 and never had an issue like this before ;) no idea what was going on.

**Comment by Data66PF** [comment] 2016-10-01 09:40
As you can't reproduce it, we will close this

**Closed** 2016-10-01 09:39 UTC
