### ISSUE TITLE
Site wide ajax not working exactly

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#339] opened 2015-08-12 15:06 UTC
I enable site wide ajax browsing but when i use search function its refreshing page.

**Comment by Data66PF** [comment] 2015-08-12 19:05
Do not enable sitewide ajax. It is not in the list of settings for V4.Where did you see it in v4.0.5?

**Comment by Ylmzef** [comment] 2015-08-13 01:32
Phpfox v4comming  already sitewide ajax.
You can open chat window and surf other page its stay in page.

**Comment by Data66PF** [comment] 2015-08-13 09:18
Yes so you don't need to enable the setting.

**Comment by Data66PF** [comment] 2015-08-13 09:42
I'll confirm this just so the setting cannot be accessed as that setting to enable sitewide ajax is not used.

**Comment by RaymondBenc** [comment] 2015-08-17 15:46
Can **site wide ajax** browsing be enabled in 4.0.5?

**Comment by Ylmzef** [comment] 2015-08-17 16:12
Its already comming with ajax browsing i mean that.

**Comment by muhammadnaeemahsan** [comment] 2015-08-29 05:23
how to enable and disable ajax browsing

**Comment by RaymondBenc** [comment] 2015-10-05 14:54
@Ylmzef Can this issue still be reproduced on our community?

**Comment by Data66PF** [comment] 2015-10-05 15:27
I think this is a duplicate of the search bug maybe. I'll go mark that bug a bug as it has more description in it.

**Comment by Data66PF** [comment] 2015-10-05 15:29
https://github.com/moxi9/phpfox/issues/586

**Comment by Ylmzef** [comment] 2015-10-05 18:47
I can still reproduced this on pf community.
And this is not same as @Data66PF mentioned issue.

**Comment by Ylmzef** [comment] 2015-12-21 05:25
When do you want fix this?

**Comment by neil96** [comment] 2015-12-21 07:11
![screen shot 2015-12-21 at 14 04 45](https://cloud.githubusercontent.com/assets/15936115/11925289/a44b91b2-a7ec-11e5-943d-ffbdf43dfd21.png)
Did you mean this search?

**Comment by Ylmzef** [comment] 2015-12-21 20:29
I mean all search forms on phpfox.

**Comment by Data66PF** [comment] 2015-12-23 11:43
I'm not sure how to reproduce this as search requires hitting enter to work in my bootstrap tests. This then produces results in a "new page". I don't see any bugs with it in my tests.

**Comment by Ylmzef** [comment] 2015-12-23 11:46
@Data66PF You need to open a chat window first than search something on the site than you can see that the chat window disappears on the page. So it's reloading the page it's not working as ajax.

**Comment by Data66PF** [comment] 2015-12-23 13:25
I don't have chat on the site. We only test with default modules. We cannot test with third party products.

**Comment by Ylmzef** [comment] 2015-12-23 15:10
Chat (Messages) is not third party product.

**Comment by Data66PF** [comment] 2015-12-23 15:46
Chat is. Pm is not. Do you mean PM as that is different from Chat. There is no Chat in the default phpFox v4 script.

**Comment by Ylmzef** [comment] 2015-12-24 02:56
Yes.

**Comment by Data66PF** [comment] 2015-12-29 09:43
A core developer has determined that this is working as designed. Once we are done with bugs, we'll take a look at the search process to see if it can be improved if you'll post this in the feature requests at the community.

**Closed by Data66PF** 2015-12-29 09:43 UTC
Labels: Working as Designed
