### ISSUE TITLE
New Custom Fields Have Different Styling

### ISSUE THREAD

**Issue by SpaniNet** [moxi9/phpfox#921] opened 2016-01-07 21:32 UTC
All new Custom Fields created have different styling than the Default "About Me" field and neither appears the button to edit the field.

#### Screenshot:

![Custom Field vs Default "About Me" Field](https://community.phpfox.com/file/attachment/2016/01/d2dda329e83d8d62b54dc4f34046c659_view.png)

**Comment by Data66PF** [comment] 2016-01-07 23:20
It depends on where you add the field. Did  you ad it to basic section or main? Added to basic info and they need to click Edit Profile to edit those as they are in a different area than the main and have always looked different. This is as designed but it could look better, true. However, that would be an enhancement and not a bug.

**Comment by SpaniNet** [comment] 2016-01-08 00:19
I have tested it in the two sections and looks the same.

**Comment by Data66PF** [comment] 2016-01-08 11:46
They have slight differences to make them stand out from each other. The header, as you noted, is different and the edit is at a different location (edit profile) as it has always been in v3 as well. However, we could improve how they look so I left this as an enhancement.

**Comment by SpaniNet** [comment] 2016-01-08 16:17
OK.

But the Custom Fields in both sections can be edited in same place (Edit Profile).

**Comment by Data66PF** [comment] 2016-01-09 09:22
Yes I know but one has a fast edit and the other doesn't. We really should move the Basic info to the Info tab. Will mark this a bug enhancement and see what we can do for this.

**Comment by robert9592** [comment] 2016-01-12 10:20
Fixed in v4.2.0

**Closed** 2016-01-14 02:12 UTC
Labels: Bug, Enhancement, Fixed
