### ISSUE TITLE
Visiter menu

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#496] opened 2015-09-10 13:25 UTC
No setting to allow visitors to see menu on landing page. Only shows if failed registration, You must click to enter site then only it shows. Also click home takes you to sign in page not feed. Same on community site.

**Comment by Data66PF** [comment] 2015-09-10 16:37
Will address only the issue of the menu in this as the Home tab is as designed, to see core.index-visitor for non logged in users.

**Comment by one44** [comment] 2015-09-10 16:41
how will visitors see the main feed ????

**Comment by Data66PF** [comment] 2015-09-10 16:47
They don't see it now in v3 by default either, unless you set the guest group to be able to see feeds anyplace on the site, in user group settings.

**Comment by Data66PF** [comment] 2015-09-10 16:50
Ok this was addressed in bug #242 as the setting to show menu to guest is removed and no longer used.

**Closed by Data66PF** 2015-09-10 16:50 UTC

**Comment by Data66PF** [comment] 2015-09-10 17:04
I'm not sure this will help you but if you need to edit the html of the visitor page, here is a tutorial for how to get to it if you want to use the admincp editor http://scripttechs.com/article/366/how-to-see-the-visitor-page-in-phpfox-v4-while-logged-in/  since the edit button only shows when logged in. I'm still trying to figure out a good work around though as making a footer menu doesn't show either. not without an edit anyway.
