### ISSUE TITLE
RE: Users profile photo album issue #688

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#1044] opened 2016-01-30 14:52 UTC
This again issue in v4.2

https://github.com/moxi9/phpfox/issues/688
If users havent any photos except created album photos, photos tab not showing under profile.
Example: users have only profile photos under "Profile Pictures" album than the photos tab not showing in profile menu. Also there no albums for cover photos and timeline photos.

**Comment by Data66PF** [comment] 2016-02-01 13:32
we've never had an album for cover photos or status share photos. that would be a feature request.

**Comment by Ylmzef** [comment] 2016-02-01 15:29
It's not about cover or timeline photos,
It's about profile photos album.
It was fixed from older version but i see it's again a issue.

**Comment by Data66PF** [comment] 2016-02-01 22:27
Next time in the description, please post exact steps to reproduce a bug instead of just linking an old bug as we will assume that the entire old bug is again showing up for you. Thank you.

**Comment by Data66PF** [comment] 2016-03-08 13:55
I'm able to confirm on our staging https://stage.phpfox.com/profile-1522/ that a profile with no profile photo loaded will show no Photo count in the drop down. Since it shows Video and Activity Points at 0 in the drop down, this seems a bug as it should show nothing in the drop down or it should show everything in the drop down. Meaning, if the user has 0 content added to the site, either everything should show up and as 0, or nothing should show up (blogs, photos, videos, listings, etc) in the count there.

**Comment by robert9592** [comment] 2016-03-09 09:03
@Ylmzef , from phpFox v4.2.0 we bring the photo setting "Display Profile Photo within Gallery" back. If enable this setting, the profile photo and profile album will be display in profile photo tab and photo module. So, please check this setting on your site, it might be disabled.

**Comment by robert9592** [comment] 2016-03-09 09:11
Fixed in v4.3.0

**Closed** 2016-03-09 09:56 UTC
Labels: Bug, Fixed
