### ISSUE TITLE
Secure Pages with Https NOT working

### ISSUE THREAD

**Issue by bamafanz** [moxi9/phpfox#1392] opened 2016-04-30 16:44 UTC
Hello, 

Is there a way to customize the SSL where you can have only certain pages encrypted?

We were wanting to just encrypt  example:  Login- Sign Up,  Account / privacy , profile settings.

It seems, it currently want let us pick specific pages to encrypt.

This in turn , has really slowed down our site as every page is secured.

Was wondering if this might be a bug?

Thanks for your help and suggestions..

**Comment by Data66PF** [comment] 2016-04-30 17:10
There are two SSL settings. One just sets the site login, signup, account/privacy and profile settings to SSL. The other sets the entire site to SSL and requires the first setting mentioned to be set in order to work.

Are you saying that the setting 1 is not working? 

If you are saying setting 1 is not working, please post details about the server such as:

is it nginx?
are you using cloudflare ssl?

**Comment by bamafanz** [comment] 2016-04-30 17:43
Will check on a few things and check back in .Thanks Donna for your help.

**Comment by bamafanz** [comment] 2016-04-30 18:48
(Donna) Are you saying that the setting 1 is not working?
 ( yes  - setting 1 is not working) Secure Certain pages only not functioning..

(Donna) Is it nginx?    (It is nginx as proxy) - apache as backend..

(Donna)  Are you using cloudflare ssl?     No.

**Comment by Data66PF** [comment] 2016-05-10 14:53
How is this marked not a bug? The title was written a little wrong but we need this checked. The issue is that you can't set the secure site settings. One way works and the other doesn't. Reopened for an explanation for the client.

Client wants to ONLY set the Secure Pages setting and not the second one, Force Secure for entire site.

**Comment by Data66PF** [comment] 2016-05-10 14:54
@RaymondBenc please check this issue. Or someone please address the client as to why that setting doesn't work properly. You must test it with only the first setting that secures just the login, signup, account privacy as the clients do not want the full site https (which would be the second setting)

**Comment by Data66PF** [comment] 2016-05-10 14:59
Setting is this one core.force_https_secure_pages
admincp/setting/edit/?group-id=server_settings
If your server has support for HTTPS you can enable this feature to secure certain pages like the login, registration and account setting pages.

note that the client only wants that setting for the login, registration and account to be https as the setting says and as it used to work previously.

It is NOT for this setting : core.force_secure_site
Enable to make all connections secure when a user is logged in. Notice: Your server must have HTTPS support.

Client does not want the entire site HTTPS. He wants our first setting to work properly.

**Comment by RaymondBenc** [comment] 2016-05-12 03:47
Fixed in 4.4.0.

**Closed** 2016-06-27 09:26 UTC
Labels: Bug, Fixed
