### ISSUE TITLE
Installed apps & themes update

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#330] opened 2015-08-11 16:45 UTC
There no way to update apps and themes.

**Comment by Ylmzef** [comment] 2015-08-11 16:53
I found cause of the problem.
Setting_admin_cp is enabled in settings site.com/admincp15487 for me.

**Comment by Data66PF** [comment] 2015-09-08 10:38
What do you mean?

**Comment by Ylmzef** [comment] 2015-09-08 12:04
When i change admincp url than can't uninstall any apps.
But so it was 28 days ago, i do not know what the situation is currently..

**Comment by Data66PF** [comment] 2015-09-10 12:22
Ok if you can reproduce it, please post the issue again. Will close for now.

**Comment by Ylmzef** [comment] 2015-09-10 12:23
It's not fixed yet.

**Comment by Ylmzef** [comment] 2015-09-26 01:51
It's still issue on v4.0.8
My admincp url is site.com/differentadmin
Try to change your admincp url!

**Comment by Data66PF** [comment] 2015-09-30 10:30
The setting to change admincp location, I can't find it in Settings. It looks to be removed.

**Comment by Ylmzef** [comment] 2015-09-30 12:10
Its upgraded site.

**Comment by Data66PF** [comment] 2015-09-30 15:19
Alright. I'm sure that setting is disabled in v4 since it's not in the fresh install settings. Will test on an upgraded site.

**Comment by Data66PF** [comment] 2015-10-06 10:17
I have upgraded another v3.8 site. This one I had changed the Manage settings >> AdminCP and set the location to myadmin. I then upgraded.

In firefox I have no issue installing or "upgrading" apps. In chrome it won't work.
In dev console I see:
Uncaught SecurityError: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
https://da1a3suzxtd3z.cloudfront.net/2.4.8/unity.js
line 558

**Comment by Data66PF** [comment] 2015-10-07 12:18
I'm now getting this issue on the live site if using Chrome browser when I try to install apps too.

**Comment by Ylmzef** [comment] 2015-11-16 19:28
Why you don't fix crittical bugs first?
It's need fixed asap i think..

**Comment by Ylmzef** [comment] 2015-12-21 05:25
When do you want fix this?

**Comment by neil96** [comment] 2016-01-05 16:00
Fixed on V4.2.0

**Closed** 2016-01-14 11:10 UTC
Labels: Bug, Critical, Fixed
