### ISSUE TITLE
Bootstrap Theme :Event Details not displaying properly on mobile

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#936] opened 2016-01-12 03:46 UTC
tested with latest phpfox (Bootstrap Theme) using iphone 6 and chrome.

![image](https://cloud.githubusercontent.com/assets/406030/12254324/6d04b150-b8e7-11e5-9a8f-4af1f54c0c7a.png)

**Comment by neil96** [comment] 2016-01-27 16:04
I can't reproduce on V4.2.0RC. Please test again on 4.2 and tell us if you still reproduce it.

**Comment by neil96** [comment] 2016-01-30 17:06
Could you test this issue again on V4.2stable.

**Comment by aakash83** [comment] 2016-01-30 17:50
the previous  issues are fixed  . but when see how it looks when  the location field have a long address.

![image](https://cloud.githubusercontent.com/assets/406030/12697388/1d5d108a-c782-11e5-9f05-78b13f86951a.png)

**Comment by robert9592** [comment] 2016-03-07 10:26
Fixed in v4.3.0

**Closed** 2016-03-07 10:55 UTC
Labels: Bug, Fixed
