### ISSUE TITLE
Bootsrap theme . cannot select forum threads and replies

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#851] opened 2015-12-19 05:57 UTC
we do have select and unselect buttons on a View thread page but  we dont have nay check boxes. also select un select  thread or replies buttons are not working.
![image](https://cloud.githubusercontent.com/assets/406030/11911673/c5080596-a61d-11e5-8214-34f5349ca8a3.png)

**Comment by Data66PF** [comment] 2015-12-19 10:29
Cannot reproduce in 4.1.2 chrome on win 10 desktop view. I can select several threads. I can unselect them by clicking the Clear all and it works for me.

**Comment by neil96** [comment] 2016-01-07 02:24
Fixed on V4.2.0

**Closed** 2016-01-13 10:06 UTC
Labels: Bug, Fixed
