### ISSUE TITLE
Menu not fully visable.

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#491] opened 2015-09-09 07:17 UTC
Depending on screen size the full menu is not visible
![2015-09-09 09_08_00-inbox - edwardeap lantic net - outlook](https://cloud.githubusercontent.com/assets/13656046/9755599/8cc1e678-56d3-11e5-9fa6-cb4e3e963eab.jpg)
 and the scroll function does not work.

**Comment by Jinkers** [comment] 2015-09-09 07:23
Working fine for me on my live site (wisteria) and the community. Can you replicate this on the PF Community @one44 ?

**Comment by one44** [comment] 2015-09-09 07:31
That site looks better but the scroll function does not work there either

**Comment by one44** [comment] 2015-09-09 07:34
ok problem is with font sizes only just fits when fonts are 13 but this is small for people with poor vision 15 looks better/

**Comment by Jinkers** [comment] 2015-09-09 07:48
I don't think it is a font-issue. More a issue that its not sizing to the window properly, do you have the taskbar set to hide when not in use? I know that sometimes this stuffs with my sidebars such as something like this case.

**Comment by one44** [comment] 2015-09-09 07:59
Yes it is set to hide and it is a font size issue I had it set at 15 and it reverts to community look when set at 13

**Comment by aakash83** [comment] 2015-09-09 10:18
This is a issue with the scroll bar. which is not working. I already posted it but still not fixed. #156 . We have a same scroll bar in admin panel as well which works fine. it would be better to remove this scroll bar and attach it to main page's scroll bar so when we scroll down we can view all items in this menu. @RaymondBenc

**Comment by Data66PF** [comment] 2015-09-09 10:29
Duplicate of #156

**Closed by Data66PF** 2015-09-09 10:29 UTC

**Comment by PhpFoxJohnJr** [comment] 2015-10-30 02:26
Not sure why this is closed.  I just uploaded 4.09 and the wisteria theme and on the mobile device there is not scroll bar and it cuts off just like the image above.  I would assume it must be the theme since I check phpfox community site and it does move up and down.  Also, I just notice I do not have the pages menu either but on the phpfox community mobile version it shows the menu pages on the mobile version.

**Comment by Data66PF** [comment] 2015-10-30 08:59
@PhpFoxJohnJr it was closed for the reason I mentioned. It is a duplicate of the one I linked.

**Comment by PhpFoxJohnJr** [comment] 2015-10-30 15:55
Got it...thanks
