### ISSUE TITLE
Can't disable custom pages.

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#308] opened 2015-08-09 01:51 UTC
I can't disable custom pages in admincp.
I'm getting "The page you are looking for cannot be found." errorr.

**Comment by Data66PF** [comment] 2015-08-09 08:57
Can't reproduce in latest 4.0.5.

**Comment by Ylmzef** [comment] 2015-09-26 01:41
It can disabled now but it's showing same message after disabled.
There no information about disable/enable.

**Comment by phpfoxdev** [comment] 2015-10-08 07:32
You could reproduce by creating a page in ACP, page will not show but the message "The page you are looking for cannot be found."

**Comment by Data66PF** [comment] 2015-10-08 08:44
Please label the bugs critical, minor or major.

**Comment by Data66PF** [comment] 2015-11-13 15:15
Fixed in v4.0.10 *staff note YPFOXNEUTRON-40 *

**Closed by Data66PF** 2015-11-13 15:15 UTC
Labels: Bug

**Comment by Ylmzef** [comment] 2015-11-13 17:57
You forget to mark as fixed.
