### ISSUE TITLE
Message members or create an event not working unless i refresh page.

### ISSUE THREAD

**Issue by allterainx** [moxi9/phpfox#1644] opened 2016-08-31 12:16 UTC
I have to refresh page before I can message members or create an event

**Comment by neil96** [comment] 2016-09-01 02:04
I can't reproduce, could you give us detail steps to reproduce.

**Comment by allterainx** [comment] 2016-09-01 02:17
it happens when you enable bundled javascript and CSS settings performance 


Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: "Neil J." <notifications@github.com> Date: 8/31/16  7:04 PM  (GMT-08:00) To: moxi9/phpfox <phpfox@noreply.github.com> Cc: allterainx <slewis0073@gmail.com>, Author <author@noreply.github.com> Subject: Re: [moxi9/phpfox] Message members or create an event not working
  unless i refresh page. (#1644) 
I can't reproduce, could you give us detail steps to reproduce. 

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/moxi9/phpfox","title":"moxi9/phpfox","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/moxi9/phpfox"}},"updates":{"snippets":[{"icon":"PERSON","message":"@neil96 in #1644: I can't reproduce, could you give us detail steps to reproduce. "}],"action":{"name":"View Issue","url":"https://github.com/moxi9/phpfox/issues/1644#issuecomment-243955737"}}}

**Comment by neil96** [comment] 2016-10-05 09:03
This issue is similar with #1661 which is marked as fixed.

**Closed by neil96** 2016-10-05 09:03 UTC
Labels: Cannot reproduce
