### ISSUE TITLE
Deleting users from ACP

### ISSUE THREAD

**Issue by lupuspl** [moxi9/phpfox#69] opened 2015-07-12 11:30 UTC
When I try to delete users from ACP it doesn't work.

**Comment by RaymondBenc** [comment] 2015-07-13 12:20
I was unable to reproduce this locally. Do you get the popup to confirm if you should delete the user?

**Comment by lupuspl** [comment] 2015-07-13 12:30
No, I don't have it.
But when I selected few users, nothing happened after action delete.

2015-07-13 14:20 GMT+02:00 Raymond Benc <notifications@github.com>:

**Comment by GloriousKoch** [comment] 2015-07-14 10:47
Can confirm similar results as @lupuspl, sort of.

There are two 'versions' of the buttons depending on how far you scrolled.

This button does not work for me, even after the popup confirmation:
![image](https://cloud.githubusercontent.com/assets/6254165/8671534/eb54ad7c-29f3-11e5-8ef0-6423abd3ca0f.png)

This button, however, does work. HOWEVER, there is NO confirmation when using this one. They just end up deleted within a second. Could be kind of dangerous as it could be simple to hit this button by mistake:
![image](https://cloud.githubusercontent.com/assets/6254165/8671559/2ebd0fb4-29f4-11e5-905b-9f15518b815c.png)

**Comment by Data66PF** [comment] 2015-07-15 09:36
I've seen many clients delete their admin account by method 2 in the above post. We also need a fail-safe that the main admin cannot be deleted.

**Comment by Data66PF** [comment] 2015-07-24 13:38
closing this one and keeping it to issue #140 as it has the "help wanted" label also.

**Closed by Data66PF** 2015-07-24 13:38 UTC
