### ISSUE TITLE
Newsletter HTML Not Working

### ISSUE THREAD

**Issue by queenmother305** [moxi9/phpfox#1709] opened 2016-10-24 23:32 UTC
When you send a newsletter it shows the html code itself in the email the user recieved instead of photos or whatever else the code was supposed to display.

**Comment by neil96** [comment] 2016-10-25 01:55
It works on my test. Could you give me detail steps to reproduce.

**Comment by neil96** [comment] 2016-10-25 01:56
#1537

**Comment by queenmother305** [comment] 2016-10-25 02:02
I sent out a newsletter this evening. I upgraded to the latest version yesterday. When I checked my email to view how the newsletter looked it was displaying the html codes, not the photos the codes should have prompted. The email address I used was a gmail address.

**Comment by queenmother305** [comment] 2016-10-25 02:03
This has happened in the past as you've pointed out.

**Comment by neil96** [comment] 2016-10-25 02:05
I have tested on version 4.4.3b2. Please double check your 3rd-pary apps, themes,...

**Comment by queenmother305** [comment] 2016-10-25 02:23
I am using bootstrap default, and I have very few third party apps, none of which should be interfering with the newsletter.

**Comment by phpfoxaccount** [comment] 2016-11-07 08:23
@queenmother305 , since we could not reproduce on our testing sites and work fine on other client sites with the latest version of phpFox, it might be due to your site specific configuration. We closed this issue for now.
Please do submit ticket under Client Area if you need further check, kindly check our Support Policy - https://www.phpfox.com/terms/support/

**Closed by phpfoxaccount** 2016-11-07 08:23 UTC
Labels: Cannot reproduce
