### ISSUE TITLE
Adding questions to existing quiz, all question fields get blanked

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#785] opened 2015-12-08 21:03 UTC
4.1.1
Starting with an existing two question quiz, editing to add additional questions, the original questions get blanked in the edit dialog and the completed new questions in the dialog save until original question are re-entered.  After attempting to save and failing, all question fields went blank again. Answers retain correctly.

**Comment by Data66PF** [comment] 2015-12-08 22:28
Please include screenshots with your bugs. It helps immensely.

**Comment by Data66PF** [comment] 2015-12-08 22:42
Well I can't get a screenshot as this broke my dev site testing. Live dev site, not localhost. 

I made a quiz as the bug states, with two questions and with answers. 
I then went and answered it, answering the first question right and the second wrong so I had a 50% score.
Then I edited it to add one more question with answers. 
I then noticed that once i saved it, I could not answer the third question, nor could I view results as it kept spinning to load the results. 
Debug then showed me:
Exception (8)
Undefined index: full_name
Exception thrown with message "Undefined index: full_name"
Stacktrace:
#14 Exception in /home/scripttechs/web/mysite.com/public_html/mysite/PF.Base/start.php:182
#13 Whoops\Exception\ErrorException in /home/scripttechs/web/mysite.com/public_html/mysite/PF.Base/file/cache/template/block_quiz.block.result.php:37
#12 Whoops\Run:handleError in /home/scripttechs/web/mysite.com/public_html/mysite/PF.Base/file/cache/template/block_quiz.block.result.php:37
#11 require in /home/scripttechs/web/mysite.com/public_html/mysite/PF.Base/include/library/phpfox/template/template.class.php:2311
#10 Phpfox_Template:getBuiltFile in /home/scripttechs/web/mysite.com/public_html/mysite/PF.Base/file/cache/template/block_quiz.block.entry.php:89
#9 require in /home/scripttechs/web/mysite.com/public_html/mysite/PF.Base/include/library/phpfox/template/template.class.php:2311
#8 Phpfox_Template:getBuiltFile in /home/scripttechs/web/mysite.com/public_html/mysite/PF.Base/file/cache/template/quiz_template_default_controller_view.html.php.php:18
#7 require in /home/scripttechs/web/mysite.com/public_html/mysite/PF.Base/include/library/phpfox/template/template.class.php:3254
#6 Phpfox_Template:_requireFile in /home/scripttechs/web/mysite.com/public_html/mysite/PF.Base/include/library/phpfox/template/template.class.php:3240
#5 Phpfox_Template:_getFromCache in /home/scripttechs/web/mysite.com/public_html/mysite/PF.Base/include/library/phpfox/template/template.class.php:2529
#4 Phpfox_Template:getTemplate in /home/scripttechs/web/mysite.com/public_html/mysite/PF.Base/include/library/phpfox/module/module.class.php:589
#3 Phpfox_Module:getControllerTemplate in /home/scripttechs/web/mysite.com/public_html/mysite/PF.Src/Core/View.php:155
#2 Core\View:getContent in /home/scripttechs/web/mysite.com/public_html/mysite/PF.Base/include/library/phpfox/phpfox/phpfox.class.php:1561
#1 Phpfox:run in /home/scripttechs/web/mysite.com/public_html/mysite/PF.Base/start.php:136
#0 require in /home/scripttechs/web/mysite.com/public_html/mysite/index.php:7

**Comment by Gatsby-PF** [comment] 2015-12-09 16:42
Sorry about your dev server. This was such a simple issue to describe, the thought of attaching images never came to mind.

**Comment by Data66PF** [comment] 2015-12-09 16:59
it's ok. happens. as for simple, it depends on who's looking LOL. It took me a bit to figure out but I was pretty tired. I want to make sure our techs know what the issue is too though so images help if there are language barriers. :)

**Comment by Vivian-phpFox** [comment] 2015-12-10 07:21
Confirmed, happened in previous version (4.07; 4.0.10)

**Comment by robert9592** [comment] 2015-12-15 10:11
Fixed in v4.1.2

**Comment by Vivian-phpFox** [comment] 2015-12-21 04:28
Fixed in V4.1.2

**Closed by Vivian-phpFox** 2015-12-21 04:28 UTC
Labels: Bug, Fixed
