### ISSUE TITLE
SSL Issue

### ISSUE THREAD

**Issue by erick260** [moxi9/phpfox#1622] opened 2016-08-11 21:03 UTC
it seems that my site is having issues with ssl still. Like when you go to my sites main page, and click Login Or  Sign up, that box that pops up never loads, but when i disable the SSL 100% then it works fine. 
![social networking community](https://cloud.githubusercontent.com/assets/19263189/17604828/580fd16c-5fcc-11e6-81c0-348a02ee49d9.png)

**Comment by neil96** [comment] 2016-08-12 01:33
Are you using short-url?

**Comment by PhpFoxJohnJr** [comment] 2016-08-12 03:21
I was having the same issue.  In cloudflare (free version) in the page rule I added http://mydomain.com redirect to https://mydomain.com and then I didn't get the circle of death :)

**Comment by erick260** [comment] 2016-08-12 04:30
Yes, i do have shorten URLS enabled. I also have another screenshot for you.  It seems like If your using both SSL options you wont have this issue on your site. but if you just choose to secure some pages with SSL (witch im currently using) This issue is coming up.

**Comment by Data66PF** [comment] 2016-08-12 10:24
https://github.com/moxi9/phpfox/issues/1392 this shows fixed for 4.4.0. We might need to check that fix.

**Comment by Data66PF** [comment] 2016-08-12 10:25
https://github.com/moxi9/phpfox/issues/1497 or a duplicate of that one.

**Comment by Ylmzef** [comment] 2016-08-12 18:04
I reported this issue a lot of times before.
But no one considerabout it like as reported other issues by me.

Now I seem that many people reporting/having this issue.

I hope that you get more attention about reported issues.

Thanks,

https://community.phpfox.com/forum/thread/54977/ssl-issue/
https://github.com/moxi9/phpfox/issues/1566#issuecomment-234385635

**Comment by erick260** [comment] 2016-08-15 23:23
I've also noticed something else. IF your not using the sites SSL options, If both  options are disabled You can still pull up your site using https://yoursite.com, and everything, and all buttons will work fine. But once you enable your sites HTTPS options then the buttons dont work.

**Comment by erick260** [comment] 2016-08-15 23:28
The version im testing this on is: 4.4.1

**Comment by PhpFoxJohnJr** [comment] 2016-08-16 01:41
Just an update on my comment.  It must have taken a little bit to either truly clear the cache or maybe for the dns to go through because a few days later I went back and removed the forward page thing on cloudflare and now it works perfect with just phpfox alone.

**Comment by phpfoxdev** [comment] 2016-09-08 07:20
This issue is closed for now, feel free to create one if it happens again.

**Closed by phpfoxdev** 2016-09-08 07:20 UTC
Labels: Not a bug
