### ISSUE TITLE
Found Some Bugs in 4.0.0rc2

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#41] opened 2015-07-06 00:44 UTC
hi
I was just testing the script and found some bugs .
1. When we try to modify the pages ( about us , privacy policy) and save them  we got an error "Page is missing data" this happens even if try to make a new page same like about us etc.
2. I have two user accounts  when i sent a PM to other account i am not getting any notification for new message.
3. I created an announcement  but it is not appearing anywhere on the index page ( logged in and non logged in pages).
4. when we receive a notification about anything e.g.  new friend request or  post likes etc, the notification is not disappearing even we click on it . the blue counter remains there. i am having this issue on community.phpfox.com also.
Thanks

**Comment by Data66PF** [comment] 2015-07-09 13:02
For #4, it will disappear if you refresh the page (I have to use ctrl + f5).

**Comment by aakash83** [comment] 2015-07-10 19:02
now i am updated to 4.0.0. I can create a page but there is still a bug. I created a page and used a hello world php code i saved it and the page was ok. i came back to edit page and i can't see that php code now. I repeated the process using  html code and the problem is same. is this normal or a bug?

**Comment by aakash83** [comment] 2015-07-10 19:16
Another small bug: On login page when we enter username and password and click the "Remember me"  the check box disappears .it comes back when we again click "Remember me" but remains unchecked. it is happening on your demo community also.

**Comment by Data66PF** [comment] 2015-07-10 19:22
@aakash83 Could you please only put one bug per issue? It makes it easier to put the fix numbers and close fixed bugs. Thank you!

**Comment by aakash83** [comment] 2015-07-10 19:24
ok . Sorry if something went against the standards.

**Comment by Data66PF** [comment] 2015-07-10 19:25
It's ok. It just makes bug squashing easier if each item is in a separate issue. :)

**Comment by aakash83** [comment] 2015-07-10 22:42
ok data i am deleting it from here and opening a new issue .thanks

**Comment by Data66PF** [comment] 2015-07-21 22:03
Is this one resolved for you with version 4.0.3?

**Comment by aakash83** [comment] 2015-07-22 00:42
No. the bug is still there in 4.0.3. I can create a page and when i go for edit i can't see html or php code which was added previously. OR sometimes there are few characters or a half line of code but if we save it for 2nd time without any modification it will treat everything as text. should i post it as a new issue??

**Comment by Data66PF** [comment] 2015-07-22 09:21
No don't post a new issue. I cannot reproduce this as it works for me.

**Comment by Data66PF** [comment] 2015-07-23 11:52
Closed as he opened the other ticket instead.

**Closed by Data66PF** 2015-07-23 11:52 UTC
Labels: cannot reproduce
