### ISSUE TITLE
Navigation options disappear 

### ISSUE THREAD

**Issue by Lukey199223** [moxi9/phpfox#1270] opened 2016-03-27 17:11 UTC
Hello :) 

I posted this on the community aswel

when you click on for example the "Messages" , the menu pages disappear, it seems like they sometimes disappear until you click the messages again and sometimes they disappear just for a couple of seconds

**Comment by Data66PF** [comment] 2016-03-27 19:23
Please make sure when testing that you are using v4.3.0 build 5 and that you tested at the phpFox demo https://v4.phpfox.com .

**Comment by Lukey199223** [comment] 2016-03-29 13:07
forgot there was a build 5 to be honest :/ ,sorry Donna aha

**Comment by Data66PF** [comment] 2016-03-29 14:05
If you see the issue is resolved at our live demo, please close this issue report. :)

**Comment by Lukey199223** [comment] 2016-03-30 17:29
The issue is not in the demo, I've upgraded to 4.3 build 5 and the problems still there, I'm using neutron , so I'm not sure if its just a problem with the neutron theme because I cant reproduce it on the demo :)

**Comment by Data66PF** [comment] 2016-03-31 13:05
Ok I see what you are talking about in neutron. This is how it is designed as the messages or notifications open above into the navigation. Once those boxes are closed, the navigation comes back.

**Closed by Data66PF** 2016-03-31 13:05 UTC
