### ISSUE TITLE
FTP Account setting missing

### ISSUE THREAD

**Issue by Avisjay** [moxi9/phpfox#1027] opened 2016-01-28 23:59 UTC
core version 4.2.0 (build 7), Php version 5.4.45 , windows 7,

FTP account missing on admincp setting. hosting support confirm no issue on server environment.

![ftp account miss](https://cloud.githubusercontent.com/assets/16947473/12662854/2381ce9a-c649-11e5-84f2-ca8cf8d5df0c.png)

**Comment by Data66PF** [comment] 2016-01-29 10:51
Please put a title that describes the issue when reporting.

Did you run the Find Missing Settings and the Find Missing phrases? I cannot reproduce this.

**Comment by RaymondBenc** [comment] 2016-05-10 09:04
Currently closing, as this method is no longer supported and was being tested in an earlier version.

**Closed by RaymondBenc** 2016-05-10 09:04 UTC
Labels: Bug
