### ISSUE TITLE
Bug(Status Share Place Holder text Posted on wall)

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#163] opened 2015-07-21 10:19 UTC
In Status Share Box Place Holder is not working properly.When we click on photo section then on Status we have to manually delete placeholder text.But Unfortunately if we click on share place holder text posted on wall

**Comment by Data66PF** [comment] 2015-07-21 14:07
I cannot reproduce this issue on the latest build nor on the PHPfox community site.

**Comment by SalmanKhan86** [comment] 2015-07-22 06:25
![write something post](https://cloud.githubusercontent.com/assets/13433124/8819257/486f10a4-3068-11e5-8bc7-3124e1fce2b8.png)
pls check this screenshot! its happen we have to manually delete that text that overlap place holder text

**Comment by Data66PF** [comment] 2015-07-22 09:24
What OS and browser?

**Comment by SalmanKhan86** [comment] 2015-07-22 09:30
window 7 tested on Mozilla as well as chrome.but same result

**Comment by Data66PF** [comment] 2015-07-22 09:31
Hmm. We had issues with the dreaded Win 7 before. I'll see if I can reproduce it anyway though on my 8.1 pro. If not, Ray has a Win7 test machine I think.

**Comment by Data66PF** [comment] 2015-07-22 09:35
http://community.phpfox.com/profile-natio/# just tested with win 8.1 pro, latest firefox. Worked fine. When I clicked to post a message, the text disappeared as it should. Will have to test in win7.

**Comment by SalmanKhan86** [comment] 2015-07-22 09:40
http://community.phpfox.com/profile-natio/# pls check still its posted on wall.i just test it

**Comment by Data66PF** [comment] 2015-07-22 09:53
Please see my comment above as I said we have to test with Win7. That comment was for Ray. Thanks!

**Comment by Data66PF** [comment] 2015-07-22 09:53
Marked as a bug so we test with Win 7.

**Closed** 2015-07-25 15:45 UTC
Labels: bug
