### ISSUE TITLE
Sign Up Form - Repeating reCaptcha 

### ISSUE THREAD

**Issue by NathanielRand** [moxi9/phpfox#764] opened 2015-11-30 19:05 UTC
- Browser: Chrome
- User Group: Guest
- Steps : 1.) Sign Up Form. 2.) Selected "Click here to learn more about our memberships." 3.) Additional reCaptcha appears. 4.) Exited membership popup 5.) Repeated step 2 and additional reCaptcha stacked on top of previous two.
- Screenshot:
![screenshot_1](https://cloud.githubusercontent.com/assets/16087849/11481345/e9c4f6a8-976a-11e5-9dbe-f4a11d955754.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/16087849/11481344/e9c40450-976a-11e5-8f62-79266f7cd064.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/16087849/11481343/e9c1848c-976a-11e5-8297-654c54bdbfe6.png)

- Reproduce: Yes
- Support Ticket: No
- PHPFox version/build: Neutron v4.0.10(build 1447692264)

**Comment by neil96** [comment] 2015-12-01 02:09
comfirmed on 4.1.0

**Comment by Data66PF** [comment] 2015-12-01 12:03
https://github.com/moxi9/reCAPTCHA/issues/6 duplicate of that one.

**Comment by neil96** [comment] 2015-12-23 10:19
This bug is caused by Recapcha App, It can not fixed within platform core. Please follow status of this issue on moxi9/reCAPTCHA#6.

**Closed by neil96** 2015-12-23 10:19 UTC
Labels: Bug
