### ISSUE TITLE
Message is hiding behind the front panel on phpfox mobile version

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#307] opened 2015-08-09 01:42 UTC
while browsing with iphone6 when we click "messages"  and then click on any message ,the preview panel is hiding the recently opened message .so we can't read or reply that message. I am having this problem while browsing with an Android phone also.

Please modify this panel settings so it should disappear automatically when we don't need it for desktop users also.

**Comment by Data66PF** [comment] 2015-08-09 09:01
duplicate of your bug #177 which is working as designed. Please do not post duplicates.

**Closed by Data66PF** 2015-08-09 09:01 UTC
