### ISSUE TITLE
Missing Create Campaign Button

### ISSUE THREAD

**Issue by leandrotavaresrocha** [moxi9/phpfox#565] opened 2015-09-29 13:48 UTC
Until the end of V3 there were an option to create campaign directly from the backend and this setting is missing in v4, although it is possible to access this feature if you go directly to "/admincp/ad/add".

In consequence in the campaign creation screen is missing the "media" button where you before could upload a image to the ad and a dropbox where was possible to chosse between a html banner or image banner.

**Comment by Data66PF** [comment] 2015-09-29 14:43
This is a duplicate of others. This feature was removed. There will be an app coming for admin and other ads. Ads can be created in blocks as mentioned in the other issue reports.

**Closed by Data66PF** 2015-09-29 14:43 UTC

**Comment by leandrotavaresrocha** [comment] 2015-09-29 14:46
But ads in block dont rotate. With the old feature was possible to create multiple ads and put in the sponsored block to rotate, now this is not possible.

**Comment by Data66PF** [comment] 2015-09-29 18:01
You'll need to add a feature request in the feature request forum or please wait for the ad app that is coming from Vieber.
