### ISSUE TITLE
Cant send messages on ios and android device

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#365] opened 2015-08-17 19:08 UTC
I cant send message on mobile device because there no send button.

**Comment by Data66PF** [comment] 2015-08-18 13:37
Hit the Return or Enter key. That is how it is designed. There is no Send button.

However, if you mean that there no envelope icon on a user's profile so you can message them, I see that the number of friends is overlapping the mail icon. This is a duplicate of #357

**Closed by Data66PF** 2015-08-18 13:37 UTC

**Comment by Ylmzef** [comment] 2015-08-19 00:40
The standard answer "that is how it is designed."
Buddy its not adequate answer.
Users are not coder of designer, they have not enough know knowledge about how phpfox is designed.
There lot of sites on the web. Phpfox must be easy to use for all people at all levels.

**Comment by Jinkers** [comment] 2015-08-19 01:39
@Ylmzef. If that is how it is designed then that is how it is. I support this design. It is a unique software, making it self different from the others there. If these problems are such a problem then you should have thoroughly tested before upgrading/purchasing. 

V4 is still buggy to a certain level and not as well documented as V3. It will take time for adjustments as does with any other software. The developer community will provide more apps that will 'standardize' things once the time is right. Until then, it is how it is.

Admittedly, you do make a good point, not all users are designers/coders. Unfortunately we aren't all good at the sort of stuff but that is how this world works we all have our strengths but as before, you will have to wait it out for these additions to come or to move on.

**Comment by Data66PF** [comment] 2015-08-19 11:41
Thank you  @Jinkers . As for @Ylmzef I'm not a buddy, I'm a woman. Thanks. 

As for this, the other bug was linked for you and you can watch that one for when that issue is fixed if you mean for the small mail icon so that users can send. 

As for the mail issue with it requiring the user to hit enter to send it, you can have a developer create something for you.

As for users not able to figure out your site, that is your responsibility too in making tutorials for your users to use your site. I make them for all of my sites as I know users can get confused with how to do stuff. I even have FREE front end tutorials at my scripttechs site for clients to use on their websites to show users how to use a site (just change the wording some so google doesn't penalize you for using same content). That should help your users use your site. If you need more front end tutorials made, just ask. I make them all the time. Thanks.

**Comment by voarsh** [comment] 2015-09-09 00:29
I also spotted an issue where you can't close msg box on mobile....
