### ISSUE TITLE
Users setting page error

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#227] opened 2015-07-27 21:44 UTC
I upgraded from v3 to v4 after upgade im getting error in /user/setting/ page.

Exception thrown with message "Undefined index: custom"

Stacktrace:
#7 Exception in /home/xxxxxxxxxxx/public_html/PF.Base/start.php:118
#6 Whoops\Exception\ErrorException in /home/xxxxxxxxxxx/public_html/PF.Base/module/user/include/component/controller/setting.class.php:135
#5 Whoops\Run:handleError in /home/xxxxxxxxxxx/public_html/PF.Base/module/user/include/component/controller/setting.class.php:135
#4 User_Component_Controller_Setting:process in /home/xxxxxxxxxxx/public_html/PF.Base/include/library/phpfox/module/module.class.php:963
#3 Phpfox_Module:getComponent in /home/xxxxxxxxxxx/public_html/PF.Base/include/library/phpfox/module/module.class.php:520
#2 Phpfox_Module:getController in /home/xxxxxxxxxxx/public_html/PF.Base/include/library/phpfox/phpfox/phpfox.class.php:1278
#1 Phpfox:run in /home/xxxxxxxxxxx/public_html/PF.Base/start.php:73
#0 require in /home/xxxxxxxxxxx/public_html/index.php:7

**Comment by Data66PF** [comment] 2015-07-27 23:21
duplicate of your other bug #187

**Closed by Data66PF** 2015-07-27 23:21 UTC
