### ISSUE TITLE
Ubiquitous avatar cropping tool error when uploading smaller image 

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#630] opened 2015-10-16 02:28 UTC
When a new user goes to upload their avatar, the cropping tool opens.  If the photo is too small, the cropping tool presents the option to save anyways (implying that it has agreed to compromise and go away).  So they save, but it gives them an error instead of going away.

At this point, the avatar does take to the usersname, and if the user exits the screen with the error (the only way to get it to go away)  by clicking on their profile, it is found that that avatar has also scaled correctly to fit the larger image placeholder.

When each new user logs into the site and gets this error every time they try to upload, it creates a bad first impression, possibly reasoning that they did not get past a dozen or two mouse clicks before getting an error that did not reset.

The cropper seems to have done its job (scaled if too small, or cropped if too large).  It just does not handle the error that results from the "Save Anyways" button being clicked.

**Comment by phpfoxdev** [comment] 2015-10-16 04:54
Confirmed, the "Error" message shall not display in this case.

**Comment by Data66PF** [comment] 2015-10-16 09:40
Just a note, this is how it's always worked. I have tutorials that mention for front end for users not to click Save unless they are cropping.

**Comment by Gatsby-PF** [comment] 2015-10-16 19:53
So the cropping tool instructional content should reflect that then.  But that is not to say that the save anyways option is still not misleading as it implies they should save if it is too small (which it is), but they shouldn't because the should just exit without saving.

**Comment by Data66PF** [comment] 2015-10-19 10:49
marked as a bug due to the issue of the error popup for small images won't go away. A temporary solution is what other clients have done. Change the phrase for that "The image you uploaded is rather small so we are unable to crop it, however you can still save this image if you want to use it." to be "The image you uploaded is rather small so we are unable to crop it but it has already been saved as your avatar."

**Comment by phpfoxdev** [comment] 2015-10-26 10:11
Fixed, will be released in next version.

**Comment by Data66PF** [comment] 2015-11-13 14:58
Fixed in v4.0.10 *staff note YPFOXNEUTRON-77 *

**Closed by Data66PF** 2015-11-13 14:58 UTC
Labels: Bug, Fixed, Minor
