### ISSUE TITLE
Google Chrome - Pages

### ISSUE THREAD

**Issue by MBonner702** [moxi9/phpfox#155] opened 2015-07-20 23:43 UTC
I don't know if this is a bug or not but when you create a page, add a cover to the page and view it through Internet Explorer, the pages fits the window. In Google Chrome, however, the page is larger than the screen size and requires the scroll tools to see everything.
Again, don't know if this is a bug or not.

**Comment by Jinkers** [comment] 2015-07-20 23:53
Can you post some pictures of this?

**Comment by MBonner702** [comment] 2015-07-21 00:13
![2015-07-20 17_04_36-paid dating 101 _ cherry dollar - internet explorer](https://cloud.githubusercontent.com/assets/13371544/8790390/656aef64-2f02-11e5-9da7-988ec40ad003.png)

![2015-07-20 17_07_18-paid dating 101 _ cherry dollar](https://cloud.githubusercontent.com/assets/13371544/8790397/6fb9bdce-2f02-11e5-963e-f723dcaeacd8.png)

The 1st image is Internet Explorer. The 2nd is Google Chrome. They're both shown without any kind of zoom. The Google Chrome version is larger than the page.

**Comment by Data66PF** [comment] 2015-07-21 09:21
What OS? Do you have the same issue on the PHPfox community demo site?

**Comment by Data66PF** [comment] 2015-07-23 17:51
I can't reproduce it. I tried with chrome and the cover photo is fitting like it does for FF, it doesn't span the entire page but I am testing on v4.0.3.

**Comment by RaymondBenc** [comment] 2015-08-04 08:13
This was a known issue for versions before 4.0.4. If upgraded, can you reproduce?

**Comment by phpfoxdev** [comment] 2015-10-08 07:25
It's fixed in 4.0.8

**Comment by Data66PF** [comment] 2015-10-14 09:14
https://github.com/moxi9/phpfox/commit/845ebcf390e8ed980c42284dbfa7af6bc742cec8

**Closed by Data66PF** 2015-10-14 09:14 UTC
Labels: fixed
