### ISSUE TITLE
Feed  : New Update Messages 

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#1074] opened 2016-02-04 19:19 UTC
Latest Phpfox with bootstrap and chrome
This is an old issue posted earlier and was marked as fixed but still facing in latest version. sometimes when we don't have any new updates but phpfox shows  we have X new updates. Sometimes it says  1   and sometimes 591 new updates. but  there is no specific way to reproduce it .
![image](https://cloud.githubusercontent.com/assets/406030/12826681/82b0b2f4-cb7c-11e5-80a5-9d1af8d2ee4a.png)

**Comment by neil96** [comment] 2016-02-05 01:37
Could you give me anwser me some questions here:
- Is your site have sponsor feed?
- If all your feeds loaded before update message show?
We have some fixs since relate this issue closed. These fixed updated in V4.2.1.

**Comment by Data66PF** [comment] 2016-02-05 13:06
duplicate of #1042

**Closed by Data66PF** 2016-02-05 13:06 UTC
