### ISSUE TITLE
Manage friends menu link

### ISSUE THREAD

**Issue by zx500** [moxi9/phpfox#203] opened 2015-07-23 20:18 UTC
1- go to a Discussions of froum in http://community.phpfox.com and click reply a popup will be open dont close it go to menu and click photo , video , member or .... the popup still open . is it a bug ?

2- manage friend url in http://community.phpfox.com is mistak

**Comment by Data66PF** [comment] 2015-07-23 20:40
Please post only one bug per issue.  Please check the tracker before posting bugs as issue 1 is a duplicate of issue #177  
As for issue 2, please describe the issue fully. Thank you.

**Comment by zx500** [comment] 2015-07-24 12:08
for issue 2 in side menu click on manage friend it go to members page not friend page the valid url is sitename/friend not sitename/user/friend/

**Comment by Data66PF** [comment] 2015-07-24 12:26
There is no Manage Friends in the side menu in V4. There is a Members link in the side menu in default V4 at the community. http://community.phpfox.com/forum/ at that location.

**Comment by zx500** [comment] 2015-07-24 15:53
whta is this ? 
http://oi59.tinypic.com/27y0gpj.jpg

**Comment by Data66PF** [comment] 2015-07-24 16:46
That is a drop down, not a side menu. I'll go look.

**Comment by Data66PF** [comment] 2015-07-24 16:47
I'll confirm that if you click the drop down at View Profile, the Manage Friends link goes to the old user/friend instead of /friend

**Comment by zx500** [comment] 2015-07-24 16:48
ty :/

**Comment by Data66PF** [comment] 2015-07-24 16:49
yw :)

**Comment by aakash83** [comment] 2015-07-25 04:10
there is another problem with this "manage friend " link. we have 5 items in that drop down list but if you click "manage friend" link this drop down menu will disappear.  if you click any other link e.g. "Edit Profile" this drop down menu will stay there which is a normal behaviour.

**Comment by RaymondBenc** [comment] 2015-07-25 16:08
Issue has been resolved for our next release, 4.0.4.

**Closed** 2015-07-25 16:15 UTC
Labels: bug
