### ISSUE TITLE
Custom Fields Issues

### ISSUE THREAD

**Issue by leandrotavaresrocha** [moxi9/phpfox#225] opened 2015-07-27 17:33 UTC
Hello Again,

I noticed two possible issues related to custom fields creation:

1- When creating a new custom field if you select the type selection box there is no button or link to add more options than the first. 
2- The option to create a group is not working also. After fill the information and click on "add group" the script request a module, however there is no box where we can select a module.

**Comment by Data66PF** [comment] 2015-07-27 20:54
Please post one issue per bug so we can confirm or mark them as needed. Please search before posting. Issue #1 is a duplicate of #108

**Comment by Data66PF** [comment] 2015-07-27 20:59
I cannot reproduce this. 
1. I click to make a custom group
2. I have already set a user group to be able to have custom fields, required in order to make a custom group for the user group.
3. I select the module Custom from the list. This is working fine for me.

![custom group](https://cloud.githubusercontent.com/assets/6908282/8917588/e3ee56e0-3480-11e5-81f8-2e782654384b.png)
V4.0.3

**Comment by leandrotavaresrocha** [comment] 2015-07-30 02:44
This is weird data.

I did the followint steps:

1- Custom Fields; (admincp)
2- Clicked at Create a New Custom Field; (admincp/custom)
3- Clicked at "Create a New Group"; (/admincp/custom/add/)
4- Select a location (user profile) and give a Group Name. There is no option to select at Group Member box. After hit Add Group no result the error occur (admincp/custom/add/#pem)

**Comment by RaymondBenc** [comment] 2015-08-04 10:26
Issue has been fixed in a recent dev build so @Data66PF wasn't able to reproduce as she has access to it. Issue will be released to the client build today with v4.0.5.

**Closed by RaymondBenc** 2015-08-04 10:26 UTC
Labels: cannot reproduce
