### ISSUE TITLE
without permission to access the restricted parts destined for a group of subscribers.

### ISSUE THREAD

**Issue by cympgo** [moxi9/phpfox#1196] opened 2016-03-11 17:13 UTC
one page in AdminCP for a given I created group of subscribers have access works , other subscribers of other groups can not see the content, and is redirected to the subscriber page . more I do the logaut I can see restricted content of the page .

How do I block access to a particular page I created when agent creates the page choose the access group , so far works. members of other access groups can not access, open the page to sign package. more when I do my logout I can access the page that was supposed to be locked. only works for those who are logged in the community, a visitate accesses the coumidade without logging it can access the content that was supposed to be locked.

**Comment by cympgo** [comment] 2016-03-11 17:23
Images:
creating page and giving access to a particular subscription group.
http://xdkplus.96.lt/imagem1.jpg

creating page and giving access to a particular subscription group.
http://xdkplus.96.lt/imagem2.jpg

User without permission when you try to access the address : http://www.xdkplus.com/download-de-projetos/ is redirected to : http://www.xdkplus.com/subscribe/
http://xdkplus.96.lt/imagem3.jpg

User with permission to access the normal url: http://www.xdkplus.com/download-de-projetos/
http://xdkplus.96.lt/imagem4.jpg

Now if I log out I can access the restricted page , there is no lock.
http://xdkplus.96.lt/imagem5.jpg

**Comment by Data66PF** [comment] 2016-03-11 21:31
If you clear your browser cache are you able to see the page?

**Comment by cympgo** [comment] 2016-03-13 22:54
Yes , I tested in more than one browser . most still have access to a private page to the group without logged . I think it's a bug. you could do a test in your community? creates a page restricted to a group of User and then do the logaut and try to access the page . I believe that you will identify the error.

**Comment by cympgo** [comment] 2016-03-13 23:00
is the page is supposed to be accessed by a group that has been determined .
http://www.xdkplus.com/download-de-projetos/

**Comment by cympgo** [comment] 2016-03-13 23:02
You can create an account in this community and prove the error, after logging try accesses this URL again, you will see that you can not access it.
http://www.xdkplus.com/download-de-projetos/

**Comment by neil96** [comment] 2016-03-14 02:01
I can't reproduce on 4.3.0.

**Comment by cympgo** [comment] 2016-03-15 12:21
The 4.3.0 version of phpFox not resolvel this error of logic , how can I solve this? with this error does not make sense I have a community with subscriber packages, I can not put restricted content from error. Data66PF have as you give me a position of how much to correct and logical error, this bug ?

**Comment by Data66PF** [comment] 2016-03-15 16:33
I am unable to reproduce this on my dev site. 

1. I created a page in AdminCP that has permissions for only two groups - Admin and Jedi.
2. I view that page in a different browser as a guest and get the subscribe message and cannot see the page. This is working as expected.
3. I am logged in as Admin and can see the page. This works as expected. 
4. I log in as a user in the Jedi user group and can see the page. This works as expected.

**Comment by cympgo** [comment] 2016-03-15 16:40
Yes, it all works here too. try to finish their session by logging out and so access the url of the page that you created without enta logged in the system ! var will you will be able to access without A LICENSE for this. or will need is logged to access the page created. I'm talking about this logic error.

**Comment by cympgo** [comment] 2016-03-15 16:50
I just want you to try to access the url of the page you created , without having logged onto the system . I believe you will be able to see the contents of it without having access to it.

**Comment by neil96** [comment] 2016-03-16 02:16
I still can't reproduce with your steps you gave.

**Comment by Data66PF** [comment] 2016-03-16 11:49
I tried by being logged in as admin and then logging out. I cannot see the page.

I tried a different browser that I hadn't logged in with and used the direct url of the page and still cannot see the page content.

**Comment by cympgo** [comment] 2016-03-16 11:56
then what you can is acotecendo with my community? It has been changed to the new version 4.3 and continues with the same ess of unauthorized access to a one page it would be private .

**Comment by cympgo** [comment] 2016-03-16 11:59
you know the heart of your system better than I, what should is going to have this open Security Industry in my community ? I need to fix it ! I do not have to offer exclusive content to certain group members.

**Comment by cympgo** [comment] 2016-03-16 12:47
Hello , I made a local installation to see if it was no mistake in my outdoor installation , did the same test , I created a new page and put access to two groups , admin and Guest . I did the admin account logaut and tried to access the URL of the page I created with restricted access and I can access it without logged . I created a new account Registered User group , after logging in I can not access the url of the page I created. in short: the system works for those who are playing active session if you do not have an active session will be able to access it without having A LICENSE . the error is I have no access is logged . is no mistake in my active community , made ​​a local installation and has the same error.

**Comment by cympgo** [comment] 2016-03-16 14:44
As my community is not broken as I thought , because I made a new local installation and has the same bug in my active community . which may have different here in my in that you do not have? if I just do a fresh install with version 4.3.0 and the same bug has been found! need to fix this , my community is stopped because of this error of logic , how can I solve?

**Comment by neil96** [comment] 2016-03-17 01:55
Please submit a ticket with your site information. I will check for you!

**Comment by Data66PF** [comment] 2016-03-17 13:13
@neil96 please see ticket 144 in our new system.

**Comment by Data66PF** [comment] 2016-03-21 12:19
Closed as this was a operator error and not a bug.

**Closed by Data66PF** 2016-03-21 12:19 UTC
Labels: Cannot reproduce
