### ISSUE TITLE
Request to disable general information links for closed or invite only systems

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#1104] opened 2016-02-09 15:17 UTC
Please provide user group permissions for Terms/Privacy/About pages. Sites configured as closed sites (registration disabled), or invite only sites (registration selectively enabled), are not intended for public use, therefore the public does not have need to have access to any information on what the site is about, what its terms are, or privacy policy is, until they are validated as an invitee.

A simpler way might be to provide a general control to disable such general information links if either closed or invite only operation is enabled.

**Comment by Data66PF** [comment] 2016-02-09 15:21
I believe this is a duplicate of the one for disabling guest access to menus. However, I will let our tech determine if this would be a separate issue.

**Comment by Data66PF** [comment] 2016-03-08 13:40
This issue was moved to moxi9/phpfox-feature-requests#59

**Closed by Data66PF** 2016-03-08 13:40 UTC
Labels: Enhancement
