### ISSUE TITLE
[4.4.0-beta1] Feed Deletion Notice Issue Neutron Theme

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#1491] opened 2016-06-28 06:31 UTC
when we delete any feed a notice comes with confirmation box and when we click on no then its does't hide even we click on yes then box comes with feed successfully deleted msg still it does't disappear.
![feed deletetion notice](https://cloud.githubusercontent.com/assets/13433124/16405815/0c301c1e-3d28-11e6-999e-7e7e488b408c.png)

**Comment by neil96** [comment] 2016-06-28 06:35
Please try to clear site cache and test again. I can't reproduce on my side.

**Comment by SalmanKhan86** [comment] 2016-06-28 06:47
i cross check it same issue found on chrome and Mozilla

**Comment by SalmanKhan86** [comment] 2016-06-28 07:02
when we click on No first time its works fine with me then again second time on same feed it does't hide box when we click on NO

**Comment by neil96** [comment] 2016-06-28 07:25
It's working with bootstrap theme. We will check and fix all issues on neutron theme after 4.4 final released.

**Comment by Data66PF** [comment] 2016-07-05 10:18
closing for now. theme is removed from the store for now. we will open a new area for neutron once we are ready to get that theme fixed.

**Closed by Data66PF** 2016-07-05 10:18 UTC
Labels: Neutron theme
