### ISSUE TITLE
Cropping image by mobile not possible

### ISSUE THREAD

**Issue by optiroot** [moxi9/phpfox#729] opened 2015-11-19 09:12 UTC
On PHPFox 4.0.10, if you upload an avatar on mobile (Android & Chrome latest, in my case; I don't know for iOS and more), you can't simply select the thumbnail; if you touch the image nothing appears but a small thumbnail at the right of the image that has taken just an upper-left side of the image: pratically doesn't let you select the thumbnail as on desktop, and it will select the thumbnail automatically from the up-left side of the image, for a square.

Is this a bug?

**Comment by Data66PF** [comment] 2016-01-04 12:40
as this is an enhancement and not a bug, we will close this for now until we are doing feature enhancements as the bug tracker is only for bugs.

**Comment by Data66PF** [comment] 2016-01-04 12:42
Actually, I'm not sure if this is an enhancement only issue since it impacts mobile devices and we have clients that mainly use mobile for their sites. Will leave it open for now.

**Comment by optiroot** [comment] 2016-01-07 13:59
Thank you. 

It is really important, even because I think that from here comes another bug, which if I see it continues in the next release, I'll post here in GitHub.

**Comment by optiroot** [comment] 2016-01-21 17:10
@Data66PF anything about this? 
Mobile users sometimes have problem about. Thumbnail doesn't ever positions how it should for mobile users, and they get problems for this...

@phpfoxdev @neil96 can you do something about this? Thank you!

**Comment by Data66PF** [comment] 2016-02-18 14:00
This issue was moved to moxi9/phpfox-feature-requests#19

**Closed by Data66PF** 2016-02-18 14:00 UTC
Labels: Enhancement
