### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by leandrotavaresrocha** [moxi9/phpfox#637] opened 2015-10-17 00:56 UTC
Sometimes I receive this weird error when loading the main feed and sometimes it only appear when I enable the console from google chrome.

Until I could discover seems that it is related with the following file/line:

PF.Base/static/jscript/user_info.js

user_info.js:80
Uncaught TypeError: Cannot read property 'replace' of undefined(anonymous function) 
@ user_info.js:80jQuery.event.dispatch 
@ jquery.js:4665elemData.handle 
@ jquery.js:4333

user_info.js:126 
Uncaught TypeError: Cannot read property 'replace' of undefined(anonymous function) ]
@ user_info.js:126jQuery.event.dispatch 
@ jquery.js:4665elemData.handle 
@ jquery.js:4333

**Comment by Data66PF** [comment] 2015-10-17 09:51
Does the error show like this? https://github.com/moxi9/phpfox/issues/522

**Comment by leandrotavaresrocha** [comment] 2015-10-17 13:09
Yes @Data66PF, this is the main issue. I noticed that sometimes it dont appear in the feed, but appear in the java console.

**Comment by Data66PF** [comment] 2015-10-17 13:43
ok this is a duplicate of that bug and I had given him the error message Friday as we finally were able to see it again in the live community. I'll close this for now as that issue is being resolved. However, if you find that once that issue is fixed and a release done, and you upgrade at that time, if that doesn't fix this, please have me open this one again.

**Closed by Data66PF** 2015-10-17 13:43 UTC
