### ISSUE TITLE
Bootstrap Theme - forum post sort -missing values

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#853] opened 2015-12-19 06:02 UTC
latest phpfox with chrome

![image](https://cloud.githubusercontent.com/assets/406030/11911688/76faeb6a-a61e-11e5-87e8-b86e7be1abd4.png)

**Comment by Data66PF** [comment] 2015-12-19 10:27
duplicate https://github.com/moxi9/phpfox/issues/855

**Comment by aakash83** [comment] 2015-12-19 12:01
This is  not a duplicate. previous one was for items per page. this one is for   Sorting options. @Data66PF

**Comment by Data66PF** [comment] 2015-12-19 13:36
You need to better describe the issues when reporting please. don't just put an image. Put actual steps to reproduce. I still don't know what the issue is. All I see is that you circled sort.

**Comment by Data66PF** [comment] 2015-12-19 13:48
Ok I can see the issue. The sort is not needed in the forum as we have the other options there.

**Comment by aakash83** [comment] 2015-12-19 15:49
i think it is very clear that  options for post sorting are missing  like  sort alphabetically  or  newest first etc. and it can be  clearly seen that  "sort" button is clicked.    if they don't need sorting then this button should be removed

**Comment by Data66PF** [comment] 2015-12-19 16:18
There never was a sort alphabetically but as I mentioned before, I see the issue and I marked it a bug before when I said I had seen the issue. Thanks for posting.

**Comment by neil96** [comment] 2016-01-05 17:01
I think your site is missing phrase. Could you test again with debug mode on?

**Comment by Vivian-phpFox** [comment] 2016-01-15 05:00
We'll put back the quick links and forum search tool function

**Comment by robert9592** [comment] 2016-03-02 13:10
Fixed in v4.3.0

**Closed** 2016-03-03 07:48 UTC
Labels: Enhancement, Fixed
