### ISSUE TITLE
Show/Hide Menu Problem With Android OS

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#368] opened 2015-08-18 12:40 UTC
when we show/hide menu in Android OS its left with white border line.
![screenshot_2015-08-10-09-40-40](https://cloud.githubusercontent.com/assets/13433124/9330069/5d2f874a-45d4-11e5-8f16-1060d265a820.png)

**Comment by Data66PF** [comment] 2015-08-18 13:22
I'm not having any luck reproducing this on an iPhone 5c.

**Comment by Jinkers** [comment] 2015-08-18 13:30
Likewise. Im unable to reproduce on Samsung s4.

**Comment by SalmanKhan86** [comment] 2015-08-19 12:11
i have tested it with Android 4.4.4 both on chrome and Mozilla same problem exists.

**Comment by SalmanKhan86** [comment] 2015-10-08 11:22
i am on Android OS.check PFA for same
![screenshot_2015-10-08-16-44-59](https://cloud.githubusercontent.com/assets/13433124/10364907/e581b9a8-6ddc-11e5-9519-bd16110478b8.png)

**Comment by Jinkers** [comment] 2015-10-08 21:50
Can confirm on PF Community, android Samsung s4 chrome browser. Replication is a matter of opening the menu via the stacked lines, tapping the arrow to expose the 'What's Up?' section, then tapping the stacked lines again without closing the 'What's Up?' section. 

It leaves a transparent box, kinda as if a div hasn't been removed.

**Closed** 2015-11-30 03:06 UTC
Labels: Help wanted
