### ISSUE TITLE
Video Play 

### ISSUE THREAD

**Issue by signupsi** [moxi9/phpfox#104] opened 2015-07-15 13:30 UTC
How to test : 
go to /video 
play any video 
click any where on screen 
video goes away 

problem : you keep hearing the sound

**Comment by signupsi** [comment] 2015-07-16 15:16
the problem persists in 4.02 as well 

and you can test on community.phpfox.com

**Comment by Data66PF** [comment] 2015-07-23 18:03
Duplicate of this https://github.com/moxi9/phpfox-videofeed/issues/1

**Closed by Data66PF** 2015-07-23 18:03 UTC
