### ISSUE TITLE
V4 Menu scroll bar does not work in user area, works in Admin area

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#510] opened 2015-09-15 00:40 UTC
V4.02 Menu scroll bar does not work in users area, but works for the Admin area.
Default theme.
Browser: Firefox, Torbrowser Latest.
Affects both PC and mobile (Android) user agents.
Existed on both dev and production server.

The thin menu scroll bar to the right of the menu area does not scroll no matter what page the user is in. Menu items below the display screen are still accessible by selecting a menu item and arrowing down.

Additionally, with mobile user agent (android), there is no scroll for the menu, and no way to access the menu items below the display.  There is only scroll for the main page in mobile.

But it works for Admin area (as long as you are not in settings).

**Comment by Data66PF** [comment] 2015-09-15 12:25
Please search before posting and note that we need only one issue posted per bug report. This is a duplicate of #156

**Closed by Data66PF** 2015-09-15 12:25 UTC
