### ISSUE TITLE
JavaScript error in theme admin

### ISSUE THREAD

**Issue by jpbu** [moxi9/phpfox#647] opened 2015-10-20 19:00 UTC
File PF.Base/module/theme/template/default/controller/admincp/manage.html.php has a wrong jQuery selector (missing a closing bracket) in line 71:
`$('._colorpicker:not(.built').each(function()`
This causes a JavaScript error at least in Safari browser, causing some of the theme admin functions not to work properly

**Comment by Data66PF** [comment] 2015-10-20 19:04
This is my line 71 of the same file in v4.0.9 client version
`$('._colorpicker:not(.built').each(function() {`

**Comment by jpbu** [comment] 2015-10-20 19:26
I posted the line as is, what I wanted to say is that the jQuery selector must be
`$('._colorpicker:not(.built)')`
instead of
`$('._colorpicker:not(.built')`
The bracket inside the selector with the quotes is not closed.

**Comment by Data66PF** [comment] 2015-10-20 19:44
I see that. I also see it in other places in this file like this. I wonder why it causes an issue in safari but not in other browsers. I'll leave this open for a core developer to see as I can't reproduce any issue with admin functions using win 10 and other browsers.

**Comment by neil96** [comment] 2015-11-27 15:21
Fixed in v4.0.10 staff note *YPFOXNEUTRON-106*

**Closed by neil96** 2015-11-27 15:21 UTC
Labels: Bug, Fixed, Major
