### ISSUE TITLE
Edit Cancel Comment Not Working

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#804] opened 2015-12-10 08:19 UTC
when i edit my comment on someone post then click on cancel button in text editor 
its display me object object not my comment
tested it on 4.1.3
![comment edit cancel option](https://cloud.githubusercontent.com/assets/13433124/11710391/c509fffc-9f44-11e5-8c41-aa42b7fa6033.png)

**Comment by Vivian-phpFox** [comment] 2015-12-10 08:34
Can not reproduce on V4.1.1

**Comment by Optiroot** [comment] 2015-12-10 08:35
In fact this has been fixed without knowing of it in v4.1.1, because in 4.1 it was still present!

Great job!

**Comment by Data66PF** [comment] 2015-12-10 13:01
Cannot reproduce at the live http://demo.phpfox.com on v4.1.1 version.

**Closed by Data66PF** 2015-12-10 13:01 UTC
Labels: Cannot reproduce

**Comment by SalmanKhan86** [comment] 2015-12-17 11:52
it is still there in v 4.1.1 pls check and Resolve it

**Comment by SalmanKhan86** [comment] 2015-12-17 11:53
why its closed here.pls open it

**Comment by SalmanKhan86** [comment] 2015-12-17 11:55
Sorry Working fine.....
