### ISSUE TITLE
Invalid password after user registration

### ISSUE THREAD

**Issue by SpeakLife** [moxi9/phpfox#1070] opened 2016-02-04 02:42 UTC
Ok I realize I'm late in the game with this issue but I am currently experiencing it. I didn't notice an issue before with user registration as everything was working fine to my knowledge before my upgrade of 4.0.9 I have a mobile application for apple and android so I know users were able to create accounts just fine then. 

I searched for similar posts and I found this link https://github.com/moxi9/phpfox/issues/279 which shows it's resolved due to changing the password length from 32 to 150. I do believe that is already done however I'm now experiencing this issue. Any suggestions is most appreciated. 

Thanks,
SpeakLife

**Comment by SpeakLife** [comment] 2016-02-04 02:45
Just to clarify I upgraded from 4.0.9 to 4.2.1

**Comment by SpeakLife** [comment] 2016-02-04 03:22
So I went into my database to table **phpfox_user** and then I went down to columns and clicked on **password**.  I saw it has the password character at 32, so I changed it to 150. I then registered a new account and was able to log in however it didn't create my profile correctly. I could navigate to other parts of my website just fine except when I went to my profile it showed me a blank page with two links that said parent directory and some other link I can't recall at the moment. 

So I happened to see a post from Donna about removing email verification. I removed email verification and I removed having the user type in their email twice to verify it that way. I registered a second new account and was able to log into it just fine and when I went to my profile it loaded successfully. I'm going to continue to test some more before I state this is fixed because I should be able to choose fields during registration without an issue. I am using the google captcha that Donna mentioned as well.

**Comment by SpeakLife** [comment] 2016-02-04 04:05
Another Update -

I did a process of elimination. I enabled email verification and created a new account again. I cleared the site cache. I noticed on the first user creation I was able to click on the verification link it emailed me and I was able to log in just fine and view my profile. 

I created a second user account keeping the email verification on again. This time when I clicked on the verification link from my email, it took me to my site but stated "invalid verification link" as it kept mass emailing me a verification link. 

So I went back and turned off email verification again and I was able to create user accounts just fine without any issues so far.

I hope my testing and results help as I feel there could be an issue with the email verification process.

**Comment by Data66PF** [comment] 2016-02-04 14:53
Do you have any apps installed? If so, which ones? Note that facebook app will not work with any extra fields as facebook doesn't like extra stuff (force profile photo upload, email verification, custom fields, etc)

**Comment by SpeakLife** [comment] 2016-02-04 15:18
I have the following apps installed;
Phpfox Facebook Base - disabled (never set it up)
 IM - disabled (never set it up)
Twemoji Awesome (auto enabled)
Videos - enabled (/v/)
Phfox reCaptcha app - enabled (google)

**Comment by neil96** [comment] 2016-02-05 01:58
I can't reproduce this issue when upgrade from 4.0.9 to 4.2.1. Is your site rest install of version 4.0.9 or upgrade from V3?

**Comment by SpeakLife** [comment] 2016-02-05 10:41
My site was upgraded from V3 to V4. I know lots of people had this issue from a previous post. So ever since I changed the password from 32 characters to 150 in my database and made some changes to the registration process everything seems to be working. However I'm curious if this will stick for the next version upgrade. 

So you may close this ticket for now. If I experience this issue again I will let you all know.

**Comment by Data66PF** [comment] 2016-02-05 13:15
Note, please ensure when you upgraded from v3 to v4 that you ran the full upgrade routine. If not, our lead core developer had said before that it would cause site issues.

Closing per the client's request.

**Closed by Data66PF** 2016-02-05 13:15 UTC

**Comment by SpeakLife** [comment] 2016-02-05 13:37
Yes I always run the upgrade routine as defined in each upgrade instructions.

**Comment by mobicomfi** [comment] 2016-03-17 08:43
This issue still exist. I have upgaded site too, but in v4 it works before. But i use now last versin and i tried to make test account and all confirmation letters come, but if i want to login, then i get error invalid password.
