### ISSUE TITLE
Login block

### ISSUE THREAD

**Issue by lordofnos** [moxi9/phpfox#1595] opened 2016-07-29 10:37 UTC
The block log>login that shows last logged in users does not work any more on my site. It does not show up...

**Comment by Data66PF** [comment] 2016-07-29 12:05
I'm guessing this is working as designed as that block, in v3 optimization blog, was mentioned to really slow a site due to queries, etc. It might be disabled now due to our recent optimizations but will let a core developer answer.

**Comment by lordofnos** [comment] 2016-07-29 12:20
then it should be deleted with the new feature to delete files not used?

**Comment by akvaskov** [comment] 2016-08-02 19:02
Probably I have should posted my message as a separate issue but that's not a big thing that's why I deceided to try here.

When I'm logining in the AdminCP, the login form is displayed at the bottom of the respective page althought it seems it should be centralised in the middle of the screen.

![login to admincp](https://cloud.githubusercontent.com/assets/18528411/17341324/c064889c-58fc-11e6-9b0b-709b6bc2bfea.png)

**Comment by lordofnos** [comment] 2016-08-02 19:56
this is about the log module not the user login block.

**Comment by akvaskov** [comment] 2016-08-03 06:13
Oh, ok, but in any case it should be fixed.

**Comment by Data66PF** [comment] 2016-08-03 12:10
Comments that do not belong to the issue are removed. Post a new issue if you find one.

**Closed** 2016-11-07 07:04 UTC
Labels: Bug, Fixed
