### ISSUE TITLE
Theme editor : be able to see the site even if it is offline

### ISSUE THREAD

**Issue by Miroslav36** [moxi9/phpfox#1069] opened 2016-02-03 22:42 UTC
I have noticed that when the site is offline, it is impossible to view the site in the theme editor. I only can see the "offline message" when I am in the menu "homepage" , "logo" or "design" #

**Comment by neil96** [comment] 2016-02-04 01:56
I can't reproduce, could you give us more information?
Note: user still access to login page, and Admin User can use site normal.

**Comment by Miroslav36** [comment] 2016-02-04 18:21
Hello,
I have a screencast explaining the issue.
Just to be sure I explained correctly :
The problem is when I am connected as admin and I want to perform changes on the theme.
this screencast explains the problem : 
https://www.youtube.com/watch?v=Ke8plOET_8I&feature=youtu.be

I enter in the theme editor
I select/edit the current theme
I open the "logo" menu : OK I can see the site
I open the "homepage" menu" : I see the offline message
I come back to the "logo" menu : I see the offline message

I have refreshed the browser , same issue

**Comment by neil96** [comment] 2016-02-05 01:49
Thanks for your screencast!

**Comment by RaymondBenc** [comment] 2016-02-17 13:43
Fixed in 4.3

**Closed by RaymondBenc** 2016-02-17 13:43 UTC
Labels: Bug
