### ISSUE TITLE
The "Next" arrow on photo's doesn't work for me 

### ISSUE THREAD

**Issue by Lukey199223** [moxi9/phpfox#1269] opened 2016-03-27 17:09 UTC
Hello :) 

I've been testing my site all day to see if there's any bugs that can be fixed

and I found 3 I know of (1 has been posted in the community, but will post in here too,incase the community doesn't except bugs 

One of the bugs is 

when your on the photo's page, there's no sign of the "back arrow" and the arrows dont work when clicked

**Comment by Data66PF** [comment] 2016-03-27 19:23
Please make sure when testing that you are using v4.3.0 build 5 and that you tested at the phpFox demo https://v4.phpfox.com .

**Comment by neil96** [comment] 2016-03-28 02:09
Did you mean button for view next/previous photo?

**Comment by Lukey199223** [comment] 2016-03-29 12:53
Ye that's it :) , sorry for the delay in response neil96

**Comment by Lukey199223** [comment] 2016-03-29 12:54
And I dont think I'm using build 5, dull me haha, I forgot that, there was a build 5 *_*, thanks Donna :)

**Comment by Data66PF** [comment] 2016-03-29 14:05
Please test at our live demo and if you see that the issue is fixed there, please close this issue.

**Comment by Data66PF** [comment] 2016-03-30 12:53
This issue was moved to moxi9/phpfox-feature-requests#107

**Closed by Data66PF** 2016-03-30 12:53 UTC
