### ISSUE TITLE
Event date set is displaying the current, not the set date

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#743] opened 2015-11-22 21:53 UTC
When attempting to set date and time for an event (fictitious event for testing) for November 27, at 0:00 hours, then clicking save if new, or update if retrying, the event displays instead for November 22 (today).  Cleared cache and retried, but it displays same result.

Going back to edit the time, it has reverted back to the 22nd.

**Comment by Data66PF** [comment] 2015-11-23 12:05
Cannot reproduce in v4.1.0 which will release this week.
![testing time and date issue social networking community](https://cloud.githubusercontent.com/assets/6908282/11336103/925fe982-91b0-11e5-91de-2d30ac72a856.png)

**Comment by NetworkCycles** [comment] 2015-11-24 02:43
Same exact issue:  

1. Enter date of May 4, 2016 and click Update.
2. The date display today's date. 

3. Also the date picker is overlapped and does not display correctly. 

4. The event display is also bad. See attached images. 

![event_date_picker](https://cloud.githubusercontent.com/assets/13318857/11356281/5cfa54c4-922a-11e5-9d34-b8b628cadc2b.png)
![event_privacy](https://cloud.githubusercontent.com/assets/13318857/11356280/5cfa4f10-922a-11e5-92b0-f9d960bcc60b.png)
![event_photo_error](https://cloud.githubusercontent.com/assets/13318857/11356300/9635d3e4-922a-11e5-917a-02e43cfc71f7.png)

**Comment by NetworkCycles** [comment] 2015-11-24 02:46
The same issue if on the phpFox Demo. 

See http://community.phpfox.com/event/221/v10-event-test-party/ 

I created the event with a date of May 4, 2016. 
The date displayed is Nov 23, 2015 - the same date i created the event. 

The demo display the correct theme layouts.

**Comment by Data66PF** [comment] 2015-11-24 12:02
We've not yet released v4.1.0 as stable. Once the blog is out that v4.1.0 is released, at that time you can upgrade and run all of the upgrade steps posted at scripttechs as well. Our community is still using 4.0.10

**Comment by Data66PF** [comment] 2015-12-23 12:43
Changing this to a bug. I created an event in bootstrap 4.1.2. The vent starts January 23, 2016 6:40 am and note that we have no options to set an end time so for some unknown reason the system is setting it as seen below. We need to add an end date and time back to the process as the script is determining the event will last until today's date next year. (it sets the end to be one year from the date the event is entered)

Saturday, January 23, 2016 6:40 am - Friday, December 23, 2016 7:40 am

**Comment by robert9592** [comment] 2016-01-07 04:02
Fixed in v4.2.0

**Closed** 2016-01-13 10:37 UTC
Labels: Bug, Fixed
