### ISSUE TITLE
bug . change full name

### ISSUE THREAD

**Issue by zx500** [moxi9/phpfox#208] opened 2015-07-24 12:00 UTC
when i want to change full name not change . "Provide a valid email address."

**Comment by Data66PF** [comment] 2015-07-24 13:17
Is this at your site our our community? Did you have an email address entered?

**Comment by zx500** [comment] 2015-07-24 15:42
in your community . no

**Comment by Data66PF** [comment] 2015-07-24 16:09
Did you make sure you have a valid email entered before changing the name?

**Comment by zx500** [comment] 2015-07-24 16:30
yes

**Comment by Data66PF** [comment] 2015-07-24 16:34
Check your settings for emails that you don't allow to be used and make sure you didn't put your email as one of them (perhaps trying to make sure spammers don't sign up with your site email) because it might not let you save it if that is the case.

**Comment by zx500** [comment] 2015-07-24 16:37
i mean i registered in phpfox community . when i want to change my full name in account setting and click save button . it show me a message that is "Provide a valid email address."

**Comment by Data66PF** [comment] 2015-07-24 16:42
I just tested and it works for me. Perhaps your email is not entered correctly. Please PM me at the community site and I'll check your account. http://community.phpfox.com/profile-data66/

**Comment by zx500** [comment] 2015-07-24 16:45
ok .also check issue 203 .i sent you a screenshot

**Comment by zx500** [comment] 2015-07-24 16:55
add me ms lizz . i sent you friend req

**Comment by Data66PF** [comment] 2015-07-24 17:07
As long as you haven't already changed it and gone over the allowance, it should work. I added a gender for you as you hadn't added one.

**Comment by zx500** [comment] 2015-07-24 17:21
i sent you messages

**Comment by RaymondBenc** [comment] 2015-08-04 08:31
Any update on this? Is this still reproducible on our community?

**Comment by zx500** [comment] 2015-08-05 19:29
problem not fixed yet

**Comment by SalmanKhan86** [comment] 2015-08-08 09:33
is this fix in V4.0.5

**Comment by Data66PF** [comment] 2015-08-08 10:22
The forum is running 4.0.5 so if you can still produce it there, it is not fixed yet.

**Comment by Ylmzef** [comment] 2015-09-26 02:45
Is it fixed?

**Comment by Data66PF** [comment] 2015-09-26 09:03
We can't reproduce it. Can you in the community 4.0.8 ?

**Comment by Ylmzef** [comment] 2015-09-27 01:04
I can change on my site.
I think you can marked as fixed.

**Comment by Data66PF** [comment] 2015-09-27 10:40
Ok we'll close this one. You can also close tickets you create if you find them fixed.

**Closed by Data66PF** 2015-09-27 10:40 UTC
Labels: PF Community Issue
