### ISSUE TITLE
Short URL

### ISSUE THREAD

**Issue by muhammadnaeemahsan** [moxi9/phpfox#376] opened 2015-08-19 13:47 UTC
![short urls](https://cloud.githubusercontent.com/assets/12130785/9357916/e190cc8c-46a2-11e5-87bc-731405119180.png)
Create a new file called /.htaccess and add the following:
# START PHPfox Rewrite
<IfModule mod_rewrite.c>
	RewriteEngine On
	RewriteBase /	
	RewriteCond %{REQUEST_FILENAME} !-f
	
    RewriteRule ^(file)/(.*) PF.Base/$1/$2

    RewriteRule ^static/ajax.php index.php
	RewriteRule ^themes/default/(.*) PF.Base/theme/default/$1
	RewriteRule ^(static|theme|module)/(.*) PF.Base/$1/$2
	RewriteRule ^(Apps|themes)/(.*) PF.Site/$1/$2

	
	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteCond %{REQUEST_FILENAME} !-d
	
	RewriteRule ^(.*) index.php/$1
</IfModule>
# END PHPfox Rewrite
Continue below if your .htaccess file is ready.

and we click on enable short urls 

We received error :  The /.htaccess file seems to be missing our Rewrite rules or this server does not support Mod_Rewrite.

we contact with hosting provider. they said its our basic feature Mod_Rewrite.

we install phpfox v4.0.5 and upgraded to v4.0.6  both was same error

**Comment by Data66PF** [comment] 2015-08-19 13:57
Did you make the .htaccess file in the root (or where you have PHPfox installed)?

**Comment by one44** [comment] 2015-08-19 15:43
Maybe check this???  http://blog.phpfox.com/2015/08/11/short-url-rewrite-rules-for-fastcgi-servers-updated/

**Comment by muhammadnaeemahsan** [comment] 2015-08-20 04:17
Yes Dear i made a file adopting provided procedure and take action.
Error : The /.htaccess file seems to be missing our Rewrite rules or this server does not support Mod_Rewrite.
i contact with hosting provider too. they said its our basic feature Mod_Rewrite.

i tried many time. but same error

**Comment by haisay** [comment] 2015-08-21 11:46
The same issue facing me too....
Our Hosting company  also says this is our basic feature Mod_Rewrite.

**Comment by Data66PF** [comment] 2015-08-21 12:13
Did you both try the other short url htaccess linked by @one44 ? I cannot reproduce any issues with short urls on my server but I don't need the special .htaccess file mentioned in that blog.

**Comment by haisay** [comment] 2015-08-22 08:03
Yes i tried.
stills the issue continue...

**Comment by muhammadnaeemahsan** [comment] 2015-08-23 04:52
Issue still in PHPFOX V4.0.7  too

**Comment by AnthonyKing** [comment] 2015-09-21 19:56
if you can not access the website because you enabled the short url, i have a solutions for that

**Comment by Data66PF** [comment] 2015-09-25 13:18
Just installed fresh to another server, this one is nginx and still no issues seen with the new .htaccess. Are you sure you have the newest code?
```
# START PHPfox Rewrite
<IfModule mod_rewrite.c>
	RewriteEngine On
	RewriteBase /	
	RewriteCond %{REQUEST_FILENAME} !-f
	
    RewriteRule ^(file)/(.*) PF.Base/$1/$2

    RewriteRule ^static/ajax.php index.php
	RewriteRule ^themes/default/(.*) PF.Base/theme/default/$1
	RewriteRule ^(static|theme|module)/(.*) PF.Base/$1/$2
	RewriteRule ^(Apps|themes)/(.*) PF.Site/$1/$2

	
	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteCond %{REQUEST_FILENAME} !-d
	
	RewriteRule ^(.*) index.php/$1
</IfModule>
# END PHPfox Rewrite
```

**Comment by muhammadnaeemahsan** [comment] 2015-09-25 13:44
yes new code but not working......   we installed fresh from phpfox v4.0.5 and upgrading to 4.0.6 and to 4.0.7 and now also to 4.0.8 but problem same

**Comment by SpeakLife** [comment] 2015-09-25 15:10
I am still receiving an issue with short urls myself and I upgraded to the latest 4.0.8 Any suggestions anyone?

**Comment by AnthonyKing** [comment] 2015-09-25 16:38
check  that you place the htaccess in the right folder and check that you do not have another htaccess, and if your web host does not have their own htaccess file

**Comment by SpeakLife** [comment] 2015-09-25 18:15
Yes I did that and still no resolution :( the short urls use to work before I switched over to phpfox 4 neutron

**Comment by SpeakLife** [comment] 2015-09-25 18:28
I think what's going on is the phpfox system is looking for a file named /.htaccess when the webhost will not allow a file to start with a "slash"  So you have to create a .htaccess without the slash in front.

**Comment by Data66PF** [comment] 2015-09-25 18:56
I'm not sure what you mean. Short urls work on all of my sites, on the phpfox.com community, on my client sites and on my new nginx server with the provided .htaccess they say to make. It goes in the root where you have phpfox installed if it's in the root (public_html) or in the subfolder you have phpfox installed to. It looks for .htaccess .

**Comment by SpeakLife** [comment] 2015-09-25 20:00
It's obvious I'm not the only person this isn't working for. I did place the .htaccess inside of the (public_html) folder.

Here is the code I used that's in the phpfox 4 site under admin panel> tools>settings> short URL. But this still doesn't work. I still get the error message The /.htaccess file seems to be missing our Rewrite rules or this server does not support Mod_Rewrite.

# START PHPfox Rewrite
<IfModule mod_rewrite.c>
	RewriteEngine On
	RewriteBase /	
	RewriteCond %{REQUEST_FILENAME} !-f
	
    RewriteRule ^(file)/(.*) PF.Base/$1/$2

    RewriteRule ^static/ajax.php index.php
	RewriteRule ^themes/default/(.*) PF.Base/theme/default/$1
	RewriteRule ^(static|theme|module)/(.*) PF.Base/$1/$2
	RewriteRule ^(Apps|themes)/(.*) PF.Site/$1/$2

	
	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteCond %{REQUEST_FILENAME} !-d
	
	RewriteRule ^(.*) index.php/$1
</IfModule>
# END PHPfox Rewrite

**Comment by AnthonyKing** [comment] 2015-09-25 22:18
1 are you using a default theme?
2. if your htaccess is in the public html and the phpfox files are in a subfolder the htaccess wont work because it is looking for the index.php for phpfox
3. have you already enabled short url?
4. test it on a localhost 
5. maybe check the hotlink under security in the cpanel

**Comment by haisay** [comment] 2015-09-27 10:04
My .htaccess file:

# START PHPfox Rewrite
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /   
    RewriteCond %{REQUEST_FILENAME} !-f

    RewriteRule ^(file)/(.*) PF.Base/$1/$2

    RewriteRule ^static/ajax.php index.php
    RewriteRule ^themes/default/(.*) PF.Base/theme/default/$1
    RewriteRule ^(static|theme|module)/(.*) PF.Base/$1/$2
    RewriteRule ^(Apps|themes)/(.*) PF.Site/$1/$2


    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d

    RewriteRule ^(.*) index.php/$1
</IfModule>
# END PHPfox Rewrite

"I still get the error message The /.htaccess file seems to be missing our Rewrite rules or this server does not support Mod_Rewrite."

**Comment by AnthonyKing** [comment] 2015-09-27 21:02
# Mod Rewrite
Options +FollowSymLinks
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
The fix to this problem was to add the following directive before my mod_rewrite directives:

#Fix Rewrite
Options -Multiviews

**Comment by AnthonyKing** [comment] 2015-09-27 21:09
http://smartwebdeveloper.com/apache/htaccess-problems

**Comment by AnthonyKing** [comment] 2015-09-27 21:14
If your site URL looks like this:

http://example.com/~jsmith1/drupal/

Then you need to set RewriteBase! Find the section in your .htaccess file that looks like this:

  # Modify the RewriteBase if you are using Drupal in a subdirectory and
  # the rewrite rules are not working properly.
  #RewriteBase /drupal
And change the last line, like this:

  RewriteBase /~jsmith1/drupal
Make sure you remove the # symbol in front of RewriteBase, otherwise this will not work.

If you move your site later on, this line will need to be changed again. For example, if you later move it to: http://your-site-here.com/ then update the line to RewriteBase / (or just comment it out with a # in front).

VARIANT. When using an Alias, if your site URL looks like this:

http://example.com/YourAliasName/

Then you must change the last line as stated above, like this:

  RewriteBase /YourAliasName
2. Your .htaccess file didn't get uploaded at all. #

Check if the .htaccess file was actually uploaded. It should be in the directory where you uploaded Drupal (for example: /public_html/drupal/)

If the .htaccess file is missing, you need to upload it. If you accidentally deleted this file, just download Drupal again, and copy the new .htaccess file.

Make sure the file is only called .htaccess and not htaccess.txt or anything else. The .period .at .the .beginning is required.
This name usually means that the file will be invisible on folder listings on Unix-based systems so you might not always see it. If using an FTP client, you may have to configure it to 'show hidden files'. If listing on the commandline, you must ls -la to see it. This will be somewhat dependent on your OS.

3. Your .htaccess file is corrupt. #

The .htaccess file is very fussy, and only works if things are in a certain order. If you've tried to add password protection or to block image hotlinking (especially if you used cPanel or some other software to set that up), you've probably corrupted the file. The simple solution is to delete your corrupted .htaccess file, then upload the standard version that comes with Drupal.
Evidence of a broken htaccess file can usually be seen in the Apache logs. If you have access on the host, the logs may be at /var/log/apache2/error.log or some variation like that. If you are on a shared host, see your ISPs documentation or helpdesk.

4. Pager and other query strings don't work #

Make sure you have not modified the Apache rewrite rule. The default RewriteRule is:

RewriteRule ^(.*)$ index.php?q=$1 [L,QSA]
What this rule does is rewrite a path like example.com/node into example.com/index.php?q=node

However, you'd normally then expect that path like example.com/node?page=1 would be re-written into example.com/index.php?q=node?page=1 which would fail since both separators are ?.

However, the rewrite rule has additional flags. The 'L' flag is irrelevant, but 'QSA' makes the difference. What it does is to preserve any existing arguments after the rewrite, thereby changing the second '?' in this scenario into '&'.

**Comment by Data66PF** [comment] 2015-09-28 19:21
Please see the .htaccess I posted above as that is the correct one to use. It's working on all of my sites and on the client sites that have used that one that I posted.

**Comment by haisay** [comment] 2015-10-17 07:31
We hosted in LINUX server. 
Error Msg "The /.htaccess file seems to be missing our Rewrite rules or this server does not support Mod_Rewrite."

hosting company says "Mod_Rewrite" supports the server.

the file hosted in "public_html" folder.

V4.0.8

**Comment by pootato** [comment] 2015-10-17 10:14
For anyone having this problem, the following .htaccess will work:

    RewriteEngine On
    #RewriteBase /   
    RewriteCond %{REQUEST_FILENAME} !-f

    RewriteRule ^(file)/(.*) PF.Base/$1/$2

    RewriteRule ^static/ajax.php index.php
    RewriteRule ^themes/default/(.*) PF.Base/theme/default/$1
    RewriteRule ^(static|theme|module)/(.*) PF.Base/$1/$2
    RewriteRule ^(Apps|themes)/(.*) PF.Site/$1/$2

    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d

    RewriteRule ^(.*)$ index.php?q=$1 [L,QSA]
</IfModule>
# END PHPfox Rewrite


Notice the index.php line change - 
<b>RewriteRule ^(.*) index.php/$1</b>
to
<b>RewriteRule ^(.*)$ index.php?q=$1 [L,QSA]</b>

**Comment by t2nttn** [comment] 2015-10-19 02:16
Confirmed post shared by @pootato work fine .Other .htaccess don't work at my server.

**Comment by SpeakLife** [comment] 2015-10-19 17:21
Good news for my site. Once I upgraded to 4.0.9 then .haccess now works. So I now have short url enabled.

**Comment by haisay** [comment] 2015-10-20 14:44
<IfModule mod_rewrite.c>
RewriteEngine On
# RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(file)/(.*) PF.Base/$1/$2
RewriteRule ^static/ajax.php index.php
RewriteRule ^themes/default/(.*) PF.Base/theme/default/$1
RewriteRule ^(static|theme|module)/(.*) PF.Base/$1/$2
RewriteRule ^(Apps|themes)/(.*) PF.Site/$1/$2
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php?q=$1 [L,QSA]
</IfModule>

its solve my issue. short url working fine now. Thanks

**Comment by raviji** [comment] 2015-10-30 15:11
For me too not working on V4.0.9,
When i click Enable Short Url site ll be collapsed. Please help me out to fix this big issue.

**Comment by Data66PF** [comment] 2015-10-30 15:16
Did you use the ones from here that are working for others?

**Comment by raviji** [comment] 2015-10-30 15:18
I have tried all the way mentioned in this thread.

**Comment by Data66PF** [comment] 2015-10-30 15:20
Is your site upgraded? If so, another client had to do comment out these two lines like this
```
#RewriteRule ^(file)/(.) PF.Base/$1/$2
#RewriteRule ^static/ajax.php index.php
```
Just those two for sites upgraded from 3.8 and only some sites seem to need that done.

**Comment by Data66PF** [comment] 2015-10-30 15:23
There are too many clients having .htaccess issues with short urls so I'm marking this a bug for our developers to look at further, to see if we can make a better one.

**Comment by raviji** [comment] 2015-10-30 18:18
yes you are right. Then only our phpfox ll be in easy way to follow all. Also currently there is no to update customer logo in their way. That also i request phpfox take it as high priority to fix.

**Comment by Data66PF** [comment] 2015-10-30 18:48
Customer logo is uploaded in the theme area of admincp. Edit the theme and click to upload the logo. This issue is not for that though. Please don't ask questions about other issues in a topic that is not for that. Thanks.

**Comment by Data66PF** [comment] 2015-12-08 11:01
Please test with 4.1.1 and please make a new ticket if you find issues still.

**Closed by Data66PF** 2015-12-08 11:01 UTC
Labels: Bug, Cannot reproduce

**Comment by warain** [comment] 2016-03-23 14:58
First make sure you Enabling mod_rewrite: ssh into your server as root, add the below code

       $ sudo a2enmod rewrite

Restart Apache
       $ sudo service apache2 restart

Setting Up .htaccess, First, allow changes in the .htaccess file. Open the default Apache configuration file using nano or your favorite text editor.

      $ sudo nano /etc/apache2/sites-enabled/000-default.conf

Inside that file, you will find the <VirtualHost *:80> add the follow code: should look like this -->

<VirtualHost *:80>
       <Directory /var/www/html>
                   Options Indexes FollowSymLinks MultiViews
                   AllowOverride All
                   Order allow,deny
                   allow from all
       </Directory>
</VirtualHost>

Restart apache
     $ sudo service apache2 restart  

Create the /.htaccess file
    $ sudo nano /var/www/html/.htacces

Add the code below:

# START PHPfox Rewrite
    Options -Indexes
<IfModule mod_rewrite.c>
        RewriteEngine On
        RewriteBase /
        RewriteCond %{REQUEST_FILENAME} !-f

    RewriteRule ^(file)/(.*) PF.Base/$1/$2

    RewriteRule ^static/ajax.php index.php
        RewriteRule ^themes/default/(.*) PF.Base/theme/defa$
        RewriteRule ^(static|theme|module)/(.*) PF.Base/$1/$
        RewriteRule ^(Apps|themes)/(.*) PF.Site/$1/$2


        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d

        RewriteRule ^(.*) index.php/$1
</IfModule>
# END PHPfox Rewrite

Prevent other from writing to this 
       $ sudo chmod 644 /var/www/html/.htaccess
Log into your phpfox site --> setting --> short url --> push the button, you are set!
