### ISSUE TITLE
User unable to change password from his/her account settings.

### ISSUE THREAD

**Issue by Verdz** [moxi9/phpfox#221] opened 2015-07-26 14:30 UTC
User unable to change password from his/her account settings.
I have tried so many times with 3 other user accounts.

![passwordchange](https://cloud.githubusercontent.com/assets/13417524/8894353/6f382864-33bb-11e5-926b-bd5a19c55bdc.jpg)

**Comment by Data66PF** [comment] 2015-07-27 21:13
I cannot reproduce this with V4.0.3, on a win 8.1 pro machine with firefox browser.

**Comment by RaymondBenc** [comment] 2015-08-04 08:47
Fixed in >= 4.0.3

**Closed by RaymondBenc** 2015-08-04 08:47 UTC
Labels: cannot reproduce
