### ISSUE TITLE
Neutron 4.0.9 Cover Photo is not responsive and Profile photo bug

### ISSUE THREAD

**Issue by Rajsenior** [moxi9/phpfox#696] opened 2015-11-05 10:27 UTC
Hello 

The Cover Photo do not have any fix size, adjustment or setting to locate the view and while shrinking to mobile view its badly shrunk and lost the original look and feel ...  

On other hand Profile carries first two letters of the Members name which is also not placing right in the middle of avatar in both mobile and web view.

Please fix the bug 

Regards

**Comment by Data66PF** [comment] 2015-11-05 13:06
Please post only one issue per report. We will address the issue of the cover photo in this report as the other issue with the avatar was already posted in another issue.

What mobile device and browser are you testing?

**Comment by Rajsenior** [comment] 2015-11-05 13:11
tested on Web browsers .. i.e. Google Chrome, Mozilla, Safari and Opera 

tested on http://www.responsinator.com/ and tested on my iphone 5s and gionee both

**Comment by Data66PF** [comment] 2015-11-05 13:37
Do you have a link to a page/group you tested at the PHPfox community or a profile where you loaded a cover photo? If not, that's ok but it would help to see the same image you tested. Thank you!

**Comment by Rajsenior** [comment] 2015-11-05 13:54
Data66 you can upload any cover photo to your own profile in phpfox community  then take a look on it
by using your web browsers and look at it on your phone device ... you will see how it lose the shape of image ...

**Comment by aakash83** [comment] 2015-11-05 15:16
i can reproduce the second part (about avator) on iphone 6 using safari browser and in win 10 using chrome. the issue about cover photo needs testing. as i can see for some images it works fine.but some images it don't.

**Comment by Data66PF** [comment] 2015-11-05 15:40
The second part is not being addressed here as it is in another bug report so we are only addressing the cover image issue. We will test with the recommended size of 850 x 315.

**Comment by Rajsenior** [comment] 2015-11-05 15:45
Data we can not ask users to cut or crop their photos to 850x315 ... For a good portal its not nice the cover photo is shrinking like that and users are helpless or the admins are working day night to cut or crop cover photos manually for them... The cover photo should be responsive ... if phpfox team is helpless for that, then what I can say more now.

**Comment by Data66PF** [comment] 2015-11-05 16:20
It's not designed to crop photos though. It has always had a default size. If you mean that you want it to crop, then it won't do that. Same if they load a 150 x 150, it won't look good as it would be too pixelated. They need to load the right size. If googled for fb cover photo, they come up at the size that I recommended.

**Comment by Data66PF** [comment] 2015-11-06 11:47
We are looking at ways to improve this.

**Comment by Rajsenior** [comment] 2015-11-06 12:39
Data ... Thank you so much for keeping the topic up and looking sincerely for the way to improve.

**Comment by Data66PF** [comment] 2015-11-06 12:43
You're welcome. We were trying to keep the core bugs, for now, just to broken issues and not for enhancements until we got bugs down and then look at enhancing but we've made a lot of progress so can look at some enhancements. :)

**Comment by one44** [comment] 2015-11-22 04:29
I know it is strictly not a bug but has the cover image upload problem been fixed. It is an issue for members who upload images. It should have a routine that when add cover pic is clicked a message pops up that says image must be x by Y for best results and only allow images of a certain size to be uploaded.

**Comment by Gatsby-PF** [comment] 2015-12-14 23:14
I do not know if what I am seeing is the same as the creator of this post, but when going to mobile view using the android simulator in Firefox User Agent Switcher, the entire width or the cover image is compressed like an accordion, while the height remains unaffected.  Noting the css class that controls how this image is displayed in mobile view:

.profiles_banner .cover > img {:

and noting that background-image: cover;

contained therein is not supported by android according to this specification

http://www.w3schools.com/cssref/css3_pr_background-size.asp

When I see this horizintally compressed image, I think of the word bug, not enhancement.  It appears that the css is not adequately addressing mobile requirements for proper image display.

**Comment by neil96** [comment] 2016-01-05 16:15
Fixed on V4.2.0

**Closed** 2016-01-14 07:01 UTC
Labels: Enhancement, Fixed
