### ISSUE TITLE
Photo Albums

### ISSUE THREAD

**Issue by SpeakLife** [moxi9/phpfox#648] opened 2015-10-20 19:01 UTC
I noticed when I click on photos and I go at the top and select All Albums I get this where something is wrong with the albums.

![allalbums](https://cloud.githubusercontent.com/assets/11232020/10617886/ec8cbe98-773a-11e5-8f73-6a458ef3b21f.png)

I also had YouNetCo upgrade my mobile application and on their app when I go to photos it displays the thumbnail photos as blank white boxes. YouNetCo stated it was not their application but possibly with the phpfox thumbnails but being parsed correctly. 

I also noticed within all content of my site as far as blogs and profile posts and any text being posted, there were break codes in the content and coding showing the url path to the photo. I had to edit every blog and every content on my site and click on the update button for the system to remove the coding and post the photos and text with paragraphs in the blogs as normal.

**Comment by Data66PF** [comment] 2015-10-20 19:13
We take one issue per report. In regards to the photo albums, you show a much larger image than is the default. Have you edited your sizes? I cannot reproduce any issue in photo albums with default, unedited Neutron theme and no apps or modules added to the site. Also cannot reproduce at the forum. http://community.phpfox.com/photo/albums/

**Comment by SpeakLife** [comment] 2015-10-20 20:11
When I mentioned apps I was referring to the company younetco who created an Apple and Android mobile application of my site. On my android note 5 and iPhone 5s when you click on photos it shows blank square boxes 

Also while using the browser when I go to photos on my website the albums don't properly display. They use to on phpfox version 3.

**Comment by SpeakLife** [comment] 2015-10-20 20:12
Are you not being able to reproduce because your website was a fresh clean install of V4 verses an upgrade fromantic V3 to V4?

I believe I have the option enabled to auto resize images but I never had this issue with V3.

**Comment by Data66PF** [comment] 2015-10-20 20:19
Did you change image sizes at all? There are default image sizes. Did you change any of those?

**Comment by Data66PF** [comment] 2015-10-20 20:24
Tested on an upgraded site and still no issues seen. Your images does not look like the default size. This is what it should look like:
![photo albums all albums social networking community](https://cloud.githubusercontent.com/assets/6908282/10620047/09efc302-7747-11e5-81dd-f20e71f65ccb.png)

**Comment by Data66PF** [comment] 2015-10-20 20:26
Are you sure you are using default Neutron theme? Double check your photo sizes in photo settings too.
![admin cp manage settings social networking community](https://cloud.githubusercontent.com/assets/6908282/10620087/3f52dc0a-7747-11e5-8b7f-8c3f57a8dfb2.png)

**Comment by SpeakLife** [comment] 2015-10-20 21:16
Yes I'm using the default Neutron Theme. I don't touch the sizes of my photos. I upload them and the site takes care of the rest.

![photosizes](https://cloud.githubusercontent.com/assets/11232020/10621359/4d021d3c-774e-11e5-8198-1fdd74819445.png)

**Comment by SpeakLife** [comment] 2015-10-20 21:17
What do I have to do in order to have someone from phpfox log into my site and fix all my issues?

**Comment by Data66PF** [comment] 2015-10-20 22:26
That isn't something addressed in the issue tracker as this is only for script bugs. It seems like it is a site issue. Your screenshot of your albums, the theme is not the same as mine. Your theme looks different colors, different styling. Perhaps adjustments were made for your mobile app? I still suggest to make a development site with nothing on it except default. No mobile app, no other apps, no third party stuff added and see how it shows then.

**Comment by SpeakLife** [comment] 2015-10-20 23:05
It is the exact same theme I just changed the colors to it which has nothing to do with the functionality of the theme or site. I can't afford to pay for another license of phpfox and another server.

**Comment by Data66PF** [comment] 2015-10-21 08:42
The license terms allow you to install a development copy in the same server as your current site, on the same domain. Put it in a phpfoxdev or development subfolder and see how that works for you. It helps with testing for issues when you have a pristine copy of the script so you can see what could be a bug (something that is also in your development site) or what is a site issue (perhaps from settings, add ons, apps, themes, plugins, etc).

**Comment by Data66PF** [comment] 2015-11-20 14:07
Still unable to reproduce though all of our testing environments. Please upgrade to v4.1.0 when we release it next week.

**Closed by Data66PF** 2015-11-20 14:07 UTC
Labels: Cannot reproduce
