### ISSUE TITLE
Language pack issue

### ISSUE THREAD

**Issue by Foxgerman** [moxi9/phpfox#897] opened 2016-01-03 12:25 UTC
Hi, i try to import a language pack and have all phrases twice after search for new phrases.
Same issue if i try to create a new language pack from scratch from english.

Can anyone confirm please? Using 4.1.2(build 4)

![bildschirmfoto 2016-01-03 um 13 24 48](https://cloud.githubusercontent.com/assets/5095754/12078726/6e8b6eb8-b21d-11e5-98a4-45cd795911bd.png)

**Comment by Data66PF** [comment] 2016-01-03 17:47
I don't think I'm testing right. For my site, I have 3 language packs installed other than English. I clicked Find Missing Phrases and I don't  have duplicated phrases. I have one phrase for each phrase per pack. This is for apps installed from the apps store.

**Comment by Data66PF** [comment] 2016-01-04 09:34
Just letting our staff know that this is the German Language Pack developer. :) He's one of our most popular language pack developers.

**Comment by tamlalt** [comment] 2016-01-04 20:59
I've also found some duplicated phrases in the Default English Language Pack.

**Comment by Data66PF** [comment] 2016-01-05 12:48
Weird. I just can't reproduce this but I've not imported one. I tried making one and then clicked Find Missing Phrases and didn't have issues. For those that do, did you click the Maintenance >> Remove Duplicates?

**Comment by Foxgerman** [comment] 2016-01-05 16:56
Well, i have made a screencast for this. Feel free to download and check:
http://foxgerman.com/issues/language_issue_412.mp4.zip

**Comment by Data66PF** [comment] 2016-01-06 10:13
Confirmed as I now have about 7 duplicates for the phrase for facebook depreciated (was looking due to a bug for misspelled phrases). Remove duplicates does nothing for this.
![duplanguage](https://cloud.githubusercontent.com/assets/6908282/12140217/1143f586-b434-11e5-8bde-3926f3e74eb0.png)

**Comment by Foxgerman** [comment] 2016-01-24 21:43
So...4.2.0 is out and has the same issue on a fresh install. I was not able to work on our language pack to provide updates for clients not can i create a new pack since duplicated phrases. I can only ask the dev´s to work on this issue. Thanks.

**Comment by Spaninet** [comment] 2016-01-24 23:32
Same here.

**Comment by Data66PF** [comment] 2016-01-27 17:09
As we are still trying to nail down the issue with this, we will have to do a fix for 4.2.1. Sorry for the delay.

**Comment by Foxgerman** [comment] 2016-01-27 17:11
@Data66PF Thanks for let us know.

**Comment by Data66PF** [comment] 2016-01-27 17:13
You're welcome! :) We did try to get it done but we want to make sure something else doesn't break so more testing is warranted.

**Comment by Data66PF** [comment] 2016-02-10 11:46
We are having an issue finding a solution but are still working on this.

**Comment by RaymondBenc** [comment] 2016-02-17 16:14
Fixed in 4.3.0

**Closed by RaymondBenc** 2016-02-17 16:14 UTC
Labels: Bug, Developer
