### ISSUE TITLE
Ajax Problem

### ISSUE THREAD

**Issue by perayknox** [moxi9/phpfox#658] opened 2015-10-23 05:48 UTC
Some pages have some problems..

For example, Sometimes it does not go  to other page from one page.. I'm not sure but it was happen on forums too..  But when I delete the thread I added last, it fixed.,

It happening on photos module now.. I don't now why.. When I go to the photos, it's okay but when I go to the another page, it doesn't working until I refresh the page... 

Please fix it. This problem is also in other phpfox versions too. (3.x.x)

**Comment by perayknox** [comment] 2015-10-23 05:56
Interesting...

I clicked the "Home" link and it has loaded in photos module..

![2015-10-23_08-53-21](https://cloud.githubusercontent.com/assets/13890542/10685552/f11e7d90-7963-11e5-9769-ef628d5b8e17.png)

**Comment by SalmanKhan86** [comment] 2015-10-23 10:08
some times it occurs.having some problem with it.

**Comment by perayknox** [comment] 2015-10-30 11:30
Please fix it!!! This is everywhere!! Pof!

**Comment by perayknox** [comment] 2015-10-30 11:31
@Data66PF

**Comment by perayknox** [comment] 2015-10-30 12:08
I updated this with new informations!!!!!

https://github.com/moxi9/phpfox/issues/689

**Comment by perayknox** [comment] 2015-10-30 12:08
I updated this with new informations!!!!! @Data66PF 
https://github.com/moxi9/phpfox/issues/689

**Comment by Data66PF** [comment] 2015-11-07 17:30
Please keep all of the updates in this Open bug report as we don't want duplicates that can complicate things for us and make testing and fixing go much slower. Thank you.

**Comment by perayknox** [comment] 2015-11-07 17:32
I already told and I reported 6 bug. so I dont care anymore.

ASUS'umdan gönderildi.

-------- Orijinal Mesaj --------
Başlangıç:Data66 <notifications@github.com>
Gönderme:Sat, 07 Nov 2015 19:30:24 +0200
Bitiş:moxi9/phpfox <phpfox@noreply.github.com>
Bilgi:perayknox <eyup.c.elma@gmail.com>
Konu:Re: [phpfox] Ajax Problem (#658)

**Comment by Data66PF** [comment] 2015-11-07 18:36
Which other bugs? I'll look at them again if you link them. I didn't see them in your Github.

**Comment by Data66PF** [comment] 2015-11-07 18:39
I found your other bugs. 7 are still open, some of those are fixed already. The closed ones were either duplicates or feature requests. For the 7 open ones, we are still working on fixing the ones that were confirmed and testing the ones that are not confirmed yet.

**Comment by Data66PF** [comment] 2015-11-17 12:02
I installed the Turkish language pack to test and cannot reproduce this. Tested 4.0.10 using chrome on win 10

**Comment by Data66PF** [comment] 2015-12-08 10:43
Tested in 4.1.1 with Arabic language pack and I can reproduce this issue. We need to test with either the Arabic or Turkish language pack.

**Comment by perayknox** [comment] 2015-12-09 08:30
I was said.

2015-12-08 12:43 GMT+02:00 Data66 <notifications@github.com>:

**Comment by Data66PF** [comment] 2015-12-23 12:08
Tested in 4.1.2 with Turkish language pack and I cannot reproduce it. @perayknox please test with 4.1.2 and let us know if you can reproduce this.

**Comment by neil96** [comment] 2015-12-30 04:37
Relate with #461

**Comment by Data66PF** [comment] 2016-01-30 22:17
Is this resolved with 4.2 ? The related bug is confirmed fixed by the other client. Please let us know if your issue is now resolved with v4.2.

**Comment by perayknox** [comment] 2016-01-30 22:53
Yes, it's okay for now but I can't be sure.

**Closed** 2016-03-06 14:41 UTC
Labels: Bug
