### ISSUE TITLE
Responsive: like button does not work correctly in "Marketplace"

### ISSUE THREAD

**Issue by cleger80** [moxi9/phpfox#624] opened 2015-10-15 22:33 UTC
The like button square is not entirely clickable on mobile view.
![tets_ _social_networking_community](https://cloud.githubusercontent.com/assets/15106126/10529349/76152b24-739d-11e5-82bf-b039082ae551.jpg)

Tested on Chrome Version 46.0.2490.71

**Comment by Data66PF** [comment] 2015-10-16 10:39
duplicate of #598

**Closed by Data66PF** 2015-10-16 10:39 UTC
