### ISSUE TITLE
Pages Discussion Bug 2

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#737] opened 2015-11-19 15:50 UTC
Ver 4.0.10
Steps to reproduce 
Pages >> Discussions >> New Thread 
Post a thread and  go again to discussions  tab  select  the newly created thread using check box. A  blue button will appear at the bottom of Page . click on that button and click approve. The newly created thread will  disappear but  you can still see the check box as shown below.

![image](https://cloud.githubusercontent.com/assets/406030/11275278/33759a50-8edd-11e5-973f-27c132b04208.png)

Apart from checkbox  , this entry was already appearing on the page  so there was no need to approve it . Also  it was  posted by an admin.

**Comment by Data66PF** [comment] 2015-11-23 12:20
Cannot reproduce this in our 4.1.0 which will be released this week.

**Closed** 2015-12-23 12:36 UTC
Labels: Cannot reproduce
