### ISSUE TITLE
Incorrect formatting on Pages

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#733] opened 2015-11-19 15:19 UTC
Ver 4.0.10
If we dont have any events  and photos on any page then the message we get for photos  has incorrect placement.

![image](https://cloud.githubusercontent.com/assets/406030/11274485/54baa3e4-8ed9-11e5-8493-6b9fecd37d23.png)

**Comment by Data66PF** [comment] 2015-11-23 12:31
I can confirm the issue on v4.1.0 Neutron theme as shown.

I can see that in our v4.1.0 Bootstrap, the text is centered for Events but left justified for photos. 

We should look at making both themes show it aligned the same way.

**Comment by aakash83** [comment] 2015-11-29 11:46
Not Fixed in latest release.

**Comment by Data66PF** [comment] 2015-11-29 15:37
That's because we've not marked it as fixed. Please wait for that before posting. Thanks.

**Comment by Data66PF** [comment] 2015-12-04 11:50
Fixed in v4.1.1 *staff note YPFOXNEUTRON-222 *

**Closed by Data66PF** 2015-12-04 11:50 UTC
Labels: Bug
