### ISSUE TITLE
[Feed Comments] Forever "Loading"

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#329] opened 2015-08-11 14:21 UTC
When leaving a comment on someone's status in the activity feed, it will sometimes show a continuous loading circle without actually showing any indication the comment posted. Refreshing or going to the profile shows that it did, but without doing that, you would think you needed to stay and wait until it "finished".

**Comment by SalmanKhan86** [comment] 2015-08-12 03:20
Confirmed!Sometimes it occurs.

**Comment by Data66PF** [comment] 2015-08-13 10:10
Are you able to reproduce this today at the PF community? what browser and os? Just tested and it seems fixed as I had the issue before too with win 10, latest FF

**Comment by SalmanKhan86** [comment] 2015-08-13 10:14
i just tested it in PF community.Window 7 OS chrome and Mozilla same problem.
![comment problem](https://cloud.githubusercontent.com/assets/13433124/9247586/244c9c66-41d2-11e5-9841-46ef9c6d4cb2.png)

**Comment by Data66PF** [comment] 2015-08-13 10:19
I see a lag on that profile with adding a comment. It does add for me but there is a delay so I'll confirm this for further testing. I tested with win 10 on ff.

**Comment by RaymondBenc** [comment] 2015-08-25 08:36
Is it on any item on Emily Smith's profile?

The lag usually provided from a post is due to emails being sent out. Delaying emails to be sent out is something needed in this area.

**Comment by one44** [comment] 2015-08-25 12:28
This issue also arises when Photo from ver 3.8 or a deleted pic is looked for. Needs to sat no image found.

**Comment by RaymondBenc** [comment] 2015-09-03 12:52
When this happens, was a comment successfully posted at an earlier time successfully?

**Comment by SalmanKhan86** [comment] 2015-09-03 13:16
yes earlier comment was posted successfully. in a mean time its show loading image when we refresh comment posted in box.

**Comment by Data66PF** [comment] 2015-09-22 10:42
I'm still having this issue on anyone's profile at the community.

**Comment by neil96** [comment] 2016-01-05 16:00
Fixed on V4.2.0

**Closed** 2016-01-13 10:34 UTC
Labels: Bug, Fixed, Major
