### ISSUE TITLE
Htaccess issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#748] opened 2015-11-25 15:08 UTC
Please remove WWW from url and directories with htaccess.
Otherwise it's causing trouble of javascripts and ajaxs etc.

**Comment by Data66PF** [comment] 2015-11-27 13:00
are you having an issue with our v4.1.0 build2 release?

**Comment by Ylmzef** [comment] 2015-11-27 15:55
Yes.

**Comment by Data66PF** [comment] 2016-01-05 15:13
@neil96 can we have someone test this?

**Comment by Ylmzef** [comment] 2016-01-16 18:59
@neil96 @phpfoxdev @Vivian-phpFox @RaymondBenc @robert9592  can you fix this in v4.2.0 please?

**Comment by Data66PF** [comment] 2016-01-17 00:00
Again, please do not tag everyone

**Comment by neil96** [comment] 2016-01-27 15:49
Could you give us more information about this issue?

**Comment by Data66PF** [comment] 2016-02-18 15:22
I think this is an issue you need to resolve at the server to redirect www to non www or vice verse. This suggestion is in the forum already. I don't think this is a script bug.

**Comment by neil96** [comment] 2016-02-18 16:30
If when you install without www, but after install, your site url have www => I can't reproduce.
You can select your domain with www or without www, just change in config.

**Comment by Ylmzef** [comment] 2016-02-19 11:57
It's already without www but on first page the system not redirect to without www.

**Comment by Data66PF** [comment] 2016-02-19 13:22
https://community.phpfox.com/forum/thread/53970/login-not-working-v4-2/?view=332727 did you try the tips there? It worked for others.

**Comment by Ylmzef** [comment] 2016-02-20 22:43
I done it already but i post this as bug need fixed.

**Comment by Data66PF** [comment] 2016-02-24 09:56
@neil96  we have a ticket for this with details for log in from the other bug linked

**Comment by Data66PF** [comment] 2016-03-05 17:58
I'm able to confirm this now on my new demo site that was set to a www domain. I could not get log in to work until I added:
RewriteCond %{HTTP_HOST} ^www.(.)$ [NC]
RewriteRule ^(.)$ http://%1/$1 [R=301,L]

This site is on the same server as my non www dev site that our staff has access to. I think we should modify our htaccess code that shows in the admincp so that clients don't have this issue as they don't need to have to search for this fix just to use www sites.

**Comment by RaymondBenc** [comment] 2016-03-07 10:57
@Ylmzef we had provided a test patch on another clients site to resolve the issue. We are unsure if your issue is identical. Can you open a support ticket with us with FTP or SSH login details so we can apply the patch?

Thanks

**Comment by Ylmzef** [comment] 2016-03-07 19:29
@RaymondBenc 

I have fixed this self with htaccess rules.
I can wait untill release.

Thanks,

**Comment by RaymondBenc** [comment] 2016-03-08 10:25
Fixed in 4.3.0.

Note: New setting added in 4.3.0, which can be enabled from: AdminCP > Settings > URL Match

**Closed by RaymondBenc** 2016-03-08 10:25 UTC
Labels: Bug
