### ISSUE TITLE
Event Date will not change and end time appears but does not work

### ISSUE THREAD

**Issue by ASNLifestyle** [moxi9/phpfox#749] opened 2015-11-25 15:33 UTC
Submitted based Data66 recommendation for debug.

When editing an event it says it has updated but it does not. this did work prior to 4.0.10 and yes i have sync the theme cleared the cache everything I could think of.
Furthermore it shows an end time which it never did before. this is agitating my members as they have events that are giving the incorrect information.

I have noticed that when I hit update at bottom after I make my changes it says that I successfully invited guest. so its not updating at all. This is a problem.

(If you see the first pic shows that it is adding an end time but when you update it does not show an end time and it does not give the correct date that was selected)
![2015-11-19 9](https://cloud.githubusercontent.com/assets/14006326/11401193/55ff2e3e-935f-11e5-8ffb-37a4f6f01c19.png)
![2015-11-21](https://cloud.githubusercontent.com/assets/14006326/11401192/55fca5ba-935f-11e5-89e5-9539e2c37aa9.png)

**Comment by Data66PF** [comment] 2015-11-26 12:05
duplicate of #743 which seems fixed for our 4.1.0 release coming up.

**Closed by Data66PF** 2015-11-26 12:05 UTC
