### ISSUE TITLE
Suggestions block issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#644] opened 2015-10-20 02:01 UTC
Upgraded site
v4.0.9
Chrome v46
Windows 10

![naamloos](https://cloud.githubusercontent.com/assets/8562514/10595996/2c9f01be-76df-11e5-9f8f-1e9e803ee69e.png)

**Comment by Jinkers** [comment] 2015-10-20 03:15
Duplicate of #512

**Comment by Data66PF** [comment] 2015-10-20 10:33
Please search before posting. Thank you.

**Closed by Data66PF** 2015-10-20 10:33 UTC
Labels: Duplicate
