### ISSUE TITLE
Background Images Not showing up on Landing Page V4.2.1 (5)

### ISSUE THREAD

**Issue by ASNLifestyle** [moxi9/phpfox#1105] opened 2016-02-09 21:11 UTC
I'm having an issue with the background images on the landing page. When using Chrome, background image loads fine, but not in Firefox 43.0.4

I can't show you right now since I have it on my local computer.

But here are the screenshots:
Chrome
![2016-02-09 2](https://cloud.githubusercontent.com/assets/14006326/12930657/980f6f5e-cf47-11e5-866c-9122489d4baa.png)

Firefox
![2016-02-09 3](https://cloud.githubusercontent.com/assets/14006326/12930665/9fa0074c-cf47-11e5-8ca4-c1392d0824b3.png)

**Comment by Data66PF** [comment] 2016-02-09 23:16
I cannot reproduce this in v4.2.1 build 5 on firefox.

**Comment by ASNLifestyle** [comment] 2016-02-10 18:20
Well I get it another developer gets it so what would be the solution then?

**Comment by Data66PF** [comment] 2016-02-10 21:04
https://v4.phpfox.com can you see the background at that site? If not, please give more info about what you are using to test with. Please try disabling browser extensions and plugins in case they are interfering also.

**Comment by mobicomfi** [comment] 2016-02-11 08:51
Hi,

I have same problem in all browsers :) i try to load my site in edge, firefox, chrome, opera and no backround photo. I use bootstrap theme and uploaded 5 different photo file to homapage backround field, but nothing. And demo site shows fine to me.

**Comment by Data66PF** [comment] 2016-02-11 19:21
@mobicomfi make sure you have not disabled the registration block or disabled registration. There is a separate bug report for that already.

**Comment by mobicomfi** [comment] 2016-02-15 08:15
Hi.

No i dont havent disable anything. 

Chrome
![chrome](https://cloud.githubusercontent.com/assets/13621606/13042858/7e8e7726-d3cc-11e5-84af-b089c37c48b7.PNG)

Edge
![edge](https://cloud.githubusercontent.com/assets/13621606/13042857/7e8c3312-d3cc-11e5-99be-2575cb166c7b.PNG)

Firefox
![firefox](https://cloud.githubusercontent.com/assets/13621606/13042859/7e9068ce-d3cc-11e5-98f5-b5545891699f.PNG)

Opera
![opera](https://cloud.githubusercontent.com/assets/13621606/13042860/7e91bae4-d3cc-11e5-9865-593616424dc0.PNG)

all browsers dont show banner

i have uploaded banner to admin side
![banner](https://cloud.githubusercontent.com/assets/13621606/13042910/f1c89244-d3cc-11e5-9802-2eff44a04584.PNG)

**Comment by Data66PF** [comment] 2016-02-15 12:44
Did you make sure to do that on a clone of bootstrap and not on the default bootstrap?

**Comment by mobicomfi** [comment] 2016-02-16 08:01
no, its default, why i need clone?

**Comment by Data66PF** [comment] 2016-02-16 13:00
As default shouldn't be edited, it might be best to test it with a clone of the default instead.

**Comment by mobicomfi** [comment] 2016-02-17 10:25
i tried to with clone too, but still same problem

**Comment by neil96** [comment] 2016-03-04 04:24
I have some improve this feature on 4.3. After 4.3 release, please upgrade and tell me if it don't work.

**Comment by mobicomfi** [comment] 2016-03-16 06:22
Hi

I upgraded to latest 4.3b4, but still i dont get backround photos. I tried delete theme and make newone, but nothing. It upload photos to server, because i see it in server, but no show up in homepage. Is there possibility, that its server fault or what

**Comment by neil96** [comment] 2016-03-16 06:45
Please submit a ticket with your site information, I will check for you.

**Comment by Data66PF** [comment] 2016-03-16 15:52
https://clients.phpfox.com/ client area to submit ticket. Just log in and you'll see where to send the ticket. Thanks!

**Comment by mobicomfi** [comment] 2016-03-16 16:40
hi,

thanks, i open ticket already :)

**Comment by neil96** [comment] 2016-03-17 03:51
The issue fixed on client site.

**Closed by neil96** 2016-03-17 03:51 UTC
Labels: Cannot reproduce
