### ISSUE TITLE
Users cannot send each other messages

### ISSUE THREAD

**Issue by Scot74** [moxi9/phpfox#447] opened 2015-08-30 04:20 UTC
Version 4.07
Upgraded from 3.8+
Latest Internet Explorer and Google Chrome

Users receive emails with the content of the message but NOTHING shows up in anyone's message inbox even though it says it sent.

Please help.

**Comment by Data66PF** [comment] 2015-08-31 12:58
Did you test at the phpfox community? http://community.phpfox.com .

**Comment by Scot74** [comment] 2015-09-02 01:35
I'm not interested in that community. If it works there it is irrelevant. Why doesn't it send on our site? Are there settings that could disable it?

**Comment by Scot74** [comment] 2015-09-03 15:08
Hello? What setting could cause it not to send or receive at all? It is simply absurd.

**Comment by Data66PF** [comment] 2015-09-03 15:16
Testing at the community is our way of seeing, in a more controlled environment, whether your issue is reproduced as you are attempting it. This way, if you can reproduce it, you can give us more of a clue as to your steps as we can also check our live site to see what is happening. It is very relevant in the process as we cannot reproduce this in our community or our testing sites as you have described it, leaving us to deduce that it is an issue with your site (perhaps you are not using the recommended Mandrill for site transactional mail for example).

**Comment by Scot74** [comment] 2015-09-03 16:39
I need information on how to set up Mandrill for "site transactional" mail. Is that what you call messaging?That is what I need fixed.

**Comment by Scot74** [comment] 2015-09-03 16:42
To be clear, it was fine BEFORE the upgrade to neutron.

**Comment by Data66PF** [comment] 2015-09-03 18:13
http://scripttechs.com/article/318/using-mandrill-for-site-mail-with-phpfox/
http://scripttechs.com/article/293/using-mandrill-for-your-site-transactional-mail/

I have two there as some clients needed extra help. I'm not seeing any issues with mail sending on any test sites even without using mandrill but the PHPfox community does use a mail service and I don't recall if it's mandrill or sendgrid.

**Comment by Scot74** [comment] 2015-09-05 02:46
Why in the world does internal messaging within the phpfox network require a third party application? That is crazy. More importantly, why did the messaging cease to work with the transition from v3.8 to v4? It worked fine before? We haven't changed anything.

Are you able to look at our settings?

Thanks.

**Comment by Data66PF** [comment] 2015-09-05 08:59
I was under the impression that you meant it wasn't sending notifications to their email inbox of the message on the site. So what you are saying is that the PM (private message) is not getting from one user to the other one? It doesn't even send when clicked to send or it sends but never arrives in the PM inbox of the other user? You see it in the database? You don't see any new messages in the database? 

You enabled debug? Did you test with developer browser console open and try sending a PM? This issue is not seen on the community or any of my testing sites so we need to narrow down the issue and see if it is a bug or not. I think it is an issue with your site as no one else has mentioned this yet.

**Comment by Scot74** [comment] 2015-09-06 00:30
"So what you are saying is that the PM (private message) is not getting from one user to the other one?"

Yes.

"It doesn't even send when clicked to send or it sends but never arrives in the PM inbox of the other user?"

The popup box says it sent but it sends but never arrives in the PM inbox of the other user?"

"You see it in the database? You don't see any new messages in the database?"

I don't know how to check that. I am kind of scared I will mess something up.

"You enabled debug?"

I will if you tell me how but I don't know what it will do.

"Did you test with developer browser console open and try sending a PM?"

I don't know anything about that but am willing to do whatever you tell me in order to help fix it.

"I think it is an issue with your site as no one else has mentioned this yet."

Nothing has been changed on our end apart from the upgrade to v4 neutron. It has always worked from the time that I bought version 3 until the upgrade.

**Comment by Data66PF** [comment] 2015-09-06 09:45
just made a tutorial for enabling debug, http://scripttechs.com/article/364/v4-enabling-debug/ 

Note that V4 has new requirements and some things on the server can interfere with operation of things in it that worked in v3. Is the server php 5.4 at least? If mysql strict mode is enabled, it can cause issues. Mod_sec can interfere with things and need to be tweaked by the server folks. There are different things that can cause issues especially if the server hasn't been updated in a while.

As for developer browser console, tutorial is here for how to use it, http://scripttechs.com/article/274/debugging-with-developer-browser-console/

**Comment by Scot74** [comment] 2015-09-08 00:49
What should I be looking for as it pertains to the broken messaging feature. BTW, I am able to confirm we are using the latest version of php 5.4.

**Comment by Data66PF** [comment] 2015-09-10 13:26
Just look for any errors that show on the site when you try. Look for any errors that show in developer browser console in the network and console tabs there. It should show something but I don't see any other clients with this or any test sites with it.

**Comment by Scot74** [comment] 2015-09-11 23:21
It is as I expected. This came from our server support.

----------
 I have also checked the server logs and have not noticed any errors related to Mod_Sec.

I was able to reach the window where it says that "the message was successfully sent". However, I believe that this is an entirely developer related issue with the application. Should you need any other assistance, please do not hesitate to contact us again.
-----------

**Comment by Scot74** [comment] 2015-09-11 23:31
I noticed that when I click on the link under "To reply to this message, follow the link below" found in the email notification that "so and so sent you a message" it *does* take me to the message. Of course, there was never a notification and nothing shows up underneath "Messages" or "Notifications" on the main menu.

**Comment by lordofnos** [comment] 2015-09-12 12:50
for me the problem was solved by enabling the option "Threaded Mail Conversation"

**Comment by Data66PF** [comment] 2015-09-12 13:18
Yes, v4 uses only threaded mail I believe.

**Comment by Scot74** [comment] 2015-09-13 00:41
lordofnos, thanks...that was it

Data66PF,|
Where are all the options for sorting mail? For instance, "Inbox", "Sent", "Trash", etc...

I don't see anything at all. Also, when clicking on the notification for a message nothing happens. The notification just stays there and never takes you to the message itself.

**Comment by Data66PF** [comment] 2015-09-15 17:00
As the issue is resolved by enabling threaded mail, the original bug is closed. 

The issue for the missing buttons https://github.com/moxi9/phpfox/issues/366 wait for v4.0.8 and see if things work better.

**Comment by Data66PF** [comment] 2015-11-25 10:28
Reopened as we need to fix this for upgrade sites. The threaded mail is required but if a site does not have it set, the setting must ensure to be changed for them so they don't have issues such as this thread shows, http://community.phpfox.com/forum/thread/53248/messages-not-working/?view=328001 as the steps to fix the issue are too many for clients to find easily.

**Comment by robert9592** [comment] 2015-12-02 07:17
Fixed for v4.1.1

**Comment by Data66PF** [comment] 2015-12-04 12:02
Fixed in v4.1.1 *staff note YPFOXNEUTRON-229 *

**Closed by Data66PF** 2015-12-04 12:02 UTC
Labels: Bug, Fixed
