### ISSUE TITLE
Claim Page button missing

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#964] opened 2016-01-19 00:46 UTC
Admin and claim buttons missing

**Comment by Data66PF** [comment] 2016-01-19 09:31
Is this a duplicate of your #966

**Comment by Data66PF** [comment] 2016-01-19 09:46
Please be sure to make the titles descriptive. I'm changing them.

**Comment by one44** [comment] 2016-01-19 14:46
Sorry was half asleep

**Closed** 2016-01-20 11:30 UTC
Labels: Duplicate
