### ISSUE TITLE
Phpfox V4 missing phases

### ISSUE THREAD

**Issue by fluvial** [moxi9/phpfox#226] opened 2015-07-27 21:41 UTC
V4 have missing phase for translate to other languages on the vertical menu from the adminCP.
Can you confirme this.

Thank you

**Comment by leandrotavaresrocha** [comment] 2015-07-30 02:26
I noticed the same problem with the menus under "view profile".

**Comment by leandrotavaresrocha** [comment] 2015-08-06 02:02
The "pages" under the left menu also seems to be a hardcoded and not a phrase_var

**Comment by Jinkers** [comment] 2015-08-06 04:47
The menu on the left is mostly (if not all) composed of links. You need to manually edit those in the menu settings to be able to change the words.

**Comment by leandrotavaresrocha** [comment] 2015-08-08 21:50
I know but the "pages" block at the left menu bottom seems not to be a normal link. I looked at background and couldnt find the page menu.

**Comment by Data66PF** [comment] 2015-08-26 12:27
Confirmed that the Pages menu link does not use the language phrase for it.

**Comment by Foxgerman** [comment] 2015-09-24 11:45
Can confirm this too, hardcoded phrases in form2.html.php

![bildschirmfoto 2015-09-24 um 13 43 52](https://cloud.githubusercontent.com/assets/5095754/10072496/767ea9e6-62c2-11e5-9b2f-692f3182121e.png)

**Comment by piramidesoft** [comment] 2015-09-30 16:36
Frontend
========
"What's up?", "No new friend requests", "No new notifications","No new messages"
On user filter:  "From:", "To:", "View Advanced Filters", "SEARCH"
On add new photo: "Select photos(s)"
On forum: "Search...","Discussions","Recent Discussions","Search this forum...","Recent Posts", "Your reply..." (on add new thread)
On event: "ATTENDING" (sidebar)
On pages: "Name" (on add), all the heade meno of a "page"
On profile: header menu

**Comment by srikumar101** [comment] 2015-12-10 01:34
Dear Team, Just curious to know in which release or patch this issue is expected to be resolved as this is long pending.

**Comment by neil96** [comment] 2015-12-21 04:57
fixed on 4.1.2

**Closed** 2015-12-21 08:46 UTC
Labels: Bug, Fixed, Major
