### ISSUE TITLE
issues in Javascript in blocks

### ISSUE THREAD

**Issue by rn2020** [moxi9/phpfox#914] opened 2016-01-06 13:28 UTC
Hi , if we use any tags of Javascript in blocks . like third part tag ad from ad network and we insert it in the block to show it , like block 3 in pages or photos or home , than we will face issues when we loaded the page from insde the phpfox but if we come direct to the page link it will show ok , but if you click from insde the network than it will stay long time to open and when it open it change the themes and display the code banner like adsense , than if you refresh the page it back ok ,,,,,

this important issues should be solved

**Comment by Data66PF** [comment] 2016-01-06 15:11
Duplicate of #902 please search before posting.

**Comment by Data66PF** [comment] 2016-01-07 20:31
Please provide an example of what you are trying to add and note that some things need to follow the javascript tutorials but google adsense seems to be working fine for me.

**Comment by rn2020** [comment] 2016-01-07 23:51
HI Darta66PF 

The issues now is that . 

when you use Iframe tag  code it work ok and great but if you have JAVA SCRIPT tag ads it will work but with alot of issues the ads will show there or the content of the javascript but it will break the site , as i think there is issues with theme and CMS 

ok you can test it by your self , blow is normal javascript code try to show it in pages.view 
and go to this pages.view not from the direct link , it should be go from insde your network so open 
domain/pages/   and click any page there for user and see what happend ,
you will see one of this isuees 
1-may you see the content of the javasrcipt and not see the site , than refresh the site and you see evrything back ok 
2- may you wil see the site but with break theme  and not see the ads , than refresh the site and you will see evrything is ok 

this issues is happend in all model event ,pages , profile , and home 

[code]

<script language="JavaScript" type="text/javascript">

</script>

[/code]


pleas test the code above and you will understand 

this issues will make alot of bad things in the site 
pleas let them fix it fast 

Best

**Comment by rn2020** [comment] 2016-01-07 23:51
<script language="JavaScript" type="text/javascript">

</script>

**Comment by rn2020** [comment] 2016-01-07 23:55
otherwise this issues is not for HTTPS or HTTP i test them in alot of things by Request in HTTPS and HTTP and also in devloping verstion setup not in ssl and nt work make same issues in all the verstions

**Comment by rn2020** [comment] 2016-01-07 23:55
i hop you not close the issues and let them fix it they will understand i am sure

**Comment by Data66PF** [comment] 2016-01-08 11:28
@neil96 please test or have someone test a javascript ad or block and please navigate the site when testing. Please put the javascript in a sitewide block as though it is an ad.

**Comment by neil96** [comment] 2016-01-08 11:37
@rn2020 Could you give us example js code. I try with my code but it work well.

**Comment by Gatsby-PF** [comment] 2016-01-08 16:31
"otherwise this issues is not for HTTPS or HTTP i test them in alot of things by Request in HTTPS and HTTP and also in devloping verstion setup not in ssl and nt work make same issues in all the verstions"

Well not exactly, from a server standpoint maybe, but browsers, especially Firefox has major problems on https sites when the javascript attempts to connect to non http urls. It gets worse with every new release.

**Comment by Data66PF** [comment] 2016-01-09 15:51
I have tested again a sitewide javascript block. This is one of my favorite tools and uses javascript, https://clicky.com . Sign up for a free account and get the code. Put it in a sitewide block and verify the code works. Navigate the site and I see no issues with navigation in 4.1.2. Checking Clicky stats and the widget is working fine and reporting all the stats I expect to see.

I cannot reproduce any issues at this time.
![clicky1](https://cloud.githubusercontent.com/assets/6908282/12216907/8a20e50e-b6be-11e5-9cab-d954bf44bcfe.png)
![clicky2](https://cloud.githubusercontent.com/assets/6908282/12216919/e32904ec-b6be-11e5-9348-29c7d314f64d.png)

**Comment by neil96** [comment] 2016-01-27 16:00
Could you give us more information to reproduce this issue?

**Comment by rn2020** [comment] 2016-01-27 16:51
ok i had also test to setup the phpfox v4.2 in another server and not https  and the issues same 

, the issues is like that , when you show the JS in any block in any module 

like we show the js code in user profile view in block 3 and you click from insde the site to go to one of user profile , you will see only blank page open and only show the JS ,but if you refresh it it will back to work ok and you can see the profile ,,,,and there is no issues if you direct from browser to the user profile , the issues it come when you go to the user profile from insde the site like you click in the user name to go to his profile ....


this issues happend in all pages in phpfox not only in profile ,,,  

but for google ads code it work but it dmge the page 

the issues not has in the index in modeuls it has in the view.php in all modules 

for JS you can test any js , even the sample on it have the issues ,,,

this issues if not solve it will has big problem with alot of users ,,, 
as for me i tried to use Ifram as iframe work ok but JS not work ,,,

tes and you will understand , but test in show it in view.php  and try to go to view.php page from insde the phpfox

**Comment by neil96** [comment] 2016-03-07 04:36
I think the root cause is the same with #949. Please try again with behavior block as below example.

```
$Behavior.unique_name_here = function(){
//your code here
};
```

**Comment by Data66PF** [comment] 2016-03-08 12:18
@neil96 if we don't have a tutorial, please make one and please link it here and close this if it works fine. thank you :)

**Comment by rn2020** [comment] 2016-03-08 21:26
Hi Neil
this right it solve the issues but only for adsense but , you can try this code it is from another ad network 

<script type="text/javascript"></script>
<noscript>
<iframe src="https://ad.raaao.com/show.php?z=61,29,58,65" width="300" height="250" marginwidth="0" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no"></iframe>
</noscript>



it will not work , will show only the banner if you back from page with one lock only 

could you tell me what you have to add  to it to make it work

**Comment by rn2020** [comment] 2016-03-08 21:29
Hi Neil
this right it solve the issues but only for adsense but , you can try this
code it is from another ad network


`<script type="text/javascript"></script>
<noscript>
<iframe src="https://ad.raaao.com/show.php?z=61,29,58,65" width="300"
height="250" marginwidth="0" marginheight="0" hspace="0" vspace="0"
frameborder="0" scrolling="no"></iframe>
</noscript>`


it will not work , will show only the banner if you back from page with one
lock only

could you tell me what you have to add  to it to make it work

**Comment by neil96** [comment] 2016-04-01 06:43
From 4.4, We add a setting allow admin can turn off/on full ajax mode. In this case, you should turn off full ajax mode. These scripts don't compatible with full ajax mode.

**Closed by neil96** 2016-04-01 06:43 UTC
Labels: Cannot reproduce, Help wanted

**Comment by spirogg** [comment] 2018-07-19 22:00
@neil96 is this still an issue with latest version of phpfox. 4.6.1.b4 ??
