### ISSUE TITLE
Menu Word Space Problem in Small Screen Size

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#745] opened 2015-11-23 13:24 UTC
when i add or edit new Menu item ex: Market Place.then item name not appear properly.when i remove space in between them then its looks fine.Problem in space between them. Second word after space appear under same menu icon.
Tested it V4.0.10 With Chrome browser 

![menu space bug](https://cloud.githubusercontent.com/assets/13433124/11337494/75dfb55e-9213-11e5-96a9-3bc3182e7cb6.png)

**Comment by Data66PF** [comment] 2015-11-23 15:08
I'll test this on 4.1.0.

**Comment by Data66PF** [comment] 2015-11-25 11:26
I can't reproduce this in 4.1.0 testing as the menus are in a little tab now and I can't get them to show like that if using a Droid emulator. Will have to test on a live site once 4.1.0 is released as stable.

**Comment by Data66PF** [comment] 2015-11-27 13:06
Tested with v4.1.0 build 2 using iPhone with both neutron and bootstrap themes. Cannot reproduce with the new menu look.

**Comment by SalmanKhan86** [comment] 2015-12-11 09:27
i am facing same problem in Menu word space with iPad mini. i put space between Market Place after that it breaks in menu
pls check and resolve this issue
![menu problem](https://cloud.githubusercontent.com/assets/13433124/11740276/62760e16-a017-11e5-9000-b9a99cf78d3c.png)

**Comment by Data66PF** [comment] 2015-12-11 11:36
Did you follow all of the post upgrade steps? Mine doesn't look like that as my menus are in a little tab on Neutron theme. Is that an unedited Neutron theme?

**Comment by SalmanKhan86** [comment] 2015-12-11 11:43
i fresh install v 4.1.1 and does't make any changes with Neutron theme

**Comment by Data66PF** [comment] 2015-12-11 12:28
I'll have to test another install then. My menu is a button to click and that opens. Note that on the emulators, those are not working for my tests so I have to use the actual iPhone I have. I do have an old droid I can try testing with too.

**Comment by Data66PF** [comment] 2015-12-23 12:45
Can you still reproduce this in 4.1.2?

**Comment by SalmanKhan86** [comment] 2015-12-24 04:14
yes still present in 4.1.2. i test it same issue is there

**Comment by Data66PF** [comment] 2015-12-28 12:17
Now that our live demo is upgraded, can you reproduce the issue there? http://v4.phpfox.com

**Comment by neil96** [comment] 2015-12-28 16:13
Can't reproduce on 4.1.2.
![745](https://cloud.githubusercontent.com/assets/15936115/12021351/8f28f316-adb8-11e5-9558-99e6aba9a5ef.png)

**Closed** 2016-01-05 16:28 UTC
Labels: Cannot reproduce
