### ISSUE TITLE
Registration dialog remains for others to use after user logs off an invite only system.

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#810] opened 2015-12-11 01:10 UTC
Invite only site. Issue discovered using Firefox 42.

After new users sign up, log on and log off after a while, the registration dialog occasionally stays in the the visitors screen, even though it is an invite only site. This could allow others to register without being invited such as if the machine were in busy site such as a business.  

I caught it again and decided to register as a new user.  It let me go through the process, but when submitted a red notice was displayed "Cannot find a matching invitation" so did not net me sign up.

The registration form should still not be retentive after invited logs out.

**Comment by Data66PF** [comment] 2015-12-11 11:19
Have you cleared browser cache for your testing? Noting that in most cases, this would not be any issue since other users would be at other IP addresses, locations, etc and would have not gotten the registration stuff in the browser cache in order to see it? 

Are you able to reproduce this just by visiting the site without having tried the sign up/log on/ log off?

**Comment by Gatsby-PF** [comment] 2015-12-11 17:10
This issue does not exist when visiting the site, but rather under two conditions:

1. after logging out, or after logging out and 
2. leaving the site after logging off to find registration form still there, and revisiting it again.

**Comment by Data66PF** [comment] 2015-12-13 09:58
This has always done this due to browser cache. I'll bug it to see what a core developer determines for it - whether it can be fixed or if it is working as designed.

**Comment by robert9592** [comment] 2015-12-14 11:26
Fixed in v4.1.2

**Closed** 2015-12-21 05:02 UTC
Labels: Bug, Fixed
