### ISSUE TITLE
Branding Shows in Browser Tab

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#1134] opened 2016-02-16 14:46 UTC
According to a thread at the forum and two clients, the branding still shows in 4.2.2. I can confirm this on my test site with bootstrap on firefox browser and a Mac. We used to have a setting in the site settings to set that title but it appears not to be working or not used.

To reproduce, don't test on the core.index-member. Instead, go to blogs or something and then hover the mouse over the browser tab.
![branding](https://cloud.githubusercontent.com/assets/6908282/13079397/059b8162-d492-11e5-862f-00a274b50558.png)
![site title](https://cloud.githubusercontent.com/assets/6908282/13079428/2695758a-d492-11e5-9437-5ae00d9c6d6c.png)

**Comment by wlongdonstudio** [comment] 2016-02-16 15:00
thank you

**Comment by PhpFoxJohnJr** [comment] 2016-02-16 15:17
https://github.com/moxi9/phpfox/issues/86

**Comment by neil96** [comment] 2016-02-16 15:27
The phrase "Powered by PHPfox" only display in front-end if you use developer license (techie). It don't display if you use valid key.

**Comment by Data66PF** [comment] 2016-02-16 15:28
My live developer site is using a client license

**Comment by Data66PF** [comment] 2016-02-16 15:29
You can check it if you need as you have access. It has always used a client license. Paid.

**Comment by neil96** [comment] 2016-02-16 15:31
I can't reproduce this issue. Could you give me your demo url.

**Comment by Data66PF** [comment] 2016-02-16 15:31
The team has it :) I'll post in our chat.

**Comment by PhpFoxJohnJr** [comment] 2016-02-16 16:09
Does it show in anything else beside blogs as I disabled blogs?  But I didn't see it under forum or pages.  Just trying to help.

**Comment by Data66PF** [comment] 2016-02-16 16:11
He's found the issue and is finding a resolution :) yes it would be any edited page that was edited before but he can explain it better

**Comment by neil96** [comment] 2016-02-16 16:22
Fixed on V4.3.0.
@PhpFoxJohnJr if you can't wait to next version, please comment for me on community.

**Comment by PhpFoxJohnJr** [comment] 2016-02-16 16:31
I can wait...I just want to help as we are back over 100 issues again and I know you guys must be swamped.  So anytime you want me to check if I have the same issue just message me on scripttechs under johnjr or ask data to contact me.

**Comment by Data66PF** [comment] 2016-02-16 16:40
Thanks @PhpFoxJohnJr  if you click enhancements in the labels, you will see many in this tracker are not bugs. We only have a small list of actual bugs but we'll resolve the issue of features when we open that area so that the bug list is a true representation of bugs (broken script) and not features (things wanted to improve)

**Comment by wlongdonstudio** [comment] 2016-02-16 18:24
you guys need help? i'm available..

**Comment by Data66PF** [comment] 2016-02-16 23:31
thanks for the offer @wlongdonstudio  we can always use volunteer help testing bugs and stuff. some are even marked Help Wanted :)

**Closed** 2016-03-03 10:58 UTC
Labels: Bug, Fixed
