### ISSUE TITLE
Friend request issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#784] opened 2015-12-07 22:18 UTC
I have still thish issue. https://github.com/moxi9/phpfox/issues/406
I see still ""Pending Friend Request"" on user profile
I cleared cache and updated counters.

**Comment by Data66PF** [comment] 2015-12-08 11:04
Cannot reproduce for new pending requests. Please ensure you closed out the old ones (removed them).

**Comment by Ylmzef** [comment] 2015-12-09 00:21
It's about old requests.

**Comment by Data66PF** [comment] 2015-12-09 13:53
You need to clear out the old ones manually.

**Comment by Ylmzef** [comment] 2015-12-09 18:14
There no information about that.

**Comment by Data66PF** [comment] 2015-12-09 20:07
".... click the x in the lower right corner of the profile pic when viewing the pending and click to remove it" is how to remove the old ones.

**Comment by Ylmzef** [comment] 2015-12-10 01:23
I see this "There are no pending friends requests." on /friend/pending/ page.
But on user profile i see "Pending Friend Request" message on user profile page.

**Comment by neil96** [comment] 2015-12-10 01:40
On V3, we have this setting: "friend.hide_denied_requests_from_pending_list". If enabled, friend requests that were denied will be hidden from the Pending Friend Requests list. I think I will bring back this setting for admin can choose.

**Comment by Ylmzef** [comment] 2015-12-10 04:24
What is solution for currenlty?

**Comment by Data66PF** [comment] 2015-12-10 13:45
You would want to wait for us to release the fix.

**Comment by neil96** [comment] 2015-12-17 07:13
We bring back this setting: "Hide denied requests from pending list" on 4.1.2
To view this setting, go to: admincp->settings->modules->friends

**Comment by Vivian-phpFox** [comment] 2015-12-21 04:27
Fixed in V4.1.2

**Closed by Vivian-phpFox** 2015-12-21 04:27 UTC
Labels: Bug, Fixed

**Comment by Ylmzef** [comment] 2015-12-23 12:21
I enabled it but the friend requests still showing on profile as "Pending Friend Request
"

**Comment by Data66PF** [comment] 2015-12-23 13:24
Please open a new bug report for the issue as closed issues need a new bug report and I'll confirm the  issue for the new report.
