### ISSUE TITLE
Responsive: Profile avatar is cropped

### ISSUE THREAD

**Issue by cleger80** [moxi9/phpfox#622] opened 2015-10-15 22:27 UTC
Tested on Chrome Version 46.0.2490.71
![john_and_i_in_greece__ _social_networking_community](https://cloud.githubusercontent.com/assets/15106126/10529273/ad347174-739c-11e5-92ff-d8c3cf9a625f.jpg)

**Comment by Data66PF** [comment] 2015-10-16 09:43
Please state the device you are testing. Please don't test by resizing your browser window as responsive doesn't work like that.

**Comment by Data66PF** [comment] 2015-10-16 10:40
Cannot reproduce on iPhone 5c at community

**Comment by t2nttn** [comment] 2015-10-16 10:47
Please test with account without profile image.

**Comment by Data66PF** [comment] 2015-10-16 11:13
I did. I viewed a few profiles that had no images. Please state better instructions when posting bug reports so we can test exact steps.

**Comment by phpfoxdev** [comment] 2015-10-26 10:13
Fixed, will be released in next version

**Comment by Data66PF** [comment] 2015-11-13 12:27
Fixed in v4.0.10 *staff note YPFOXNEUTRON-73 *

**Closed by Data66PF** 2015-11-13 12:27 UTC
Labels: Bug, Cannot reproduce, Fixed
