### ISSUE TITLE
Re: Friend request issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#881] opened 2015-12-26 01:57 UTC
I see still "Pending Friend Request" on user profile page.
But there no request on /friend/pending/ page.
I want add the user as friend but there no button for it.

https://github.com/moxi9/phpfox/issues/784

**Comment by Vivian-phpFox** [comment] 2015-12-26 17:27
Sample:
User A sent a friend request to User B
User B denied request from user A
Rule:
1. If setting from ACP "Hide denied requests from pending list" = "Yes" then
User A can not send friend request to User B
2. If setting from ACP "Hide denied requests from pending list" = "No" then
User A can send fiend request to User B again after removed this request from pending request (/friend/pending/)

**Comment by Ylmzef** [comment] 2015-12-27 01:35
The issue comming from v4.0.5 there no option for old request.
I want to add the user again as freind but i can't do that.

**Comment by neil96** [comment] 2015-12-28 04:31
On #784 I commented:
>We bring back this setting: "Hide denied requests from pending list" on 4.1.2
>To view this setting, go to: admincp->settings->modules->friends
Did you see this setting on adminCP?

**Comment by Data66PF** [comment] 2015-12-29 13:36
I can see and confirm what the client is saying. If we send a friend request to someone and they deny the request, it hides just fine but the issue is, now we can never send them another friend request as it doesn't reset the setting or anything. This is a tricky situation though as it could result in someone stalking or harassing another user by repeatedly sending requests when denied. More thought needs to go into whether we change this and how, if we do.

**Comment by neil96** [comment] 2016-01-05 17:20
We have two options for admin in this case:
- First, as @Data66PF commented above.
- Second, User B denied request from user A, user A can send another friend request for user B again.

I enable this setting again on 4.1.2. Here url for that setting: http://yoursite.com/admincp/setting/edit/?module-id=friend . Turn this setting to "No", your problem will be resolved.

**Comment by Ylmzef** [comment] 2016-01-05 17:49
So now i see "Would you like to accept their request to be friends?" meesage when try add user on profile also there in the box option to send friend request. I think it's not need. But the request not listed on /friend/pending/

**Comment by Ylmzef** [comment] 2016-01-16 18:59
@neil96 @phpfoxdev @Vivian-phpFox @RaymondBenc @robert9592  can you fix this in v4.2.0 please?

**Comment by Data66PF** [comment] 2016-01-17 00:02
Do not tag everyone

**Comment by neil96** [comment] 2016-01-19 02:09
@Ylmzef I believed this issue was fixed in V4.1.2, I will test this issue again and reply you later..

**Comment by Data66PF** [comment] 2016-02-18 15:23
@neil96 how did your testing go? Is this resolved in 4.2.2?

**Comment by neil96** [comment] 2016-02-18 16:25
Sorry I miss this issue. I will update status soon.

**Comment by Data66PF** [comment] 2016-03-06 14:41
@neil96 please do. Thanks.

**Comment by neil96** [comment] 2016-03-07 02:02
It's working fine on 4.3

**Closed** 2016-03-07 10:22 UTC
Labels: Cannot reproduce
