### ISSUE TITLE
[Admin CP] Enhancement Request: A search menu that searches available settings in Admin CP

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#182] opened 2015-07-22 10:04 UTC
I've used a few Admin CPs in the past that have a lot of options in random places (like PHPFox). Some had a search feature where you could type in for example: "Photo" and any option that had Photo in it would come up in search results.

Would make setting and finding options a lot easier, especially for those new to the software and learning it on their own. :)

**Comment by Data66PF** [comment] 2015-07-22 12:46
We used to have this feature. I would also like for it to be enabled again.

**Comment by Data66PF** [comment] 2015-07-22 12:50
Oops. This is a duplicate of my #64 that @RaymondBenc requested I start and I have no idea how to merge issues.

**Closed** 2015-08-03 13:58 UTC
Labels: duplicate
