### ISSUE TITLE
Blank notification

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#543] opened 2015-09-24 23:19 UTC
You commentent on my profile but i get this blank notification.

![download](https://cloud.githubusercontent.com/assets/8562514/10089396/61c2f7d0-6323-11e5-8f20-024cae6da247.png)

**Comment by one44** [comment] 2015-09-25 08:45
I am finding notifications clear and disappear so if you get 2 and click on one the second is gone..

**Comment by Data66PF** [comment] 2015-09-25 09:58
I'll probably regret this lol, but can you comment on my profile a few times so I can test both things being mentioned?

**Comment by one44** [comment] 2015-09-25 10:14
No Problem

**Comment by Data66PF** [comment] 2015-09-25 10:19
Ok it didn't disappear until I clicked on both notifications so I can't confirm that.

As for the first issue above, I didn't get any blank notification but I hadn't done a relationship status. Can someone please comment on the relationship status I just did?

**Comment by one44** [comment] 2015-09-25 10:25
I am not sure if these are all related but i get message notifications and when I click to see the message the notification is removed but no message opens. Is an intermittent problem as most messages do show.

**Comment by Data66PF** [comment] 2015-09-25 10:31
Message notifications in email?

**Comment by one44** [comment] 2015-09-25 10:42
No idea but I would assume it is the internal mail system

**Comment by Ylmzef** [comment] 2015-09-25 15:04
On email blank too for me..

**Comment by AnthonyKing** [comment] 2015-09-25 21:52
i would say clear cache, check counters and missing settings/files

**Comment by Ylmzef** [comment] 2015-09-26 01:30
it's from community. :smile:

**Comment by Ylmzef** [comment] 2015-09-26 02:37
![download](https://cloud.githubusercontent.com/assets/8562514/10115448/3c932594-6408-11e5-9b1e-d12d3d1bb012.png)

**Comment by Data66PF** [comment] 2015-09-26 09:16
I just updated my status, http://community.phpfox.com/profile-data66/ , and changed my notifications so I would get an email. Would someone please go comment on it so I can see the email?

**Comment by Ylmzef** [comment] 2015-09-27 01:00
I can't because you removed me as friend :smile:

**Comment by Data66PF** [comment] 2015-09-27 10:39
I don't recall removing you. Feel free to friend me and we can test.

**Comment by Data66PF** [comment] 2015-10-06 09:48
Cannot reproduce at the community
![relat stat](https://cloud.githubusercontent.com/assets/6908282/10305375/e0a873ea-6bed-11e5-97fb-24726070de70.png)

**Comment by Ylmzef** [comment] 2015-10-07 01:46
What was your first changed for relationship?

**Comment by Data66PF** [comment] 2015-10-07 09:00
That was my first one. My other user had not set a relationship before that one.

**Comment by Ylmzef** [comment] 2015-10-07 20:39
It can be type of profile update..

**Comment by phpfoxdev** [comment] 2015-10-26 11:05
Fixed, will be released in next version.

**Comment by Data66PF** [comment] 2015-11-13 12:03
Fixed in v4.0.10 *staff note YPFOXNEUTRON-58 *

**Closed by Data66PF** 2015-11-13 12:03 UTC
Labels: Bug, Cannot reproduce, Fixed

**Comment by Ylmzef** [comment] 2015-11-13 17:58
You forget to mark as fixed.

**Comment by Data66PF** [comment] 2015-11-13 19:26
No, it was already marked fixed.
