### ISSUE TITLE
Script Errors

### ISSUE THREAD

**Issue by TrueAmericans** [moxi9/phpfox#317] opened 2015-08-10 01:11 UTC
This is happening on the PHPfox Community Site as well as on ours... You can't get rid of it without logging out and hope it doesn't come up when you log back in... You can't view the posts hidden by the script errors...

![script errors](https://cloud.githubusercontent.com/assets/13389534/9157867/913e1960-3ed2-11e5-92e2-a2f05c7d0fa4.jpg)

**Comment by Data66PF** [comment] 2015-08-10 10:50
Please always state your OS and browser you are testing with as I can't see that issue when I log in.

**Comment by TrueAmericans** [comment] 2015-08-10 15:32
Happens with Windows 7, 8.1, and 10... I have all 3... Also have Firefox and IE 11... Does it with both...

**Comment by jubelum** [comment] 2015-10-03 06:12
This bug always happen in my website, I use Windows 7, 8.1, 10, Mac, Andorid, iOS, etc... is this related to database? is this a bug in every phpfox software? or is this because I'm using a small vps server?

**Comment by Data66PF** [comment] 2015-10-16 09:52
This is a duplicate of another bug being fixed. #522

**Closed by Data66PF** 2015-10-16 09:52 UTC
Labels: cannot reproduce
