### ISSUE TITLE
Cant upload photos etc after upgrade from v3

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#217] opened 2015-07-26 00:13 UTC
im trying upload photos in "What's up?" section i select photo and click share button after that i see only "Say something about this photo..." entry in news feed. I cant see selected photo.

**Comment by Data66PF** [comment] 2015-07-26 09:26
Please enable debug and check developer browser console when trying to upload the photo. Note that the "say something" is already confirmed in a different report. 

Please also check folder permissions and ensure the server has updated GD libraries, PHP at a minimum of 5.4 .

**Comment by Ylmzef** [comment] 2015-07-26 16:50
Debug mode enabled but cant get any error log.
Forder permissions and server settings already setuped, i have installed v4 as freash install under a subdomain i dont have any issue on it. I have it only upgraded site.

**Comment by Data66PF** [comment] 2015-07-27 21:46
This is probably due to the deprecated getid3 setting. This is addressed in bug #142

**Comment by Data66PF** [comment] 2015-07-27 21:47
Marked a duplicate but not closed yet. Once you upgrade to v4.0.4 when we release it, please let us know if that resolves this issue.

**Comment by Ylmzef** [comment] 2015-07-28 04:02
Upgraded to 4.0.4 but still having this issue.

**Comment by Data66PF** [comment] 2015-07-28 08:54
Did you do the final upgrade steps, http://scripttechs.com/article/354/phpfox-v4-upgrade-final-steps-you-need-to-do/ log in to view.

**Comment by Ylmzef** [comment] 2015-07-28 21:47
I did do now but still have the issue.

**Comment by Ylmzef** [comment] 2015-08-01 00:33
And here is error code:

Exception thrown with message "getimagesize(http://xxxxxxxxxxx.com/file/pic/user/2015/08/298db94b49da55ebb78a50b36ee7f3fd.jpg?t=55bc13904b820): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
"

Stacktrace:
#9 Exception in /home/xxxxxxxxxxx/public_html/PF.Base/start.php:127
#8 Whoops\Exception\ErrorException in /home/xxxxxxxxxxx/public_html/PF.Base/include/library/phpfox/image/helper.class.php:58
#7 Whoops\Run:handleError in <#unknown>:0
#6 getimagesize in /home/xxxxxxxxxxx/public_html/PF.Base/include/library/phpfox/image/helper.class.php:58
#5 Phpfox_Image_Helper:getNewSize in /home/xxxxxxxxxxx/public_html/PF.Base/module/user/include/component/controller/photo.class.php:164
#4 User_Component_Controller_Photo:process in /home/xxxxxxxxxxx/public_html/PF.Base/include/library/phpfox/module/module.class.php:963
#3 Phpfox_Module:getComponent in /home/xxxxxxxxxxx/public_html/PF.Base/include/library/phpfox/module/module.class.php:520
#2 Phpfox_Module:getController in /home/xxxxxxxxxxx/public_html/PF.Base/include/library/phpfox/phpfox/phpfox.class.php:1278
#1 Phpfox:run in /home/xxxxxxxxxxx/public_html/PF.Base/start.php:82
#0 require in /home/xxxxxxxxxxx/public_html/index.php:7

**Comment by Ylmzef** [comment] 2015-08-01 00:42
I found the issue the script looking the upoaded photo under /public_html//file/pic/user/ but its not there its under /public_html/PF.Base/file/pic/user/.

Like as i said from the beginning, its script error!

**Comment by Data66PF** [comment] 2015-08-01 09:22
That is normal. It works the same at phpfox.com community. It ignores showing the PF.Base full path. See at the community.

Ensure getid3 is disabled. Ensure html5 mass uploader is enabled. Use the find missing settings and other steps to get the settings to show on your site.

**Comment by Ylmzef** [comment] 2015-08-01 11:38
But the photo uploaded to /public_html//file/pic/user/ not under /public_html/PF.Base/file/pic/user/
There for im getting not found error.
"failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found"

**Comment by Ylmzef** [comment] 2015-08-01 11:41
Also getid3 disabled and html5 mass uploader enabled from phpmyadmin.

**Comment by Data66PF** [comment] 2015-08-01 15:10
http://community.phpfox.com/photo/ log in there and check those and you will see the same thing. That is how it shows.

**Comment by Ylmzef** [comment] 2015-08-03 01:16
I enabled image protection in v3, i think the issue due the this feature.
Now disabled in phpmyadmin but still the issue.

**Comment by Ylmzef** [comment] 2015-08-03 01:44
And now when i changed url_rewrite to 2 all photos showing fine (old and new photos)
When i changed url_rewrite to 1 only new photos showing

**Comment by Ylmzef** [comment] 2015-08-03 01:45
But forum attachments etc not showin in 1 or 2 value.

**Comment by Ylmzef** [comment] 2015-08-03 02:04
And pure proof of that this issue from script side:
1253.png contains under folder /public_html/PF.Base/file/pic/user AND
03574cb4f157e4893709039590657cc3.jpg contains under folder /public_html/file/pic/user
When i try access to file 1253.png with url way like xxx.com/public_html/PF.Base/file/pic/user/1253.png 
Its shwoing the photo but for  xxx.com/public_html/file/pic/user/03574cb4f157e4893709039590657cc3.jpg
Im getting {"error":404} text from page.
This not server side bug!

**Comment by Ylmzef** [comment] 2015-08-06 12:38
Check this profile: http://community.phpfox.com/johnpaulson/
Same as mine white profile photo on my site like this too old users have white profile photo if they have photos in v3.

**Comment by Data66PF** [comment] 2015-08-06 15:15
I don't have that issue on my site and I'm not sure that the community site has run the counters for photos that must be run to have them update.

**Comment by Data66PF** [comment] 2015-10-16 09:50
We are unable to reproduce this with our test sites and no clients have confirmed this issue.

**Closed by Data66PF** 2015-10-16 09:50 UTC
Labels: cannot reproduce, duplicate
