### ISSUE TITLE
Poke - Notice???

### ISSUE THREAD

**Issue by phpfoxmetro** [moxi9/phpfox#1063] opened 2016-02-03 16:11 UTC
In Stage, when you poke another member, you get a nuisance box titled Notice (see image).  

![image](https://cloud.githubusercontent.com/assets/13341145/12788169/295937b8-ca5e-11e5-8b58-3324dec54df7.png)

**Comment by Data66PF** [comment] 2016-02-03 18:01
I cannot reproduce this on macbook pro el Capitan OS, chrome latest version. The Notice for me shows Poke Sent.

**Comment by phpfoxmetro** [comment] 2016-02-03 19:14
Test redone from a clean install of firefox on Windows 10
![image](https://cloud.githubusercontent.com/assets/13341145/12793713/66d768a8-ca77-11e5-94bd-b69ad013c968.png)

Test done from a different Dell Laptop on Chrome on Windows 10

![image](https://cloud.githubusercontent.com/assets/13341145/12793825/f032d3e4-ca77-11e5-9dad-ed70ab67bba4.png)

**Comment by Data66PF** [comment] 2016-02-03 20:02
We will test on windows as my mac shows it fine.

**Comment by Data66PF** [comment] 2016-02-04 16:24
Tested on win 10 with ff and chrome. I cannot reproduce the images shown. Not sure if there is any browser add on / extension interfering?

**Comment by optiroot** [comment] 2016-02-05 09:09
I can confirm this but not with Poke, I can confirm this about post deleting and moderation (if you approve/disapprove an element pending).

It's not just me but so much people in my website, so it isn't browser-version related.

**Comment by Data66PF** [comment] 2016-02-05 13:16
we need more testing from staff for this as we have other clients that see blank notices as shown above and not just for Pokes. For anything that has a notice such as shown above. Marking a bug for testing further.

**Comment by Data66PF** [comment] 2016-02-08 15:05
I can now reproduce this on a macbook pro with chrome browser when testing as a registered user. Weird issue. Admin user sees the messages.

**Comment by neil96** [comment] 2016-03-08 02:08
Fixed in 4.3.0

**Closed** 2016-03-08 07:28 UTC
Labels: Bug, Fixed
