### ISSUE TITLE
[4.4.0-beta1] Share Video Problem

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#1495] opened 2016-06-28 12:51 UTC
when we share someone uploaded video then open shared post link in new tab its does't show original video.show blank post.i check it on https://v4.phpfox.com/ demo

**Comment by neil96** [comment] 2016-06-29 01:56
Our demo is still using 4.3.2b5. Did you test on our demo or on your 4.4.0beta1 site?
We can't reproduce this issue on 4.4.0beta1

**Comment by SalmanKhan86** [comment] 2016-06-29 04:12
i have tested it on my site with 4.4.0beta1.
![video share problem](https://cloud.githubusercontent.com/assets/13433124/16440259/bc1a2132-3ddd-11e6-9344-74d2c6234095.png)

**Comment by Data66PF** [comment] 2016-06-30 12:12
I can reproduce this in v4.4 on my test site but the site is PHP version 5.4 and we require PHP 5.5 right now so that might be the issue.

**Comment by Data66PF** [comment] 2016-07-04 10:56
Is your server using php 5.5 or up?

**Comment by neil96** [comment] 2016-07-04 16:13
@SalmanKhan86 I think this is another Neutron them issue, Could you try again with bootstrap theme?

**Comment by SalmanKhan86** [comment] 2016-07-05 04:44
i have test it with Phpfox demo site.
this is working fine but when we click this link its show nothing.

![share video](https://cloud.githubusercontent.com/assets/13433124/16574135/39293e82-4299-11e6-9ab2-b11473fd1798.png)

**Comment by Data66PF** [comment] 2016-07-05 13:27
So the video issue is closed then since it works fine on bootstrap demo. The timestamp issue might be another issue but we would need a new ticket but for v4.3.2 as our demo is not v4.4. 

Note that neutron theme issues will not be addressed in this tracker. We would open a new tracker for that after v4.4 depending on what we decide to do with the theme.

**Comment by Data66PF** [comment] 2016-07-06 11:24
Reopening for further testing at our staging site.

**Comment by neil96** [comment] 2016-07-21 02:35
I can't reproduce this issue on our demo (4.4.0RC1)

**Comment by Data66PF** [comment] 2016-07-29 12:10
@neil96 if this is not reproduced at the demo, I think we can close it as we won't address the Neutron theme issue here. If you agree.

**Closed** 2016-07-31 08:50 UTC
Labels: Bug
