### ISSUE TITLE
Mobile Users Not Getting Confirmation Of Main Photo (Avatar) Uploads

### ISSUE THREAD

**Issue by queenmother305** [moxi9/phpfox#1416] opened 2016-05-11 16:30 UTC
I mentioned this within another bug I submitted but it seems to be over looked so I am creating this seperate report for it. It seems mobile users are not receiving any kind of "photo uploaded successfully" alert after uploading their main profile photo/avatar. This is causing the users to continuously upload the same photo over and over because it appears to them it's not being uploaded. Aside from this wasting space on our servers, it makes the photo gallery appear redundant with several groups of the same profile photo being shown over and over again. Please see attached. Aside from having to constantly rotate photos as mentioned in the other bug I submitted I am also constantly having to delete duplicate photos ALL DAY LONG. Please fix this so mobile users know their profile photo was uploaded successfully.
![screenshot 32](https://cloud.githubusercontent.com/assets/19175383/15188504/194f4476-1774-11e6-87c4-58d4768e9e72.png)

**Comment by neil96** [comment] 2016-05-12 02:00
@queenmother305 Did you test on mobile or your just saw duplicate photo in your site?

**Comment by queenmother305** [comment] 2016-05-12 03:49
I did not test on mobile. But I have tested uploading an avatar/display photo in firefox, explorer, and chrome on my laptop and it works fine. I am assuming the problem is mobile. I could be wrong about the source of the issue, but it's still definitely a bug.

**Comment by Data66PF** [comment] 2016-05-12 12:06
I think this is due to the other bug report and will clear up after as I did post the issue I found.

**Comment by queenmother305** [comment] 2016-05-15 16:08
Data this is driving me nuts and making my site look TERRIBLE. 

![screenshot 36](https://cloud.githubusercontent.com/assets/19175383/15275303/c5ffda04-1a95-11e6-854d-4471c5f1ce91.png)

**Comment by queenmother305** [comment] 2016-05-15 16:10
I should also mention that to best see this bug you should have the option for profile photos to be displayed in the main photo gallery.

**Comment by Data66PF** [comment] 2016-05-16 16:52
We can't fix bugs any faster than we are though. I still think this is a duplicate of the other issue.

**Comment by queenmother305** [comment] 2016-05-16 20:35
My concern is that if this is not marked as a bug and investigated seperately, then it ends up not being fixed until the release after the next release. The two could be related, and fixing one may resolve the other, but what if it doesn't, will we have to wait? This is an absolute nuisance to have to continually delete duplicates.

**Comment by Data66PF** [comment] 2016-05-19 10:40
@neil96 can you test to see if this one is related to the other one already marked a bug?

**Comment by queenmother305** [comment] 2016-05-19 12:48
I could be wrong about it being just mobile users. I noticed when uploading a photo yesterday that I hit the button twice by accident and it uploaded it twice. Is there a possibility everyone is just clicking the button multiple times? And if so, are there any safeguards we could put in place to prevent this from happening?

**Comment by queenmother305** [comment] 2016-06-04 02:27
I was wondering if maybe this is due to mobile users trying to use the crop feature? Is there a way to make the crop feature switch over to a mobile friendly touch version the site is being viewed at a smaller size since it's likely the user will be using mobile? I think maybe people are attempting to use the crop feature and that might be why they keep clicking the save avatar button. Not sure, just an idea.

**Comment by neil96** [comment] 2016-06-05 00:58
@queenmother305 On 4.4, we use new way to crop profile photo, it support crop on mobile.

**Comment by queenmother305** [comment] 2016-06-05 01:10
@neil96 is there a date for 4.4 release?

**Comment by Data66PF** [comment] 2016-06-29 16:19
The beta is out but we are not ready to have a stable release date yet. Will close this for now and if the issue persists once v4.4 stable is released, please open a new bug for us to test.

**Closed by Data66PF** 2016-06-29 16:19 UTC
