### ISSUE TITLE
Newsletter HTML problem

### ISSUE THREAD

**Issue by queenmother305** [moxi9/phpfox#1537] opened 2016-07-07 13:58 UTC
When you send out an html newsletter it displays the actual html code in emails, it's not being converted to display the images or other html that the code reflects.

**Comment by jhayden2000** [comment] 2016-07-07 15:01
i had a similar issue. are you using the bbc code editor??

**Comment by Data66PF** [comment] 2016-07-07 20:59
https://github.com/moxi9/phpfox/issues/1360 it shows fixed in 4.4. Are you both using v4.4?

**Comment by Data66PF** [comment] 2016-07-08 09:48
I cannot reproduce this in 4.4. I clicked to Get Plain Text from Html before sending the newsletter. I'm checking the email in google in my browser log in and not with any email thing like thunderbird. Perhaps the email program you are using to get your email is showing something else. What are you getting the email with?

**Comment by Spaninet** [comment] 2016-07-10 14:42
Same issue in my upgraded site (4.3.2b5 ➡ 4.4.0-beta1). I have BBCode App installed

**Comment by Data66PF** [comment] 2016-07-10 23:21
Don't use any apps with v4.4. It is a beta and should not be used with apps yet.

**Comment by Data66PF** [comment] 2016-07-12 12:05
Please test once we release RC version.

**Closed by Data66PF** 2016-07-12 12:05 UTC
Labels: Cannot reproduce

**Comment by Spaninet** [comment] 2016-07-12 12:56
I'll wait RC version.

**Comment by jhayden2000** [comment] 2016-07-12 13:02
Is there an ETa on the RC?
