### ISSUE TITLE
[4.2.1b5] Sharing a picture on your friend's wall issue

### ISSUE THREAD

**Issue by MichelangeloF** [moxi9/phpfox#1094] opened 2016-02-07 12:56 UTC
If you share a picture on your friend's wall the picture will appear on your wall too.

**Comment by neil96** [comment] 2016-02-07 13:44
Can't reproduce on https://v4.phpfox.com - chrome - ubuntu. Could you give us more information. Thanks!

**Comment by MichelangeloF** [comment] 2016-02-07 13:51
I have an upgraded site. 
Please try to share a pic from a fan page with a friend of yours and the image will go on your wall too.
Otherwise, maybe this problem affects upgraded sites only.

**Comment by neil96** [comment] 2016-02-07 13:54
What is original version of your site?

**Comment by MichelangeloF** [comment] 2016-02-07 13:55
I started from 4.0.1

**Comment by MichelangeloF** [comment] 2016-02-07 13:56
Tried again now and It did the same thing.

**Comment by neil96** [comment] 2016-03-01 08:37
Fixed on V4.3.0

**Closed** 2016-03-03 10:16 UTC
Labels: Bug, Fixed
