### ISSUE TITLE
New user online when hovering pop-up is non persistent

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#635] opened 2015-10-16 20:07 UTC
I originally asked for this issue, and it actually works very well but I have noticed one issue in regard. Once the pop-up displays and the mouse is moved into the box, it does not persist as long as the mouse is within the popups borders.  Very flitty.  Sometimes it will close in a fraction of a second (flashes) even when the mouse is with the bounds of the box.  Other times it may give you a second or so, and yet other times it will persist.

There is a built in send message button on the bottom that eight times out of ten, the box disappears under the cursor before getting to the button to send a message.  It really takes a "fast gun" to send a message this way.

I think all that is needed is a way to keep the pop-up persistent as long as the cursor is within its borders.

**Comment by Data66PF** [comment] 2015-10-16 20:36
confirmed and it is bug #483 that was marked fixed for this version but it seems it is still an issue at the community.

**Comment by SalmanKhan86** [comment] 2015-10-17 11:20
i also found same problem many times.Confirm.

**Comment by aakash83** [comment] 2015-10-17 23:14
I noticed that the problem is only with your own name (when you hover mouse on your own name then the popup disappears immediately). if you hover mouse on someone else name it don't disappear immediately.

**Comment by Data66PF** [comment] 2015-10-18 09:34
For me it disappears on anyone's name in the feed.

**Comment by Gatsby-PF** [comment] 2015-10-18 15:14
This may be in part due to how the browser handles pop-ups.  My issue was detected using Firefox 41.

**Comment by Gatsby-PF** [comment] 2015-10-18 15:14
This may be in part due to how the browser handles pop-ups.  My issue was detected using Firefox 41.

**Comment by Gatsby-PF** [comment] 2015-11-02 17:59
Please ensure that this issue is included in the next release.  The unstable nature of this is a potentially high user experience killer.

**Comment by neil96** [comment] 2015-11-27 15:22
Fixed in v4.0.10 staff note *YPFOXNEUTRON-82*

**Closed by neil96** 2015-11-27 15:22 UTC
Labels: Bug, Fixed, Minor
