### ISSUE TITLE
Neutron Mobile Responsive problem

### ISSUE THREAD

**Issue by Alexlim91** [moxi9/phpfox#598] opened 2015-10-08 06:56 UTC
Hi Moxi9,
I realize there are few problem with neutron in mobile view, when using the smartphone to view the neutron (demo version) why the screen cannot fully fix to the screen, below there still moving scroll. 
Besides that, i also found out when using mobile view, the like button is no function sometime function sometime no function. 

![error](https://cloud.githubusercontent.com/assets/14208881/10359557/5c403fda-6dcc-11e5-9b1b-ae76d58aaf41.png)

**Comment by Data66PF** [comment] 2015-10-08 08:32
Please always state the device you are using and the browser and OS version.

**Comment by Alexlim91** [comment] 2015-10-08 08:38
I using android phone and I using chrome and internet explorer

**Comment by SalmanKhan86** [comment] 2015-10-08 10:45
i have also few Problems Regarding Android OS. pls check screenshot.
1.when we hide/show toggle menu.

![screenshot_2015-08-10-09-40-40](https://cloud.githubusercontent.com/assets/13433124/10364141/9b660a00-6dd6-11e5-85f7-880680cf4cfc.png)
2.
![screenshot_2015-10-08-15-47-32](https://cloud.githubusercontent.com/assets/13433124/10364207/0d1197b4-6dd7-11e5-9aff-275c5920acaf.png)

3.when we open Messages then it not show pop up box.we have't any option to reply it.

![screenshot_2015-10-08-15-54-16](https://cloud.githubusercontent.com/assets/13433124/10364280/a61c143e-6dd7-11e5-9f60-44e8df7bb350.png)

**Comment by SalmanKhan86** [comment] 2015-10-08 10:51
4. when we go to the forget password page from login screen

![screenshot_2015-08-10-09-42-46](https://cloud.githubusercontent.com/assets/13433124/10364393/9120c6a0-6dd8-11e5-948c-c2f0de6ba869.png)

**Comment by Data66PF** [comment] 2015-10-08 11:04
Please note that we take one issue per report and the things you just posted were in another bug. Please don't duplicate them.

**Comment by SalmanKhan86** [comment] 2015-10-08 11:07
ok i posted it as one issue per report in separate bug

**Comment by Data66PF** [comment] 2015-10-08 11:08
It was already posted before so I hope you didn't just post it again lol. Did you search?

**Comment by Data66PF** [comment] 2015-10-16 10:53
duplicate of #574 which shows the cut off feeds.

**Closed by Data66PF** 2015-10-16 10:53 UTC

**Comment by SalmanKhan86** [comment] 2015-12-19 12:00
like button is no function sometime problem is not fixed yet in v 4.1.1.same problem in Android OS Chrome Browser
