### ISSUE TITLE
Powered by phpfox in skype

### ISSUE THREAD

**Issue by mralexrud** [moxi9/phpfox#1520] opened 2016-07-04 18:59 UTC
When I send links on my site in Skype is the display "powered by phpfox" see the screenshot. In Facebook everything is working properly.  phpfox 4.3.2 b5
![screenshot_5](https://cloud.githubusercontent.com/assets/20287387/16568435/cb4b012c-4232-11e6-9db8-103b1b5a07c6.jpg)

**Comment by Data66PF** [comment] 2016-07-05 10:40
We are not able to reproduce your issue. Can you give us more details? Do you have an app that you share with? Is this an upgraded site or fresh install? We even tried sharing a link from your site and did not have branding showing.

**Comment by mralexrud** [comment] 2016-07-05 11:18
I think I figured it out. Skype probably uses its internal cache. When I send from my Skype link I have displayed powered by phpfox. However, when sent from other Skype users, they display all the right. Thank you. Can I delete the topic?

**Comment by Data66PF** [comment] 2016-07-05 13:24
I'll close it. Thanks for updating us.:)

**Closed by Data66PF** 2016-07-05 13:24 UTC
Labels: Cannot reproduce
