### ISSUE TITLE
Ad Module not working properly

### ISSUE THREAD

**Issue by haisay** [moxi9/phpfox#150] opened 2015-07-20 04:38 UTC
Ads not working properly.
Admin able to create ads through the Admin panel. But the ad not running. as well as not able to properly defile the block.

please check the module and confirm.

**Comment by Data66PF** [comment] 2015-07-20 15:49
Please make sure the setting for Enable Advanced Ad Filters is off and that the admin user group settings are set so Admin can see Ads if testing with that group or for whatever group you are testing with. Please also check the date of the ad. My ads are working on my live test site.

**Comment by haisay** [comment] 2015-07-25 08:18
In my site it is not working.
ad filter is in off mode.
date is ok.

i created ads through as a user.
admin approved the ad through admin panel.(Payment not made) 
ads start  to display. but when i click on the ad the link direct to "www.sitename.com/index.php/ad/manage/"

if i create ads through admin->settings->ads->Manage sponsorships

the ad can create but not able to see on the list. as well as that ads not showing in site.

Please check and confirm!

**Comment by Data66PF** [comment] 2015-07-25 17:20
We would like to have one issue per bug please. It makes following the bug easier. For this, issue 1 of the user created ads and the link, I cannot reproduce it in v4.0.3 as the links work fine for me. I put the full link with the http:// as part of it.

Second issue, I see that my ads created in admin are not showing but I believe that was addressed in another bug report that ads in admin are to be made in blocks. I'll mark this as confirmed so Ray can provide feedback about this issue.

**Comment by haisay** [comment] 2015-07-26 16:53
Thanks for the reply.
I'm not able to edit the user created ads destination links through the admin panel. The link editing field not showing.

**Closed** 2015-08-04 07:21 UTC
Labels: bug
