### ISSUE TITLE
Membership in ACP Actions

### ISSUE THREAD

**Issue by TrueAmericans** [moxi9/phpfox#140] opened 2015-07-18 04:17 UTC
In the Admin Control Panel we can't approve, verify, delete, etc., any of the memberships, pending or ortherwise... The requested actions don't happen... We've done Fresh installs as well as upgrades and it's the same results...

**Comment by RaymondBenc** [comment] 2015-07-20 18:31
I wasn't able to reproduce this locally using our latest build. @Data66PF can you reproduce this?

**Comment by Data66PF** [comment] 2015-07-20 18:57
Yes, I can reproduce it if I click the checkbox to the left of the user waiting approval and then at the bottom of the screen, click the Approve. This way, it doesn't show an approved notification. It makes it look like nothing happens because the checkbox remains checked and no process seems to continue. However, if you refresh the page, you see that the user was approved. It just needs a kick to get it to show the approval was done.

**Comment by Data66PF** [comment] 2015-07-21 22:07
This is a duplicate of #69

**Comment by Data66PF** [comment] 2015-07-24 13:37
Confirming this one and closing the old one.

**Closed** 2015-07-25 20:01 UTC
Labels: bug, help wanted
